//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AppData, NSDictionary, NSMutableArray, NSMutableDictionary, SaavnVC_n, UserData;

@interface DataManager : NSObject
{
    id responseData;
    SaavnVC_n *requestedVC;
    AppData *appData;
    UserData *userData;
    NSMutableArray *topShowsArray;
    NSMutableDictionary *fetchingInfo;
    NSDictionary *appLaunchData;
    NSDictionary *globalConfig;
    NSDictionary *homepageData;
    NSDictionary *loggedUserData;
    NSMutableArray *topSearchesData;
    NSDictionary *radioData;
}

+ (void)savedZlaUserData:(id)arg1;
+ (void)savedCurrentUserData:(id)arg1;
+ (void)savedCurrentHomeData:(id)arg1;
+ (void)savedCurrentLaunchData:(id)arg1;
+ (void)savedCurrentData:(id)arg1 withKey:(id)arg2;
+ (id)getSavedZlaUserData;
+ (id)getSavedHomeSourceApiData;
+ (id)getSavedUserData;
+ (id)getSavedHomeData;
+ (id)getSavedLaunchData;
+ (void)flushCachedData;
+ (id)sharedManager;
@property(retain, nonatomic) NSDictionary *radioData; // @synthesize radioData;
@property(retain, nonatomic) NSMutableArray *topSearchesData; // @synthesize topSearchesData;
@property(retain, nonatomic) NSDictionary *loggedUserData; // @synthesize loggedUserData;
@property(retain, nonatomic) NSDictionary *homepageData; // @synthesize homepageData;
@property(retain, nonatomic) NSDictionary *globalConfig; // @synthesize globalConfig;
@property(retain, nonatomic) NSDictionary *appLaunchData; // @synthesize appLaunchData;
- (void).cxx_destruct;
- (void)replaceProStatus:(id)arg1;
- (id)replaceProStatus:(id)arg1 forInfo:(id)arg2;
- (id)getGlobalConfigObject:(id)arg1;
- (id)getGlobalConfigVal:(id)arg1;
- (id)getStreamConfig;
- (id)getAdConfig;
- (id)getSurpriseMes;
- (id)getTop15s;
- (id)getSupportedLanguages;
- (id)getSupportedRadioLanguages;
- (id)getGlobalConfig;
- (id)getTopShows;
- (id)getCharts;
- (id)getRecentlyPlayed;
- (id)getChannels;
- (id)getSuggestions;
- (id)getTopPlaylist;
- (id)getNewTrending;
- (id)getNewAlbums;
- (id)getFeaturedStation;
- (id)getTopSearchesData;
- (id)getUserData;
- (id)getHomeData;
- (id)getLaunchData;
- (id)getRequestedVC;
- (id)getCurrentResponseDataFor:(id)arg1;
- (id)getCurrentResponseData;
- (void)flushRequestedData;
- (void)parseSourceData:(id)arg1 withSource:(id)arg2;
- (void)fetchDataForSource:(id)arg1;
- (void)setUserLoggedData:(id)arg1;
- (void)parseHomepageData:(id)arg1 isLocal:(_Bool)arg2;
- (void)fetchHomepageData;
- (void)broadcastNotification:(long long)arg1 withData:(id)arg2;
- (void)broadcastNotification:(long long)arg1;
- (void)fetchData:(id)arg1 withParams:(id)arg2 success:(CDUnknownBlockType)arg3 andFailure:(CDUnknownBlockType)arg4;
- (void)fetchData:(id)arg1 withParams:(id)arg2 from:(id)arg3;
- (void)fetchData:(id)arg1 withParams:(id)arg2;
- (void)fetchData:(id)arg1 withParams:(id)arg2 inArray:(id *)arg3;
- (void)fetchData:(id)arg1 withParams:(id)arg2 inDict:(id *)arg3;
- (id)init;

@end

