//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface LyricsAnnotation : NSObject
{
    long long _startIndex;
    long long _endIndex;
    NSString *_title;
    NSString *_annotation;
}

@property(copy, nonatomic) NSString *annotation; // @synthesize annotation=_annotation;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long endIndex; // @synthesize endIndex=_endIndex;
@property(nonatomic) long long startIndex; // @synthesize startIndex=_startIndex;
- (void).cxx_destruct;
- (id)init;

@end

