//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface PaywallManager : NSObject
{
    _Bool _showPaywallScreen;
    _Bool _showSplashScreen;
    int _paywallType;
    NSDictionary *launchConfig;
    NSDictionary *_specialOfferInfo;
}

+ (void)setPickerPending;
+ (_Bool)isProRowUser;
+ (void)setPaywallActive:(_Bool)arg1;
+ (_Bool)isLoginwallActive;
+ (_Bool)isPaywallActive;
+ (id)sharedManager;
@property(retain, nonatomic) NSDictionary *specialOfferInfo; // @synthesize specialOfferInfo=_specialOfferInfo;
@property(nonatomic) int paywallType; // @synthesize paywallType=_paywallType;
@property(nonatomic) _Bool showSplashScreen; // @synthesize showSplashScreen=_showSplashScreen;
@property(nonatomic) _Bool showPaywallScreen; // @synthesize showPaywallScreen=_showPaywallScreen;
@property(retain, nonatomic) NSDictionary *launchConfig; // @synthesize launchConfig;
- (void).cxx_destruct;
- (id)getCurrentPaywallVC;
- (unsigned long long)getTrialDuration:(int)arg1;
- (void)dismissHomeCover;
- (void)showPaywallExpiredUI;
- (void)showPaywallTrialUI;
- (void)showPaywallSplashScreenUI;
- (_Bool)showPaywallUI;
- (void)removePaywallIfAny;
- (void)setupABTestingBucket:(id)arg1;
- (void)updateProductInfo:(id)arg1;
- (void)checkForSponsoredOffers:(id)arg1;
- (_Bool)checkIfPaywallActive:(id)arg1;
- (_Bool)checkIfLoginwallActive:(id)arg1;
- (_Bool)checkIfPaywallOrLoginwallActive:(id)arg1;
- (_Bool)isUserAbuseCase:(id)arg1;
- (void)pausePlayer;
- (_Bool)forcePaywall:(id)arg1;

@end

