//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class RJILMediaAnalyticsNwStatusChk;

@interface RJILInternetConnectionStatus : NSObject
{
    _Bool _isInternetActive;
    _Bool _isHostActive;
    _Bool _isStartNotify;
    RJILMediaAnalyticsNwStatusChk *_internetReachable;
    RJILMediaAnalyticsNwStatusChk *_hostReachable;
}

+ (id)internetConnectionStatus;
@property(retain, nonatomic) RJILMediaAnalyticsNwStatusChk *hostReachable; // @synthesize hostReachable=_hostReachable;
@property(retain, nonatomic) RJILMediaAnalyticsNwStatusChk *internetReachable; // @synthesize internetReachable=_internetReachable;
@property(nonatomic) _Bool isStartNotify; // @synthesize isStartNotify=_isStartNotify;
@property(nonatomic) _Bool isHostActive; // @synthesize isHostActive=_isHostActive;
@property(nonatomic) _Bool isInternetActive; // @synthesize isInternetActive=_isInternetActive;
- (void).cxx_destruct;
- (_Bool)isInternetStatusActive;
- (void)checkNetworkStatus:(id)arg1;
- (void)stopInternetUpdateStatus;
- (void)startInternetStatus;
- (id)init;

@end

