//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVCaptureVideoDataOutput.h>

@interface AVCaptureVideoDataOutput (GWADispatcher)
- (void)setSampleBufferDelegate:(id)arg1 dispatcher:(id)arg2;
@end

