//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ApiaryConsistencyTokenResponseHeader, NSMutableArray;
@protocol FCDGTMTransport;

@protocol FCDBoqDataTransportOperationDelegate <NSObject>
- (void)updateConsistencyTokenJarsWithHeader:(ApiaryConsistencyTokenResponseHeader *)arg1;
- (NSMutableArray *)activeConsistencyTokenJars;
- (id <FCDGTMTransport>)gtmTransport;
@end

