//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FCDInterceptor-Protocol.h"

@class NSString;
@protocol FCDRPCLogger, OS_dispatch_queue;

@interface FCDLoggingInterceptor : NSObject <FCDInterceptor>
{
    id <FCDRPCLogger> _rpcLogger;
    double _rpcStartTime;
    NSObject<OS_dispatch_queue> *_interceptorQueue;
}

+ (id)stage;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *interceptorQueue; // @synthesize interceptorQueue=_interceptorQueue;
- (void).cxx_destruct;
- (void)rpcRequestDidFinish:(id)arg1 requestContext:(id)arg2 response:(id)arg3;
- (void)rpcRequestWillStart:(id)arg1 context:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)initWithRPCLogger:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

