//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MDCButton, NSString;

@interface GRWCardAction : NSObject
{
    NSString *_title;
    NSString *_localizedAccessibilityHint;
    unsigned long long _style;
    MDCButton *_button;
    CDUnknownBlockType _actionBlock;
}

+ (id)actionWithTitle:(id)arg1 localizedAccessibilityHint:(id)arg2 style:(unsigned long long)arg3 primaryColor:(id)arg4 actionBlock:(CDUnknownBlockType)arg5;
+ (id)actionWithTitle:(id)arg1 style:(unsigned long long)arg2 primaryColor:(id)arg3 actionBlock:(CDUnknownBlockType)arg4;
+ (id)dismissActionWithBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(readonly, nonatomic) MDCButton *button; // @synthesize button=_button;
@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_style;
@property(readonly, nonatomic) NSString *localizedAccessibilityHint; // @synthesize localizedAccessibilityHint=_localizedAccessibilityHint;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)buttonPressed;
- (id)initWithTitle:(id)arg1 localizedAccessibilityHint:(id)arg2 style:(unsigned long long)arg3 primaryColor:(id)arg4 actionBlock:(CDUnknownBlockType)arg5;

@end

