//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GRWExperimentsDataSource, GRWUserAccounts, NSDictionary;

@interface GRWExperimentsCache : NSObject
{
    NSDictionary *_userFlagsDictionary;
    GRWExperimentsDataSource *_dataSource;
    GRWUserAccounts *_userAccounts;
}

@property(retain, nonatomic) GRWUserAccounts *userAccounts; // @synthesize userAccounts=_userAccounts;
@property(retain, nonatomic) GRWExperimentsDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain) NSDictionary *userFlagsDictionary; // @synthesize userFlagsDictionary=_userFlagsDictionary;
- (void).cxx_destruct;
- (void)forceSyncWithServer:(CDUnknownBlockType)arg1;
- (id)flagsForUserID:(id)arg1;
- (void)loadCache;
- (void)refreshCache;
- (id)experimentsForUserID:(id)arg1;
- (id)validExperimentIDsForUserID:(id)arg1;
- (id)flagsForElementName:(id)arg1 withUserID:(id)arg2;
- (id)initWithUserAccounts:(id)arg1 fetcher:(id)arg2 deviceState:(id)arg3;

@end

