//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSArray;

@interface GRWExperiment : NSObject <NSSecureCoding>
{
    _Bool _dogfoodOnly;
    NSArray *_flags;
    long long _experimentId;
    long long _firstSupportedVersion;
    long long _lastSupportedVersion;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic, getter=isDogfoodOnly) _Bool dogfoodOnly; // @synthesize dogfoodOnly=_dogfoodOnly;
@property(readonly, nonatomic) long long lastSupportedVersion; // @synthesize lastSupportedVersion=_lastSupportedVersion;
@property(readonly, nonatomic) long long firstSupportedVersion; // @synthesize firstSupportedVersion=_firstSupportedVersion;
@property(nonatomic) long long experimentId; // @synthesize experimentId=_experimentId;
@property(retain, nonatomic) NSArray *flags; // @synthesize flags=_flags;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToExperiment:(id)arg1;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
@property(readonly, nonatomic, getter=isValidForCurrentEnvironment) _Bool validForCurrentEnvironment;
@property(readonly, nonatomic, getter=isValidForCurrentVersion) _Bool validForCurrentVersion;
- (id)initWithFlags:(id)arg1 firstSupportedVersion:(long long)arg2 lastSupportedVersion:(long long)arg3 experimentId:(long long)arg4 dogfoodOnly:(_Bool)arg5;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

