//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GRWMessagingCacheListener : NSObject
{
    id _listener;
    CDUnknownBlockType _eventBlock;
}

@property(copy, nonatomic) CDUnknownBlockType eventBlock; // @synthesize eventBlock=_eventBlock;
@property(nonatomic) __weak id listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)sendEvent:(long long)arg1;
- (_Bool)isListenerValid;
- (void)dealloc;
- (id)initWithListener:(id)arg1 eventBlock:(CDUnknownBlockType)arg2;

@end

