//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTLRObject.h"

@class GTLRUserDataControls_ClientLayoutOverwritesAndroidLayoutOverwrites;

@interface GTLRUserDataControls_ClientLayoutOverwrites : GTLRObject
{
}


// Remaining properties
@property(retain, nonatomic) GTLRUserDataControls_ClientLayoutOverwritesAndroidLayoutOverwrites *androidOverwrites; // @dynamic androidOverwrites;
@end

