//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GWADependencyGraphComponent-Protocol.h"
#import "GWAForm-Protocol.h"

@class GWAButtonFlowSection, NSArray, NSString;

@interface GWAPageFooter : NSObject <GWADependencyGraphComponent, GWAForm>
{
    NSArray *_simpleFormsArray;
    GWAButtonFlowSection *_buttonSection;
}

- (void).cxx_destruct;
- (void)unRegisterWithDependencyGraph:(id)arg1;
- (void)registerWithDependencyGraph:(id)arg1;
- (_Bool)didHandleErrorMessage:(id)arg1;
- (id)sections;
- (id)value;
- (id)initWithSubmitButton:(id)arg1 cancelButton:(id)arg2 context:(id)arg3;
- (id)initWithPageFooter:(id)arg1 context:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

