//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HAMFormatDescription, HAMFormatSelection;

@interface HAMSampleBuffer : NSObject
{
    CDStruct_d2aef016 *_sampleTimingInfoArray;
    unsigned long long *_sampleSizeArray;
    _Bool _isSync;
    int _sampleCount;
    struct opaqueCMSampleBuffer *_sampleBuffer;
    HAMFormatDescription *_formatDescription;
    HAMFormatSelection *_formatSelection;
    double _productionTime;
    CDStruct_1b6d18a9 _lastSamplePresentationEndTime;
}

+ (id)sampleBufferWithBlockBuffer:(struct OpaqueCMBlockBuffer *)arg1 dataOffset:(unsigned long long)arg2 dataSize:(unsigned long long)arg3 sampleCount:(int)arg4 sampleSizeArray:(const unsigned long long *)arg5 sampleTimingArray:(const CDStruct_d2aef016 *)arg6 formatDescription:(id)arg7 formatSelection:(id)arg8 productionTime:(double)arg9 isSync:(_Bool)arg10 error:(id *)arg11;
@property(readonly, nonatomic) _Bool isSync; // @synthesize isSync=_isSync;
@property(readonly, nonatomic) CDStruct_1b6d18a9 lastSamplePresentationEndTime; // @synthesize lastSamplePresentationEndTime=_lastSamplePresentationEndTime;
@property(readonly, nonatomic) double productionTime; // @synthesize productionTime=_productionTime;
@property(readonly, nonatomic) HAMFormatSelection *formatSelection; // @synthesize formatSelection=_formatSelection;
@property(readonly, nonatomic) int sampleCount; // @synthesize sampleCount=_sampleCount;
@property(readonly, nonatomic) HAMFormatDescription *formatDescription; // @synthesize formatDescription=_formatDescription;
@property(readonly, nonatomic) struct opaqueCMSampleBuffer *sampleBuffer; // @synthesize sampleBuffer=_sampleBuffer;
- (void).cxx_destruct;
- (void)enumerateTimingInfoAndSizeUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateTimingInfoUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) CDStruct_1b6d18a9 decodeTime;
@property(readonly, nonatomic) CDStruct_1b6d18a9 presentationDuration;
@property(readonly, nonatomic) CDStruct_1b6d18a9 presentationTime;
@property(readonly, nonatomic) const unsigned long long *sampleSizeArray; // @synthesize sampleSizeArray=_sampleSizeArray;
@property(readonly, nonatomic) const CDStruct_d2aef016 *sampleTimingInfoArray; // @synthesize sampleTimingInfoArray=_sampleTimingInfoArray;
@property(readonly, nonatomic) struct OpaqueCMBlockBuffer *dataBuffer;
- (void)dealloc;
- (id)init;
- (id)initWithSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 formatSelection:(id)arg2 formatDescription:(id)arg3;

@end

