//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "HAMVideoDecoder-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString;
@protocol HAMVideoDecoderDelegate, OS_dispatch_queue;

@interface HAMVPXVideoDecoder : NSObject <HAMVideoDecoder>
{
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSObject<OS_dispatch_queue> *_decodeQueue;
    _Bool _supportsSDR;
    _Bool _supportsHDR;
    unsigned int _codec;
    NSDictionary *_pixelBufferAttributes;
    struct {
        int threads;
    } _config;
    // Error parsing type: {atomic<int>="__a_"Ai}, name: _samplesPendingDecode
    // Error parsing type: {atomic<unsigned int>="__a_"AI}, name: _frameEra
    _Bool _prepared;
    _Bool _terminated;
    struct vpx_codec_ctx _decoder;
    struct __CVPixelBufferPool *_pixelBufferPool;
    unsigned long long _bufferPoolWidth;
    unsigned long long _bufferPoolHeight;
    unsigned long long _bufferPoolBitDepth;
    NSMutableDictionary *_pixelBufferAttachments;
    id _currentFormatDescription;
    _Bool _internalDidFailWithError;
    id <HAMVideoDecoderDelegate> _delegate;
}

@property(nonatomic) __weak id <HAMVideoDecoderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)configurePixelBufferPoolForImage:(const struct vpx_image *)arg1;
- (void)internalFailWithError:(id)arg1;
- (void)internalTerminate;
- (void)internalDecodeSampleBuffer:(id)arg1 dropFrame:(_Bool)arg2 frameEra:(unsigned int)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)internalPrepare;
- (void)decodeSampleBuffer:(id)arg1 dropFrame:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)canAcceptFormatWithDescription:(id)arg1;
- (void)terminate;
- (void)discardPendingFrames;
- (void)prepare;
@property(readonly, nonatomic) int maxSampleCount;
@property(readonly, nonatomic) int samplesPendingDecode;
- (void)dealloc;
- (id)init;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2 decodeQueue:(id)arg3 formatDescription:(id)arg4 pixelBufferAttributes:(id)arg5 supportedPixelFormats:(id)arg6 config:(CDStruct_fcaf9308)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

