//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MDXSmartPairingDeviceCell.h"

@class MDXScreenManager;

@interface MDXSmartPairingConnectDeviceCell : MDXSmartPairingDeviceCell
{
    _Bool _connected;
    MDXScreenManager *_screenManager;
}

- (void).cxx_destruct;
- (id)rightButtonTitle;
- (void)didPressRightButton:(id)arg1;
- (void)setConnected:(_Bool)arg1;
- (void)setScreenManager:(id)arg1;

@end

