//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVAssetDownloadDelegate-Protocol.h"
#import "MLMediaDownloader-Protocol.h"

@class AVAssetDownloadTask, AVAssetDownloadURLSession, GIMMe, MLVideo, NSDate, NSString;
@protocol MLMediaDownloaderDelegate;

@interface MLAVAssetDownloader : NSObject <AVAssetDownloadDelegate, MLMediaDownloader>
{
    id <MLMediaDownloaderDelegate> _currentDelegate;
    AVAssetDownloadURLSession *_URLSession;
    long long _currentBitrate;
    double _secondsLoaded;
    double _secondsExpectedToLoad;
    NSDate *_startDate;
    MLVideo *_currentVideo;
    GIMMe *_gimme;
    AVAssetDownloadTask *_currentDownloadTask;
}

@property(retain, nonatomic) AVAssetDownloadTask *currentDownloadTask; // @synthesize currentDownloadTask=_currentDownloadTask;
@property(nonatomic) __weak GIMMe *gimme; // @synthesize gimme=_gimme;
- (void).cxx_destruct;
- (long long)sizeOfBundleForVideoID:(id)arg1;
- (id)masterPlaylistDataForAudioStream:(id)arg1 videoStream:(id)arg2 error:(id *)arg3;
- (long long)estimatedTotalBitsForCurrentVideo;
- (long long)estimatedTotalBytesForCurrentVideo;
- (long long)estimatedDownloadedBitsForCurrentVideo;
- (long long)estimatedDownloadedBytesForCurrentVideo;
- (void)clear;
- (void)failWithError:(id)arg1;
- (void)beginDownloadWithVideoID:(id)arg1;
- (_Bool)prepareDownloadWithAudioStream:(id)arg1 videoStream:(id)arg2 videoID:(id)arg3;
- (void)URLSession:(id)arg1 assetDownloadTask:(id)arg2 didLoadTimeRange:(CDStruct_e83c9415)arg3 totalTimeRangesLoaded:(id)arg4 timeRangeExpectedToLoad:(CDStruct_e83c9415)arg5;
- (void)URLSession:(id)arg1 assetDownloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)cancelDownloadWithVideoID:(id)arg1;
- (void)cancelDownload;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)downloadVideo:(id)arg1 audioStream:(id)arg2 videoStream:(id)arg3 allowCellularAccess:(_Bool)arg4 delegate:(id)arg5;
- (void)startBackgroundTaskRestorationWithDelegate:(id)arg1;
@property(readonly, nonatomic) _Bool restoringBackgroundTasks;
@property(readonly, nonatomic) NSString *currentVideoID;
@property(readonly, nonatomic) double currentProgress;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

