//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MLFairPlayKeyRequest-Protocol.h"

@class NSData, NSString, YTIFairPlayConfig;

@interface MLFairPlayKeyRequest : NSObject <MLFairPlayKeyRequest>
{
    NSString *_hostOverride;
    NSString *_additionalURLParameters;
    int _cryptoPeriodIndex;
    NSData *_encryptedKeyID;
    NSString *_requestIdentificationURI;
    id _request;
    YTIFairPlayConfig *_config;
}

@property(readonly, nonatomic) YTIFairPlayConfig *config; // @synthesize config=_config;
@property(readonly, nonatomic) id request; // @synthesize request=_request;
@property(readonly, nonatomic) NSString *requestIdentificationURI; // @synthesize requestIdentificationURI=_requestIdentificationURI;
@property(readonly, nonatomic) NSData *encryptedKeyID; // @synthesize encryptedKeyID=_encryptedKeyID;
@property(readonly, nonatomic) int cryptoPeriodIndex; // @synthesize cryptoPeriodIndex=_cryptoPeriodIndex;
- (void).cxx_destruct;
- (id)createRequestURL;
- (void)createURLRequestWithKeyData:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)validateKeyRequest;
- (void)parseRequestIdentificationURI;
- (void)createKeyRequestDataWithCompletionBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic, getter=isCancelled) _Bool cancelled;
- (void)createURLRequestWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)initWithRequest:(id)arg1 requestIdentificationURI:(id)arg2 fairPlayConfig:(id)arg3 hostOverride:(id)arg4 additionalURLParameters:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

