//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MLVideoFormatConstraint-Protocol.h"

@class NSString, YTReachabilityController;

@interface MLStickyCeilingFormatConstraint : NSObject <MLVideoFormatConstraint>
{
    YTReachabilityController *_reachability;
    int _maximumCellularResolution;
    int _maximumWiFiResolution;
}

- (void).cxx_destruct;
- (int)maximumResolution;
- (id)filterFormats:(id)arg1;
@property(readonly, nonatomic) _Bool disableTrack;
@property(readonly, nonatomic) long long formatSelectionReason;
- (id)initWithReachability:(id)arg1 maximumCellularResolution:(int)arg2 maximumWiFiResolution:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

