//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FCDRPCService-Protocol.h"

@class FCDRPC;

@protocol PeopleApiDataService <FCDRPCService>
@property(readonly, nonatomic) FCDRPC *listRankedTargetsLiteRPC;
@property(readonly, nonatomic) FCDRPC *batchLookupMergedPeopleLiteRPC;
@property(readonly, nonatomic) FCDRPC *autocompletePeopleLiteRPC;
@end

