//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YTAdsSettingsSectionItemVideoAdPolicy.h"

@interface YTAdsSettingsSectionItemPrerollBreakPolicy : YTAdsSettingsSectionItemVideoAdPolicy
{
}

- (id)initWithItem:(id)arg1 forceAdParameters:(id)arg2 videoAd:(id)arg3;

@end

