//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class YTIElement;

@interface YTDataComponentState : NSObject
{
    YTIElement *_element;
}

@property(retain, nonatomic) YTIElement *element; // @synthesize element=_element;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

