//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIBackgroundClingRenderer, YTIDismissableDialogRenderer, YTIUpsellDialogRenderer;

@interface YTIBackgroundabilityRenderer_BackgroundabilityInfoSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) YTIBackgroundClingRenderer *backgroundClingRenderer; // @dynamic backgroundClingRenderer;
@property(retain, nonatomic) YTIDismissableDialogRenderer *dismissableDialogRenderer; // @dynamic dismissableDialogRenderer;
@property(nonatomic) _Bool hasBackgroundClingRenderer; // @dynamic hasBackgroundClingRenderer;
@property(nonatomic) _Bool hasDismissableDialogRenderer; // @dynamic hasDismissableDialogRenderer;
@property(nonatomic) _Bool hasUpsellDialogRenderer; // @dynamic hasUpsellDialogRenderer;
@property(retain, nonatomic) YTIUpsellDialogRenderer *upsellDialogRenderer; // @dynamic upsellDialogRenderer;

@end

