//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIConnectionShelfRenderer;

@interface YTIConversationSwitcherShelfSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) YTIConnectionShelfRenderer *connectionShelfRenderer; // @dynamic connectionShelfRenderer;
@property(nonatomic) _Bool hasConnectionShelfRenderer; // @dynamic hasConnectionShelfRenderer;

@end

