//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIPlayerCaptionsRenderer, YTIPlayerCaptionsTrackListRenderer;

@interface YTICaptionsSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPlayerCaptionsRenderer; // @dynamic hasPlayerCaptionsRenderer;
@property(nonatomic) _Bool hasPlayerCaptionsTracklistRenderer; // @dynamic hasPlayerCaptionsTracklistRenderer;
@property(retain, nonatomic) YTIPlayerCaptionsRenderer *playerCaptionsRenderer; // @dynamic playerCaptionsRenderer;
@property(retain, nonatomic) YTIPlayerCaptionsTrackListRenderer *playerCaptionsTracklistRenderer; // @dynamic playerCaptionsTracklistRenderer;

@end

