//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTICommentDetailHeaderRenderer;

@interface YTICommentDetailHeaderSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) YTICommentDetailHeaderRenderer *commentDetailHeaderRenderer; // @dynamic commentDetailHeaderRenderer;
@property(nonatomic) _Bool hasCommentDetailHeaderRenderer; // @dynamic hasCommentDetailHeaderRenderer;

@end

