//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface YTICreatorStudioSettingsMask_CreatorAppSettingsMask : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool all; // @dynamic all;
@property(nonatomic) _Bool dismissedGuidedTours; // @dynamic dismissedGuidedTours;
@property(nonatomic) _Bool hasAll; // @dynamic hasAll;
@property(nonatomic) _Bool hasDismissedGuidedTours; // @dynamic hasDismissedGuidedTours;
@property(nonatomic) _Bool hasVideoListPageSize; // @dynamic hasVideoListPageSize;
@property(nonatomic) _Bool hasWarmWelcomeState; // @dynamic hasWarmWelcomeState;
@property(nonatomic) _Bool videoListPageSize; // @dynamic videoListPageSize;
@property(nonatomic) _Bool warmWelcomeState; // @dynamic warmWelcomeState;

@end

