//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIRichListHeaderRenderer, YTITitleAndButtonListHeaderRenderer;

@interface YTIHorizontalCardListHeaderSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasRichListHeaderRenderer; // @dynamic hasRichListHeaderRenderer;
@property(nonatomic) _Bool hasTitleAndButtonListHeaderRenderer; // @dynamic hasTitleAndButtonListHeaderRenderer;
@property(retain, nonatomic) YTIRichListHeaderRenderer *richListHeaderRenderer; // @dynamic richListHeaderRenderer;
@property(retain, nonatomic) YTITitleAndButtonListHeaderRenderer *titleAndButtonListHeaderRenderer; // @dynamic titleAndButtonListHeaderRenderer;

@end

