//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface YTIIosOutOfMemoryEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasResidentMemoryInBytes; // @dynamic hasResidentMemoryInBytes;
@property(nonatomic) _Bool hasWarning; // @dynamic hasWarning;
@property(nonatomic) unsigned long long residentMemoryInBytes; // @dynamic residentMemoryInBytes;
@property(nonatomic) _Bool warning; // @dynamic warning;

@end

