//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface YTIInDisplayAd : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *URL; // @dynamic URL;
@property(copy, nonatomic) NSString *adGroupId; // @dynamic adGroupId;
@property(nonatomic) _Bool hasAdGroupId; // @dynamic hasAdGroupId;
@property(nonatomic) _Bool hasMastheadKeyword; // @dynamic hasMastheadKeyword;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;
@property(copy, nonatomic) NSString *mastheadKeyword; // @dynamic mastheadKeyword;

@end

