//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface YTIKidsAgeGateTracking : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasKidsAgeType; // @dynamic hasKidsAgeType;
@property(nonatomic) int kidsAgeType; // @dynamic kidsAgeType;

@end

