//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIIosLocationConfig;

@interface YTILocationInfoConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool enableLocation; // @dynamic enableLocation;
@property(nonatomic) _Bool hasEnableLocation; // @dynamic hasEnableLocation;
@property(nonatomic) _Bool hasIosLocationConfig; // @dynamic hasIosLocationConfig;
@property(retain, nonatomic) YTIIosLocationConfig *iosLocationConfig; // @dynamic iosLocationConfig;

@end

