//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface YTILivePlaybackContext : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasManifestDuration; // @dynamic hasManifestDuration;
@property(nonatomic) _Bool hasStartWalltime; // @dynamic hasStartWalltime;
@property(nonatomic) unsigned long long manifestDuration; // @dynamic manifestDuration;
@property(nonatomic) unsigned long long startWalltime; // @dynamic startWalltime;

@end

