//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface YTIMdxRouteCount : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasRouteCount; // @dynamic hasRouteCount;
@property(nonatomic) _Bool hasRouteType; // @dynamic hasRouteType;
@property(nonatomic) int routeCount; // @dynamic routeCount;
@property(nonatomic) int routeType; // @dynamic routeType;

@end

