//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface YTIOfflinePlaylistSyncCheck : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool autoSync; // @dynamic autoSync;
@property(nonatomic) _Bool hasAutoSync; // @dynamic hasAutoSync;
@property(nonatomic) _Bool hasOfflineLastModifiedTimestamp; // @dynamic hasOfflineLastModifiedTimestamp;
@property(nonatomic) _Bool hasPlaylistId; // @dynamic hasPlaylistId;
@property(nonatomic) long long offlineLastModifiedTimestamp; // @dynamic offlineLastModifiedTimestamp;
@property(copy, nonatomic) NSString *playlistId; // @dynamic playlistId;
@property(retain, nonatomic) NSMutableArray *videoIdsArray; // @dynamic videoIdsArray;
@property(readonly, nonatomic) unsigned long long videoIdsArray_Count; // @dynamic videoIdsArray_Count;

@end

