//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIPivotBarItemRenderer;

@interface YTIPivotBarSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPivotBarItemRenderer; // @dynamic hasPivotBarItemRenderer;
@property(retain, nonatomic) YTIPivotBarItemRenderer *pivotBarItemRenderer; // @dynamic pivotBarItemRenderer;

@end

