//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTISubscriptionNotificationToggleStateSupportedRenderers;

@interface YTISubscriptionNotificationToggleState : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasNextStateId; // @dynamic hasNextStateId;
@property(nonatomic) _Bool hasState; // @dynamic hasState;
@property(nonatomic) _Bool hasStateId; // @dynamic hasStateId;
@property(nonatomic) int nextStateId; // @dynamic nextStateId;
@property(retain, nonatomic) YTISubscriptionNotificationToggleStateSupportedRenderers *state; // @dynamic state;
@property(nonatomic) int stateId; // @dynamic stateId;

@end

