//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface YTIStoreMapping : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *entriesArray; // @dynamic entriesArray;
@property(readonly, nonatomic) unsigned long long entriesArray_Count; // @dynamic entriesArray_Count;

@end

