//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class YTIUnpluggedBillingDetailsLineItemRenderer, YTIUnpluggedBillingDetailsMethodRenderer;

@interface YTIUnpluggedBillingDetailsSupportedRenderers : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasUnpluggedBillingDetailsLineItemRenderer; // @dynamic hasUnpluggedBillingDetailsLineItemRenderer;
@property(nonatomic) _Bool hasUnpluggedBillingDetailsMethodRenderer; // @dynamic hasUnpluggedBillingDetailsMethodRenderer;
@property(retain, nonatomic) YTIUnpluggedBillingDetailsLineItemRenderer *unpluggedBillingDetailsLineItemRenderer; // @dynamic unpluggedBillingDetailsLineItemRenderer;
@property(retain, nonatomic) YTIUnpluggedBillingDetailsMethodRenderer *unpluggedBillingDetailsMethodRenderer; // @dynamic unpluggedBillingDetailsMethodRenderer;

@end

