//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YTHotConfigObserver-Protocol.h"

@class GIMMe, NSString, YTAutoplayPrefetchController, YTHotConfig;
@protocol MDXServices;

@interface YTMAutoplayPrefetchController : NSObject <YTHotConfigObserver>
{
    YTAutoplayPrefetchController *_prefetchController;
    YTHotConfig *_hotConfig;
    id <MDXServices> _MDXServices;
    GIMMe *_gimme;
}

+ (id)prebufferConfigFromHotConfig:(id)arg1;
@property(nonatomic) __weak GIMMe *gimme; // @synthesize gimme=_gimme;
- (void).cxx_destruct;
- (_Bool)isMDXActive;
- (void)updateHotConfigValues;
- (void)hotConfigDidChange:(id)arg1;
- (void)currentContentVideoMediaTimeDidChangeToTime:(double)arg1 totalMediaTime:(double)arg2;
- (void)setAutoplayTransition:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

