//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YTMInkCollectionReusableView.h"

#import "YTThumbnailMapping-Protocol.h"

@class CAGradientLayer, MDCInkTouchController, NSMutableArray, NSString, QTMButton, UILabel, UITapGestureRecognizer, UIView, YTIButtonRenderer, YTIMusicCarouselShelfBasicHeaderRenderer, YTMMusicThumbnailView;
@protocol YTMCarouselShelfHeaderViewDelegate;

@interface YTMCarouselShelfHeaderView : YTMInkCollectionReusableView <YTThumbnailMapping>
{
    UILabel *_titleLabel;
    UILabel *_straplineLabel;
    YTMMusicThumbnailView *_thumbnailView;
    UIView *_headerContainer;
    struct UIEdgeInsets _headerInsets;
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSMutableArray *_iconButtonsArray;
    NSMutableArray *_iconLinkRenderersArray;
    CAGradientLayer *_scrim;
    MDCInkTouchController *_inkTouchController;
    QTMButton *_moreContentButton;
    YTIButtonRenderer *_moreContentButtonRenderer;
    YTIMusicCarouselShelfBasicHeaderRenderer *_basicHeaderRenderer;
    id <YTMCarouselShelfHeaderViewDelegate> _delegate;
}

@property(nonatomic) __weak id <YTMCarouselShelfHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) YTIMusicCarouselShelfBasicHeaderRenderer *basicHeaderRenderer; // @synthesize basicHeaderRenderer=_basicHeaderRenderer;
- (void).cxx_destruct;
- (_Bool)hasThumbnail;
- (void)setHeaderInsets:(struct UIEdgeInsets)arg1;
- (void)headerTapped;
- (void)iconButtonTapped:(id)arg1;
- (void)didTapMoreContentButton;
- (void)setUpMoreContentButton:(id)arg1;
- (void)removeAllIconButtons;
- (id)thumbnailMappings;
- (void)setBackgroundColor:(id)arg1;
- (void)prepareForReuse;
- (void)setBackgroundOverlay:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

