//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class QTMButton, YTMVideoMetadataCell;

@protocol YTMVideoMetadataCellDelegate <NSObject>
- (void)videoMetadataCell:(YTMVideoMetadataCell *)arg1 didTapExpandButton:(QTMButton *)arg2;
@end

