//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableDictionary, NSString, UIColor, UIImageView, UIView, YTLabeledImageView;

@interface YTTabButton : UIControl
{
    NSString *_annotation;
    NSMutableDictionary *_stateToColorMap;
    NSMutableDictionary *_stateToImageMap;
    NSMutableDictionary *_stateToBackgroundImageMap;
    YTLabeledImageView *_labeledImageView;
    UIView *_statusIndicatorView;
    UIImageView *_backgroundImageView;
    _Bool _statusIndicatorVisible;
    _Bool _truncatesAnnotationAndAdjustsFontSizeToFitWidth;
    NSString *_title;
    UIColor *_statusIndicatorColor;
}

@property(nonatomic) _Bool truncatesAnnotationAndAdjustsFontSizeToFitWidth; // @synthesize truncatesAnnotationAndAdjustsFontSizeToFitWidth=_truncatesAnnotationAndAdjustsFontSizeToFitWidth;
@property(nonatomic) _Bool statusIndicatorVisible; // @synthesize statusIndicatorVisible=_statusIndicatorVisible;
@property(copy, nonatomic) UIColor *statusIndicatorColor; // @synthesize statusIndicatorColor=_statusIndicatorColor;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)titleStringForState:(unsigned long long)arg1 appendAnnotation:(_Bool)arg2;
- (id)backgroundImageForState:(unsigned long long)arg1;
- (id)imageForState:(unsigned long long)arg1;
- (id)titleColorForState:(unsigned long long)arg1;
- (double)getVerticalPositionForHeight:(double)arg1;
- (double)getHorizontalPositionForWidth:(double)arg1;
- (void)updateStatusIndicatorView;
- (void)updateBackgroundImageView;
- (void)updateLabeledImageView;
- (void)updateViewsForCurrentState;
- (unsigned long long)accessibilityTraits;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)setTitleTypeKind:(long long)arg1 typeVariant:(long long)arg2;
- (void)setBackgroundImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (void)setTitle:(id)arg1 annotation:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

