//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC14WrappedFeature5Story.h"

@interface _TtC14WrappedFeature20DecadeTopArtistStory : _TtC14WrappedFeature5Story
{
    // Error parsing type: , name: introMessage
    // Error parsing type: , name: artistName
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: imageURL
}

@end

