//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC14WrappedFeature9ShareView : UIView
{
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: shareTitle
    // Error parsing type: , name: previewImageView
    // Error parsing type: , name: tableViewContainerView
    // Error parsing type: , name: tableView
    // Error parsing type: , name: tableViewHeightConstraint
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

