//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC26PlaylistWithStoriesFeature11TooltipView : UIView
{
    // Error parsing type: , name: style
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: arrow
    // Error parsing type: , name: imageView
    // Error parsing type: , name: label
    // Error parsing type: , name: isPresentingTooltip
    // Error parsing type: , name: actionOnAnimationEnd
    // Error parsing type: , name: isAnimating
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

