//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTAgeVerificationService-Protocol.h"

@interface _TtC22AgeVerificationFeature22AgeVerificationService : NSObject <SPTAgeVerificationService>
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: glueService
    // Error parsing type: , name: networkService
    // Error parsing type: , name: slateService
    // Error parsing type: , name: stateMachine
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

