//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC20SwiftAllSongsFeature20SwiftAllSongsService.h"

@interface _TtC20SwiftAllSongsFeature20SwiftAllSongsService (SwiftAllSongsFeature)
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
@end

