//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC22FullscreenStoryFeature26BackgroundStateEventSource : NSObject
{
    // Error parsing type: , name: queue
    // Error parsing type: , name: lock
    // Error parsing type: , name: consumer
}

- (void).cxx_destruct;
- (id)init;

@end

