//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "EXP_HUBIconImageResolver-Protocol.h"
#import "HUBIconImageResolver-Protocol.h"

@interface HUGSIconImageResolver : NSObject <HUBIconImageResolver, EXP_HUBIconImageResolver>
{
}

- (id)imageForPlaceholderIconWithIdentifier:(id)arg1 size:(struct CGSize)arg2 color:(id)arg3;
- (id)imageForComponentIconWithIdentifier:(id)arg1 size:(struct CGSize)arg2 color:(id)arg3;

@end

