//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTCanvasModelLoaderDelegate.h"
#import "SPTCanvasStreamingPlaybackManagerLoadDelegate.h"
#import "SPTNowPlayingContainerIdleMonitorObserver.h"

@class NSString, SPTCanvasAttributionView, SPTCanvasImageResolver, SPTCanvasLoadEventLogger, SPTCanvasLoadStateTracker, SPTCanvasLoggingService, SPTCanvasModelLoader, SPTCanvasStreamingPlaybackManager, SPTCanvasTrackCheckerImplementation, UIActivityIndicatorView, UIImageView, UIView;

@interface SPTCanvasViewController : UIViewController <SPTCanvasStreamingPlaybackManagerLoadDelegate, SPTCanvasModelLoaderDelegate, SPTNowPlayingContainerIdleMonitorObserver>
{
    _Bool _canvasContentAvailable;
    _Bool _shouldShowAttribution;
    _Bool _isIdle;
    SPTCanvasTrackCheckerImplementation *_trackChecker;
    SPTCanvasImageResolver *_imageResolver;
    SPTCanvasModelLoader *_canvasModelLoader;
    SPTCanvasLoggingService *_loggingService;
    SPTCanvasLoadEventLogger *_loadEventLogger;
    SPTCanvasLoadStateTracker *_loadStateTracker;
    id <SPTCanvasLoadStateUpdater> _canvasLoadStateUpdater;
    id <SPTCanvasModel> _canvasModel;
    id <SPTVideoPlayer> _videoPlayer;
    SPTCanvasStreamingPlaybackManager *_videoPlaybackManager;
    UIImageView *_imageView;
    SPTCanvasAttributionView *_attributionView;
    UIActivityIndicatorView *_activityIndicatorView;
    id <SPTCanvasIdleMonitorObserverDelegate> _idleMonitorDelegate;
}

@property(nonatomic) __weak id <SPTCanvasIdleMonitorObserverDelegate> idleMonitorDelegate; // @synthesize idleMonitorDelegate=_idleMonitorDelegate;
@property(nonatomic) _Bool isIdle; // @synthesize isIdle=_isIdle;
@property(nonatomic) _Bool shouldShowAttribution; // @synthesize shouldShowAttribution=_shouldShowAttribution;
@property(readonly, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(readonly, nonatomic) SPTCanvasAttributionView *attributionView; // @synthesize attributionView=_attributionView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) SPTCanvasStreamingPlaybackManager *videoPlaybackManager; // @synthesize videoPlaybackManager=_videoPlaybackManager;
@property(readonly, nonatomic) id <SPTVideoPlayer> videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) id <SPTCanvasModel> canvasModel; // @synthesize canvasModel=_canvasModel;
@property(retain, nonatomic) id <SPTCanvasLoadStateUpdater> canvasLoadStateUpdater; // @synthesize canvasLoadStateUpdater=_canvasLoadStateUpdater;
@property(readonly, nonatomic) SPTCanvasLoadStateTracker *loadStateTracker; // @synthesize loadStateTracker=_loadStateTracker;
@property(readonly, nonatomic) SPTCanvasLoadEventLogger *loadEventLogger; // @synthesize loadEventLogger=_loadEventLogger;
@property(readonly, nonatomic) SPTCanvasLoggingService *loggingService; // @synthesize loggingService=_loggingService;
@property(retain, nonatomic) SPTCanvasModelLoader *canvasModelLoader; // @synthesize canvasModelLoader=_canvasModelLoader;
@property(readonly, nonatomic) SPTCanvasImageResolver *imageResolver; // @synthesize imageResolver=_imageResolver;
@property(readonly, nonatomic) SPTCanvasTrackCheckerImplementation *trackChecker; // @synthesize trackChecker=_trackChecker;
@property(nonatomic, getter=isCanvasContentAvailable) _Bool canvasContentAvailable; // @synthesize canvasContentAvailable=_canvasContentAvailable;
- (void).cxx_destruct;
- (void)streamingPlaybackManager:(id)arg1 didFailToLoadAssetURL:(id)arg2 entityURI:(id)arg3 playbackOption:(long long)arg4;
- (void)streamingPlaybackManager:(id)arg1 didLoadAssetURL:(id)arg2 entityURI:(id)arg3 playbackOption:(long long)arg4;
- (void)streamingPlaybackManager:(id)arg1 willLoadAssetURL:(id)arg2 entityURI:(id)arg3 playbackOption:(long long)arg4;
- (void)streamingPlaybackManager:(id)arg1 streamingStartedManifestID:(id)arg2 entityURI:(id)arg3 playbackOption:(long long)arg4;
- (void)streamingDidStartForManifestId:(id)arg1 entityURI:(id)arg2 playbackOption:(long long)arg3;
- (void)assetDownloadDidFailForAssetURL:(id)arg1 entityURI:(id)arg2 playbackOption:(long long)arg3;
- (void)assetDownloadDidFinishForAssetURL:(id)arg1 entityURI:(id)arg2 playbackOption:(long long)arg3;
- (void)assetDownloadDidStartForAssetURL:(id)arg1 entityURI:(id)arg2 playbackOption:(long long)arg3;
- (_Bool)canvasModelHasSameManifestId:(id)arg1 entityURI:(id)arg2 playbackOption:(long long)arg3;
- (_Bool)canvasModelHasSameAssetURL:(id)arg1 entityURI:(id)arg2 playbackOption:(long long)arg3;
- (void)hideLoadingIndicator;
- (void)showLoadingIndicator;
- (void)updateAttributionView;
- (void)idlePeriodDidEnd;
- (void)idlePeriodDidBegin;
- (_Bool)shouldRepeatVideo:(id)arg1;
- (long long)playbackOption:(id)arg1;
@property(readonly, nonatomic) UIView *videoView;
- (void)setupStreamingPlaybackWithVideoManager:(id)arg1 playerFeature:(id)arg2;
- (void)didFailToLoadFallbackContentWithModel:(id)arg1 error:(id)arg2;
- (void)didLoadFallbackContentWithModel:(id)arg1 image:(id)arg2;
- (void)didFailToLoadImageContentWithModel:(id)arg1 error:(id)arg2;
- (void)didLoadImageContentWithModel:(id)arg1 image:(id)arg2;
- (void)willLoadImageContentWithModel:(id)arg1;
- (void)didLoadArtistAvatarWithModel:(id)arg1 artistAvatarImage:(id)arg2;
- (void)loadVideoContentWithModel:(id)arg1;
- (void)resetWithTrack:(id)arg1 imageURL:(id)arg2;
- (void)setVisible:(_Bool)arg1;
- (void)pausePlayback;
- (void)resumePlayback;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)setupConstraints;
- (void)viewDidLoad;
- (id)initWithCanvasTrackChecker:(id)arg1 loadStateTracker:(id)arg2 imageResolver:(id)arg3 videoManager:(id)arg4 loggingService:(id)arg5 loadEventLogger:(id)arg6 idleMonitorDelegate:(id)arg7 videoPlayer:(id)arg8 playerFeature:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

