//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SPTPlayerTrack, UIViewController;
@protocol SPTCanvasModel;

@protocol SPTCanvasViewControllerFactory <NSObject>
- (UIViewController *)createCanvasLowResViewControllerForTrack:(SPTPlayerTrack *)arg1 withCanvasModel:(id <SPTCanvasModel>)arg2;
- (UIViewController *)createCanvasViewControllerForTrack:(SPTPlayerTrack *)arg1 withCanvasModel:(id <SPTCanvasModel>)arg2;
@end

