//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTVideoEventObserverFactory-Protocol.h"

@class NSString;
@protocol SPTVideoLogger, SPTVideoLoggerDataProvider;

@interface SPTEndVideoLoggerFactory : NSObject <SPTVideoEventObserverFactory>
{
    id <SPTVideoLogger> _logger;
    id <SPTVideoLoggerDataProvider> _videoLoggerDataProvider;
}

@property(retain, nonatomic) id <SPTVideoLoggerDataProvider> videoLoggerDataProvider; // @synthesize videoLoggerDataProvider=_videoLoggerDataProvider;
@property(retain, nonatomic) id <SPTVideoLogger> logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (id)createPlaybackEventObserverForPlaybackIdentity:(id)arg1 options:(id)arg2 timeObservable:(id)arg3;
- (id)initWithLogger:(id)arg1 videoLoggerDataProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

