//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFreeTierPlaylistCellProviderFactory-Protocol.h"

@class NSString, SPTFreeTierPlaylistEncoreAudioCellProvider;

@interface SPTFreeTierPlaylistEncoreAudioCellProviderFactory : NSObject <SPTFreeTierPlaylistCellProviderFactory>
{
    SPTFreeTierPlaylistEncoreAudioCellProvider *_cellProvider;
}

@property(retain, nonatomic) SPTFreeTierPlaylistEncoreAudioCellProvider *cellProvider; // @synthesize cellProvider=_cellProvider;
- (void).cxx_destruct;
- (id)reuseIdentifiers;
- (id)cellProviderForRowAtIndexPath:(id)arg1;
- (id)initWithComponentFactory:(id)arg1 itemsViewModel:(id)arg2 shelves:(id)arg3 playlistViewModel:(id)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

