//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTService-Protocol.h"

@protocol SPTFeatureFlagFactory, SPTService;

@protocol SPTFeatureFlaggingService <SPTService>
- (id <SPTFeatureFlagFactory>)provideFeatureFlagFactoryForService:(id <SPTService>)arg1;
@end

