//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingsSection.h"

@class SPTSettingsButtonTableViewCell;

@interface SPTGaiaDeviceMenuSettingsSection : SettingsSection
{
    SPTSettingsButtonTableViewCell *_buttonCell;
    id <SPTGaiaManager> _gaiaManager;
}

@property(retain, nonatomic) id <SPTGaiaManager> gaiaManager; // @synthesize gaiaManager=_gaiaManager;
@property(retain, nonatomic) SPTSettingsButtonTableViewCell *buttonCell; // @synthesize buttonCell=_buttonCell;
- (void).cxx_destruct;
- (void)didSelectRow:(long long)arg1;
- (id)cellForRow:(long long)arg1;
- (long long)numberOfRows;
- (void)setupButtonCell;
- (id)initWithSettingsViewController:(id)arg1 gaiaManager:(id)arg2;

@end

