//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SPTGaiaDevicesAvailableView.h"
#import "SPTGaiaManagerObserver.h"
#import "SPTThemableView.h"

@class NSAttributedString, NSNotificationCenter, NSString, SPTGaiaDevicePickerAppearanceManager, SPTGaiaDevicesAvailableViewTextFactory, SPTTheme, UIColor, UILabel;

@interface SPTGaiaDevicesAvailableViewImplementation : UIView <SPTThemableView, SPTGaiaManagerObserver, SPTGaiaDevicesAvailableView>
{
    _Bool _hidesTextWhenDisconnected;
    long long _textAlignment;
    double _iconFontSize;
    double _devicesFontSize;
    id <SPTGaiaDevicesAvailableViewDelegate> _delegate;
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    id <SPTGaiaManager> _gaiaManager;
    SPTTheme *_theme;
    SPTGaiaDevicesAvailableViewTextFactory *_textFactory;
    SPTGaiaDevicePickerAppearanceManager *_appearanceManager;
    NSNotificationCenter *_notificationCenter;
    UILabel *_devicesLabel;
    NSAttributedString *_chromecastAttributedString;
}

@property(readonly, nonatomic) NSAttributedString *chromecastAttributedString; // @synthesize chromecastAttributedString=_chromecastAttributedString;
@property(retain, nonatomic) UILabel *devicesLabel; // @synthesize devicesLabel=_devicesLabel;
@property(retain, nonatomic) NSNotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
@property(retain, nonatomic) SPTGaiaDevicePickerAppearanceManager *appearanceManager; // @synthesize appearanceManager=_appearanceManager;
@property(retain, nonatomic) SPTGaiaDevicesAvailableViewTextFactory *textFactory; // @synthesize textFactory=_textFactory;
@property(retain, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) id <SPTGaiaManager> gaiaManager; // @synthesize gaiaManager=_gaiaManager;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(nonatomic) _Bool hidesTextWhenDisconnected; // @synthesize hidesTextWhenDisconnected=_hidesTextWhenDisconnected;
@property(nonatomic) __weak id <SPTGaiaDevicesAvailableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double devicesFontSize; // @synthesize devicesFontSize=_devicesFontSize;
@property(nonatomic) double iconFontSize; // @synthesize iconFontSize=_iconFontSize;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIColor *activeFontColor;
@property(readonly, nonatomic) UIColor *inactiveFontColor;
- (void)dealloc;
- (void)applyThemeLayout;
- (void)layoutSubviews;
@property(readonly, nonatomic) NSAttributedString *spaceAttributedString;
- (id)devicesAttributedStringWithHiddenText:(_Bool)arg1;
@property(readonly, nonatomic) NSAttributedString *devicesAttributedString;
- (void)updateLabels;
- (void)updateConnectionChangedUIWithGaiaManager:(id)arg1;
- (void)updateDeviceAvailableUIWithGaiaManager:(id)arg1;
- (void)gaiaManagerDidChangeConnectionTypesAvailable:(id)arg1;
- (void)gaiaManagerDidChangeAvailable:(id)arg1;
- (void)gaiaManagerDidChangeRemoteConnectionState:(id)arg1;
- (void)gaiaManagerDidChangeActiveDeviceName:(id)arg1;
- (void)tearDown;
- (void)addThemeLayoutObserver;
- (void)setupLayout;
- (void)setupGaiaManager;
- (void)setupLabels;
- (id)initWithFrame:(struct CGRect)arg1 gaiaManager:(id)arg2 textFactory:(id)arg3 theme:(id)arg4 appearanceManager:(id)arg5 notificationCenter:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

