//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTHeartsRecommendationStyle.h"

@class GLUEImageStyle, GLUELabelStyle, NSString, UIColor;

@interface SPTHeartsRecommendationStyleImplementation : NSObject <SPTHeartsRecommendationStyle>
{
    double _badgeAnimationDuration;
    double _badgeAnimationScale;
    double _badgeAnimationSpringDamping;
    double _badgeAnimationSpringVelocity;
    UIColor *_badgeBackgroundColor;
    double _badgeCircleWidth;
    double _badgeImageInset;
    UIColor *_badgeTintColor;
    GLUEImageStyle *_badgeViewStyle;
    double _contentSpacing;
    double _imageSelectionAlpha;
    GLUEImageStyle *_imageViewStyle;
    GLUELabelStyle *_textLabelStyle;
    UIColor *_textLabelColor;
    double _topMargin;
}

@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(copy, nonatomic) UIColor *textLabelColor; // @synthesize textLabelColor=_textLabelColor;
@property(copy, nonatomic) GLUELabelStyle *textLabelStyle; // @synthesize textLabelStyle=_textLabelStyle;
@property(copy, nonatomic) GLUEImageStyle *imageViewStyle; // @synthesize imageViewStyle=_imageViewStyle;
@property(nonatomic) double imageSelectionAlpha; // @synthesize imageSelectionAlpha=_imageSelectionAlpha;
@property(nonatomic) double contentSpacing; // @synthesize contentSpacing=_contentSpacing;
@property(copy, nonatomic) GLUEImageStyle *badgeViewStyle; // @synthesize badgeViewStyle=_badgeViewStyle;
@property(copy, nonatomic) UIColor *badgeTintColor; // @synthesize badgeTintColor=_badgeTintColor;
@property(nonatomic) double badgeImageInset; // @synthesize badgeImageInset=_badgeImageInset;
@property(nonatomic) double badgeCircleWidth; // @synthesize badgeCircleWidth=_badgeCircleWidth;
@property(copy, nonatomic) UIColor *badgeBackgroundColor; // @synthesize badgeBackgroundColor=_badgeBackgroundColor;
@property(nonatomic) double badgeAnimationSpringVelocity; // @synthesize badgeAnimationSpringVelocity=_badgeAnimationSpringVelocity;
@property(nonatomic) double badgeAnimationSpringDamping; // @synthesize badgeAnimationSpringDamping=_badgeAnimationSpringDamping;
@property(nonatomic) double badgeAnimationScale; // @synthesize badgeAnimationScale=_badgeAnimationScale;
@property(nonatomic) double badgeAnimationDuration; // @synthesize badgeAnimationDuration=_badgeAnimationDuration;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

