//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL;
@protocol SPTInteractionEvent;

@protocol SPTInteractionEventFactory <NSObject>
- (id <SPTInteractionEvent>)shuffleDisable;
- (id <SPTInteractionEvent>)skipToPreviousWithItemToBeSkipped:(NSURL *)arg1;
- (id <SPTInteractionEvent>)unfollowWithItemToBeUnfollowed:(NSURL *)arg1;
- (id <SPTInteractionEvent>)addToPlaylistWithPlaylist:(NSURL *)arg1 withItemToBeAdded:(NSURL *)arg2;
- (id <SPTInteractionEvent>)uiHide;
- (id <SPTInteractionEvent>)uiElementToggle;
- (id <SPTInteractionEvent>)skipToNextWithItemToBeSkipped:(NSURL *)arg1;
- (id <SPTInteractionEvent>)uiReveal;
- (id <SPTInteractionEvent>)unlikeWithItemToBeUnliked:(NSURL *)arg1;
- (id <SPTInteractionEvent>)shufflePlayWithContextToBePlayed:(NSURL *)arg1;
- (id <SPTInteractionEvent>)repeatEnable;
- (id <SPTInteractionEvent>)seekToTimeWithMsToSeekTo:(long long)arg1;
- (id <SPTInteractionEvent>)repeatOneEnable;
- (id <SPTInteractionEvent>)pauseWithItemToBePaused:(NSURL *)arg1;
- (id <SPTInteractionEvent>)followWithItemToBeFollowed:(NSURL *)arg1;
- (id <SPTInteractionEvent>)repeatDisable;
- (id <SPTInteractionEvent>)uiNavigateWithDestination:(NSURL *)arg1;
- (id <SPTInteractionEvent>)likeWithItemToBeLiked:(NSURL *)arg1;
- (id <SPTInteractionEvent>)shuffleEnable;
- (id <SPTInteractionEvent>)resumeWithItemToBeResumed:(NSURL *)arg1;
- (id <SPTInteractionEvent>)playWithItemToBePlayed:(NSURL *)arg1;
@end

