//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTLoginRecoverAccountHelpPopupLoggerProtocol-Protocol.h"

@class NSString;
@protocol SPTLoginLogger;

@interface SPTLoginMagicLinkHelpPopupLogger : NSObject <SPTLoginRecoverAccountHelpPopupLoggerProtocol>
{
    id <SPTLoginLogger> _logger;
}

@property(retain, nonatomic) id <SPTLoginLogger> logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (void)logUserDidTapGetHelpButton;
- (void)logUserDidTapTryAgainButton;
- (void)logUserDidSeePopupDialog;
- (id)initWithLogger:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

