//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTPreSignupExperimentationFeatureFlagsLoader;

@interface SPTLoginMagicLinkTestManager : NSObject
{
    id <SPTPreSignupExperimentationFeatureFlagsLoader> _featureFlagsLoader;
}

@property(readonly, nonatomic) id <SPTPreSignupExperimentationFeatureFlagsLoader> featureFlagsLoader; // @synthesize featureFlagsLoader=_featureFlagsLoader;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isMagicLinkExperimentEnabled) _Bool magicLinkExperimentEnabled;
@property(readonly, nonatomic, getter=isMagicLinkOnKeyboardCellTreeEnabled) _Bool magicLinkOnKeyboardCellThreeEnabled;
@property(readonly, nonatomic, getter=isMagicLinkOnKeyboardCellTwoEnabled) _Bool magicLinkOnKeyboardCellTwoEnabled;
@property(readonly, nonatomic, getter=isMagicLinkOnKeyboardCellOneEnabled) _Bool magicLinkOnKeyboardCellOneEnabled;
@property(readonly, nonatomic, getter=isMagicLinkOnLoginScreenEnabled) _Bool magicLinkOnLoginScreenEnabled;
@property(readonly, nonatomic, getter=isMagicLinkOnKeyboardEnabled) _Bool magicLinkOnKeyboardEnabled;
- (id)initWithFeatureFlagsLoader:(id)arg1;

@end

