//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTNowPlayingScrollService-Protocol.h"

@protocol SPTNowPlayingScrollTestManager_Internal;

@protocol SPTNowPlayingScrollService_Internal <SPTNowPlayingScrollService>
- (id <SPTNowPlayingScrollTestManager_Internal>)provideScrollTestManager;
@end

