//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSAttributedString;

@interface SPTPodcastEpisodeDescriptionTextView : UITextView
{
    _Bool _needsTextViewLayout;
    NSAttributedString *_collapsedLink;
    NSAttributedString *_expandedText;
    double _lineHeight;
}

@property(nonatomic) _Bool needsTextViewLayout; // @synthesize needsTextViewLayout=_needsTextViewLayout;
@property(nonatomic) double lineHeight; // @synthesize lineHeight=_lineHeight;
@property(copy, nonatomic) NSAttributedString *expandedText; // @synthesize expandedText=_expandedText;
@property(copy, nonatomic) NSAttributedString *collapsedLink; // @synthesize collapsedLink=_collapsedLink;
- (void).cxx_destruct;
- (void)setAttributedText:(id)arg1;
- (void)setNumberOfLines:(long long)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

