//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SPTPartnerIntegrationCategory : NSObject
{
    NSString *_identifier;
    NSArray *_integrations;
}

@property(readonly, copy, nonatomic) NSArray *integrations; // @synthesize integrations=_integrations;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1 integrations:(id)arg2;

@end

