//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIScrollView;

@protocol SPTPhoneNumberSignupKeyboardShowingView <NSObject>
@property(readonly, nonatomic) UIScrollView *animatingScrollView;
@property(readonly, nonatomic) double bottomViewY;
- (void)updateScrollViewWithInsets:(struct UIEdgeInsets)arg1;
@end

