//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GLUEContextMenuAccessoryButton, NSIndexPath, SPTPlaylistOfflineSyncAccessoryButton, SPTPodcastAccessoryIconButton, SPTPodcastPlayButton;

@protocol SPTPodcastButtonsFactory <NSObject>
- (SPTPlaylistOfflineSyncAccessoryButton *)offlineSyncAccessoryButtonForIndexPath:(NSIndexPath *)arg1 target:(id)arg2;
- (GLUEContextMenuAccessoryButton *)contextMenuButtonForIndexPath:(NSIndexPath *)arg1 target:(id)arg2;
- (SPTPodcastPlayButton *)podcastPlayButtonWithState:(_Bool)arg1 indexPath:(NSIndexPath *)arg2 target:(id)arg3;
- (SPTPodcastAccessoryIconButton *)podcastButtonWithType:(long long)arg1 indexPath:(NSIndexPath *)arg2 target:(id)arg3;
@end

