//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SPTPodcastJSONHelper : NSObject
{
}

+ (id)testJsonDictionary;
+ (id)testJsonDictionaryUnfinished;
+ (id)emptyDictionary;
+ (id)testJsonDataWithObject:(id)arg1;
+ (id)testEmptyJsonData;
+ (id)testJsonDataUnfinished;
+ (id)testJsonData;

@end

