//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTPodcastImportExternalPodcast, SPTPodcastImportPickerItemCell;

@protocol SPTPodcastImportPickerItemCellDelegate <NSObject>
- (void)podcastPickerItemCell:(SPTPodcastImportPickerItemCell *)arg1 didDeselectItem:(SPTPodcastImportExternalPodcast *)arg2;
- (void)podcastPickerItemCell:(SPTPodcastImportPickerItemCell *)arg1 didSelectItem:(SPTPodcastImportExternalPodcast *)arg2;
@end

