//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SPTSearchHubViewController;
@protocol EXP_HUBViewModel;

@protocol SPTSearchHubViewControllerDelegate <NSObject>
- (void)searchViewController:(SPTSearchHubViewController *)arg1 didUpdateFromViewModel:(id <EXP_HUBViewModel>)arg2 toViewModel:(id <EXP_HUBViewModel>)arg3;
@end

