//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SPTSpeakerActivationService-Protocol.h"

@class NSString, SPTAllocationContext, SPTSpeakerActivationLogger, SPTSpeakerActivationPopupManager, SPTSpeakerActivationSuggestionV2PopupManager, SPTSpeakerActivationTestManager;
@protocol GaiaFeature, SPTContainerService, SPTFeatureFlaggingService, SPTGLUEService, SPTNetworkService, SPTSessionService, SPTSettingsFeature, SPTURIDispatchService;

@interface SPTSpeakerActivationServiceImplementation : NSObject <SPTSpeakerActivationService>
{
    id <SPTContainerService> _containerService;
    id <SPTNetworkService> _networkService;
    id <SPTSessionService> _sessionService;
    id <SPTSettingsFeature> _settingsService;
    id <GaiaFeature> _gaiaFeature;
    id <SPTFeatureFlaggingService> _featureFlaggingService;
    id <SPTGLUEService> _glueService;
    id <SPTURIDispatchService> _linkDispatchService;
    SPTSpeakerActivationTestManager *_testManager;
    SPTSpeakerActivationPopupManager *_popupDialogManager;
    SPTSpeakerActivationLogger *_logger;
    SPTSpeakerActivationSuggestionV2PopupManager *_speakerSuggestionV2PopupManager;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) SPTSpeakerActivationSuggestionV2PopupManager *speakerSuggestionV2PopupManager; // @synthesize speakerSuggestionV2PopupManager=_speakerSuggestionV2PopupManager;
@property(retain, nonatomic) SPTSpeakerActivationLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) SPTSpeakerActivationPopupManager *popupDialogManager; // @synthesize popupDialogManager=_popupDialogManager;
@property(retain, nonatomic) SPTSpeakerActivationTestManager *testManager; // @synthesize testManager=_testManager;
@property(nonatomic) __weak id <SPTURIDispatchService> linkDispatchService; // @synthesize linkDispatchService=_linkDispatchService;
@property(nonatomic) __weak id <SPTGLUEService> glueService; // @synthesize glueService=_glueService;
@property(nonatomic) __weak id <SPTFeatureFlaggingService> featureFlaggingService; // @synthesize featureFlaggingService=_featureFlaggingService;
@property(nonatomic) __weak id <GaiaFeature> gaiaFeature; // @synthesize gaiaFeature=_gaiaFeature;
@property(nonatomic) __weak id <SPTSettingsFeature> settingsService; // @synthesize settingsService=_settingsService;
@property(nonatomic) __weak id <SPTSessionService> sessionService; // @synthesize sessionService=_sessionService;
@property(nonatomic) __weak id <SPTNetworkService> networkService; // @synthesize networkService=_networkService;
@property(nonatomic) __weak id <SPTContainerService> containerService; // @synthesize containerService=_containerService;
- (void).cxx_destruct;
- (void)configureSpeakerSuggestionV2PopupManager;
- (void)configureSpeakerActivationPopupManager;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

