//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTSignupTermsAndPolicyManagerDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, SPTLoginTheme, SPTSignupTermsAndPolicyManager, SPTSignupUserInfoModel;

@interface SPTSignupTermsAndPolicyViewModel : NSObject <SPTSignupTermsAndPolicyManagerDelegate, UITextViewDelegate>
{
    id <SPTSignupTermsAndPolicyViewModelDelegate> _delegate;
    SPTSignupTermsAndPolicyManager *_termsAndPolicyManager;
    SPTLoginTheme *_theme;
    SPTSignupUserInfoModel *_userInfoModel;
    id <SPTLinkDispatcher> _linkDispatcher;
    id <SPTAlertController> _alertController;
    id <SPTAdjustUserTrackerProtocol> _adjustTracker;
}

@property(retain, nonatomic) id <SPTAdjustUserTrackerProtocol> adjustTracker; // @synthesize adjustTracker=_adjustTracker;
@property(retain, nonatomic) id <SPTAlertController> alertController; // @synthesize alertController=_alertController;
@property(retain, nonatomic) id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
@property(retain, nonatomic) SPTSignupUserInfoModel *userInfoModel; // @synthesize userInfoModel=_userInfoModel;
@property(retain, nonatomic) SPTLoginTheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) SPTSignupTermsAndPolicyManager *termsAndPolicyManager; // @synthesize termsAndPolicyManager=_termsAndPolicyManager;
@property(nonatomic) __weak id <SPTSignupTermsAndPolicyViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;
- (void)showTermsAndPolicyDialog;
- (void)termsAndPolicyManagerDidAcceptAllLicences:(id)arg1;
- (void)termsAndPolicyManagerDidSelectPrivacyAndPolicyDetails:(id)arg1;
- (void)termsAndPolicyManagerDidSelectTermsAndConditionsDetails:(id)arg1;
- (void)logUserDidTapLinkWith:(id)arg1;
- (void)dismissBrowserView;
- (void)presentTermsDetailsForURL:(id)arg1;
- (_Bool)isTermsAndPolicyDialogRequired;
- (id)linksForTermsAndConditionsText;
- (id)localizedTextForTermsAndConditions;
- (id)termsAndConditionsAttributedText;
- (id)initWithUserInfoModel:(id)arg1 termsAndPolicyManager:(id)arg2 theme:(id)arg3 linkDispatcher:(id)arg4 alertController:(id)arg5 adjustTracker:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

