//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTPodcastPreferencesObserver.h"
#import "SPTWatchPlatformPublisher.h"

@class NSString;

@interface SPTWatchPlatformPlaybackSpeedStatePublisher : NSObject <SPTPodcastPreferencesObserver, SPTWatchPlatformPublisher>
{
    id <SPTWatchConnectivityPubSubMessageQueue> _pubSubMessageQueue;
    id <SPTPodcastSpeedControlManager> _podcastSpeedControlManager;
}

@property(readonly, nonatomic) __weak id <SPTPodcastSpeedControlManager> podcastSpeedControlManager; // @synthesize podcastSpeedControlManager=_podcastSpeedControlManager;
@property(readonly, nonatomic) __weak id <SPTWatchConnectivityPubSubMessageQueue> pubSubMessageQueue; // @synthesize pubSubMessageQueue=_pubSubMessageQueue;
- (void).cxx_destruct;
- (void)podcastPlaybackSpeedDidUpdate:(id)arg1 oldSpeed:(id)arg2;
- (void)handlePublisherEvent:(long long)arg1;
- (void)publishPlaybackSpeedState;
- (id)initWithPubSubMessageQueue:(id)arg1 podcastSpeedControlManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

