//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class NSMutableArray, Protocol;

@interface PHFDelegateChain : NSProxy
{
    NSMutableArray *_objects;
    Protocol *_protocol;
    _Bool _breaking;
}

+ (id)delegateChainWithObjects:(id)arg1;
@property(nonatomic, getter=__isBreaking, setter=__setBreaking:) _Bool breaking; // @synthesize breaking=_breaking;
- (void).cxx_destruct;
- (id)__firstObjectRespondingToSelector:(SEL)arg1;
- (id)__objectsRespondingToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)__setObjects:(id)arg1;
- (id)__objects;
- (id)__initWithObjectsInArray:(id)arg1;

@end

