//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol OS_dispatch_source;

@interface SEUpdateTimer : NSObject
{
    NSObject<OS_dispatch_source> *_timer;
    unsigned long long _leeway;
    _Bool _isValid;
}

+ (id)timerOnQueue:(id)arg1 withLeeway:(unsigned long long)arg2;
- (void).cxx_destruct;
- (void)scheduleBlock:(CDUnknownBlockType)arg1 afterInterval:(double)arg2 repeat:(_Bool)arg3;
- (void)invalidate;
- (void)dealloc;
- (id)initWithDispatchQueue:(id)arg1 leeway:(unsigned long long)arg2;

@end

