//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (Hierarchy)
- (id)gatherSubViews;
- (void)swapDepthsWithView:(id)arg1;
- (_Bool)isAtBack;
- (_Bool)isInFront;
- (void)sendOneLevelDown;
- (void)bringOneLevelUp;
- (void)sendToBack;
- (void)bringToFront;
- (unsigned long long)getSubviewIndex;
@end

