//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface UVTouchEvent : NSObject
{
    _Bool Keyboard;
    int Type;
    long long GroupId;
    long long X;
    long long Y;
    long long Time;
}

@property(nonatomic) _Bool Keyboard; // @synthesize Keyboard;
@property(nonatomic) int Type; // @synthesize Type;
@property(nonatomic) long long Time; // @synthesize Time;
@property(nonatomic) long long Y; // @synthesize Y;
@property(nonatomic) long long X; // @synthesize X;
@property(nonatomic) long long GroupId; // @synthesize GroupId;
- (id)toJson;

@end

