//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "VOXArtworkFetchQueueManagerDelegate-Protocol.h"

@class NSManagedObjectContext, NSMutableOrderedSet, NSString, VOXArtworkFetchQueueManager;
@protocol OS_dispatch_queue;

@interface VOXArtworkFinder : NSObject <VOXArtworkFetchQueueManagerDelegate>
{
    VOXArtworkFetchQueueManager *_queueManager;
    NSMutableOrderedSet *_fetchedObjects;
    NSObject<OS_dispatch_queue> *_queue;
    NSManagedObjectContext *_ctx;
}

+ (id)shared;
@property(retain) NSManagedObjectContext *ctx; // @synthesize ctx=_ctx;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableOrderedSet *fetchedObjects; // @synthesize fetchedObjects=_fetchedObjects;
@property(retain) VOXArtworkFetchQueueManager *queueManager; // @synthesize queueManager=_queueManager;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (void)artworkFetchQueueDidFinish;
- (void)artworkFetchOperationFinished:(id)arg1;
- (id)buildOperationForItem:(id)arg1;
- (_Bool)addToQueue:(id)arg1;
- (id)fetchObjects:(_Bool)arg1;
- (void)updateRequested;
- (_Bool)isIdle;
- (void)findAllMissingArtworksAndSave;
- (void)findAllMissingArtworksAndSaveDeferred;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

