//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, VOXSoundCloudTrackEntity;
@protocol VoxPlayableItemProtocol, _TtP3VOX12Downloadable_;

@protocol VOXActionSheetActionsProtocol <NSObject>

@optional
- (void)actionSheetActionShareMediaItem:(id <VoxPlayableItemProtocol>)arg1;
- (void)actionSheetRemoveDownloadedItem:(id <_TtP3VOX12Downloadable_>)arg1;
- (void)actionSheetDownloadItem:(id <_TtP3VOX12Downloadable_>)arg1;
- (void)actionSheetActionSoundCloudTrackDelete:(VOXSoundCloudTrackEntity *)arg1;
- (void)actionSheetActionSoundCloudTrackUnlike:(VOXSoundCloudTrackEntity *)arg1;
- (void)actionSheetActionViewOnSoundCloudWithMediaItem:(id <VoxPlayableItemProtocol>)arg1;
- (void)actionSheetActionDisMiss;
- (void)actionSheetActionPlayNextMediaItem:(id <VoxPlayableItemProtocol>)arg1;
- (void)actionSheetActionAddMediaItem:(id <VoxPlayableItemProtocol>)arg1 toQueueFromCollection:(NSArray *)arg2;
- (void)actionSheetActionCreateNewCollectionWithMediaItem:(id <VoxPlayableItemProtocol>)arg1;
- (void)actionSheetActionAddMediaItemToCollection:(id <VoxPlayableItemProtocol>)arg1;
@end

