//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDIIndexBar.h"

@interface VOXIndexBar : GDIIndexBar
{
    CDUnknownBlockType _touchBeganHandler;
    CDUnknownBlockType _touchMovedHandler;
    CDUnknownBlockType _touchEndHandler;
}

@property(copy, nonatomic) CDUnknownBlockType touchEndHandler; // @synthesize touchEndHandler=_touchEndHandler;
@property(copy, nonatomic) CDUnknownBlockType touchMovedHandler; // @synthesize touchMovedHandler=_touchMovedHandler;
@property(copy, nonatomic) CDUnknownBlockType touchBeganHandler; // @synthesize touchBeganHandler=_touchBeganHandler;
- (void).cxx_destruct;
- (struct CGRect)rectForIndexBarFrame;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end

