//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVAudioSessionPortDescription;

@protocol VOXPlayerRoutesObserverDelegate <NSObject>
- (void)routesObserverRouteChangedFrom:(AVAudioSessionPortDescription *)arg1 toPort:(AVAudioSessionPortDescription *)arg2;
- (void)routesObserverHeadphonesConnected;
- (void)routesObserverHeadphonesEjected;
@end

