//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VOXSettingsCell.h"

@class UIButton, UILabel;

@interface VOXSettingsInfoCell : VOXSettingsCell
{
    unsigned long long _state;
    UILabel *_itemTitleLabel;
    UIButton *_statusButton;
}

@property(nonatomic) __weak UIButton *statusButton; // @synthesize statusButton=_statusButton;
@property(nonatomic) __weak UILabel *itemTitleLabel; // @synthesize itemTitleLabel=_itemTitleLabel;
- (void).cxx_destruct;
- (void)tappedLabel:(id)arg1;
- (unsigned long long)state;
- (void)setState:(unsigned long long)arg1;
- (void)setSubTitle:(id)arg1;
- (void)setTitle:(id)arg1;

@end

