//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface VOXSoundCloudUserModel : NSObject
{
    NSString *_remoteId;
    NSString *_permalink;
    NSString *_permalinkUrl;
    NSString *_avatarURL;
    NSString *_uri;
    NSString *_userName;
}

@property(readonly, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(readonly, nonatomic) NSString *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(readonly, nonatomic) NSString *permalinkUrl; // @synthesize permalinkUrl=_permalinkUrl;
@property(readonly, nonatomic) NSString *permalink; // @synthesize permalink=_permalink;
@property(readonly, nonatomic) NSString *remoteId; // @synthesize remoteId=_remoteId;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

