//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VXBassAudioDevice.h"

@interface VXBassAudioDeviceIOS : VXBassAudioDevice
{
}

- (_Bool)supportsSampleRateSwitching;
- (_Bool)portTypeIsBuiltIn:(id)arg1;
- (_Bool)isBuiltIn;
- (_Bool)isSystemDefault;
- (long long)sampleRate;
- (long long)channelCount;
- (id)deviceName;
- (id)deviceUID;
- (long long)bassDeviceIndex;

@end

