//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CDPlayable.h"

@class CDWaveform, NSNumber, NSOrderedSet, NSSet, NSString;

@interface _CDTrack : CDPlayable
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *blocked; // @dynamic blocked;
@property(retain, nonatomic) NSNumber *commentsCount; // @dynamic commentsCount;
@property(retain, nonatomic) NSNumber *displayStats; // @dynamic displayStats;
@property(retain, nonatomic) NSNumber *fullDurationInMs; // @dynamic fullDurationInMs;
@property(retain, nonatomic) NSNumber *monetizable; // @dynamic monetizable;
@property(copy, nonatomic) NSString *monetizationModel; // @dynamic monetizationModel;
@property(retain, nonatomic) NSNumber *playbackCount; // @dynamic playbackCount;
@property(retain, nonatomic) NSSet *playlistTracks; // @dynamic playlistTracks;
@property(copy, nonatomic) NSString *policy; // @dynamic policy;
@property(retain, nonatomic) NSSet *queueTracks; // @dynamic queueTracks;
@property(retain, nonatomic) NSSet *recentTracks; // @dynamic recentTracks;
@property(retain, nonatomic) NSNumber *snipDurationInMs; // @dynamic snipDurationInMs;
@property(retain, nonatomic) NSNumber *snipped; // @dynamic snipped;
@property(retain, nonatomic) NSSet *stationTracks; // @dynamic stationTracks;
@property(retain, nonatomic) id stationUrns; // @dynamic stationUrns;
@property(copy, nonatomic) NSString *streamUrl; // @dynamic streamUrl;
@property(retain, nonatomic) NSNumber *subHighTier; // @dynamic subHighTier;
@property(retain, nonatomic) NSNumber *subMidTier; // @dynamic subMidTier;
@property(retain, nonatomic) NSNumber *syncable; // @dynamic syncable;
@property(retain, nonatomic) NSOrderedSet *transcodings; // @dynamic transcodings;
@property(retain, nonatomic) NSSet *userLikedTracks; // @dynamic userLikedTracks;
@property(retain, nonatomic) NSSet *userPostedTracks; // @dynamic userPostedTracks;
@property(retain, nonatomic) CDWaveform *waveform; // @dynamic waveform;
@property(copy, nonatomic) NSString *waveformPointsUrl; // @dynamic waveformPointsUrl;
@end

