//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIView;

@interface _TtC9Discovery28SingleSelectionCardCellLarge : UITableViewCell
{
    // Error parsing type: , name: titleContainerView
    // Error parsing type: , name: artworkViewContainerView
    // Error parsing type: , name: socialProofViewContainerView
    // Error parsing type: , name: cellMarginBottom
    // Error parsing type: , name: cardTitleView
    // Error parsing type: , name: cardArtworkView
    // Error parsing type: , name: cardSocialProofView
    // Error parsing type: , name: parallaxEffect.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (void)awakeFromNib;
@property(nonatomic, retain) UIView *cellMarginBottom; // @synthesize cellMarginBottom;
@property(nonatomic, retain) UIView *socialProofViewContainerView; // @synthesize socialProofViewContainerView;
@property(nonatomic, retain) UIView *artworkViewContainerView; // @synthesize artworkViewContainerView;
@property(nonatomic, retain) UIView *titleContainerView; // @synthesize titleContainerView;

@end

