//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10SoundCloud14AudioAdAdapter : NSObject
{
    // Error parsing type: , name: requestEndpoint
    // Error parsing type: , name: mobileApiAdAdapter
    // Error parsing type: , name: monetizableTrack
    // Error parsing type: , name: streamURLFormatter
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)adaptWithAd:(id)arg1;
- (id)initWithRequestEndpoint:(id)arg1 mobileApiAdAdapter:(id)arg2 monetizableTrack:(id)arg3 streamURLFormatter:(id)arg4;
- (id)initWithRequestEndpoint:(id)arg1 mobileApiAdAdapter:(id)arg2 monetizableTrack:(id)arg3;

@end

