//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC10SoundCloud40MyCollectionRecentTracksPreviewPresenter.h"

@interface _TtC10SoundCloud40MyCollectionRecentTracksPreviewPresenter (SoundCloud1)
- (id)headerIdentifierForInfo:(id)arg1;
- (void)displayInfo:(id)arg1 inHeader:(id)arg2;
- (struct CGSize)headerSizeForInfo:(id)arg1 inContentView:(id)arg2;
@property(nonatomic, readonly) _Bool shouldAlwaysShowHeader;
@end

