//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKit/SKProductsRequest.h>

@interface _TtCC8Payments6FakeSK15ProductsRequest : SKProductsRequest
{
}

- (id)init;
- (id)initWithProductIdentifiers:(id)arg1;
- (void)start;

@end

