//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10SoundCloud24UserDefaultsMenuDelegate : NSObject
{
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: navigationController
    // Error parsing type: , name: tableView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

