//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10SoundCloud22SystemPlaylistLauncher : NSObject
{
    // Error parsing type: , name: urn
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)launchFromSourceViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;

@end

