//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP10SoundCloud24Collection2Experimenting_-Protocol.h"

@interface _TtC10SoundCloud9ABManager : NSObject <_TtP10SoundCloud24Collection2Experimenting_>
{
    // Error parsing type: , name: userDefaults
    // Error parsing type: , name: oldAssignmentsKey
    // Error parsing type: , name: oldDeveloperAssignmentsKey
    // Error parsing type: , name: assignmentsKey
    // Error parsing type: , name: developerAssignmentsKey
}

- (CDUnknownBlockType).cxx_destruct;
- (id)assignedVariantsIds;
- (id)init;
@property(nonatomic, readonly) _Bool isUserInControl;
@property(nonatomic, readonly) _Bool isCollection2Enabled;

@end

