//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4Core14AsyncOperation.h"

@interface _TtC10SoundCloud20DelayedInitOperation : _TtC4Core14AsyncOperation
{
    // Error parsing type: , name: makeOperation
    // Error parsing type: , name: queue
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

