//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8Payments15NSLoggingObject.h"

@interface _TtC8Payments21ConsumerSubscriptions : _TtC8Payments15NSLoggingObject
{
}

+ (id)stringToVendorDictionary;
+ (id)stringToPlanDictionary;
+ (id)planFromInteger:(long long)arg1;
+ (id)planFromString:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

