//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC10SoundCloud20SoundCloudAppSupport.h"

#import "_TtP8Features24FeatureFlagServiceMaking_-Protocol.h"

@interface _TtC10SoundCloud20SoundCloudAppSupport (SoundCloud1) <_TtP8Features24FeatureFlagServiceMaking_>
- (Class)makeFeatureFlagService;
@end

