//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface _TtC8Playback22PlaybackAnalyticsEvent : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: version
    // Error parsing type: , name: attributes
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithName:(id)arg1 version:(long long)arg2 attributes:(id)arg3;
@property(nonatomic, copy) NSDictionary *attributes; // @synthesize attributes;
@property(nonatomic, readonly) long long version; // @synthesize version;
@property(nonatomic, readonly) NSString *name; // @synthesize name;

@end

