//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC3Ads26ForceAdTestIdentifierStore : NSObject
{
    // Error parsing type: , name: lineID
    // Error parsing type: , name: creativeID
    // Error parsing type: , name: shouldRespectAdTimer
}

+ (id)shared;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) _Bool shouldRespectAdTimer; // @synthesize shouldRespectAdTimer;
@property(nonatomic, copy) NSString *creativeID; // @synthesize creativeID;
@property(nonatomic, copy) NSString *lineID; // @synthesize lineID;

@end

