//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10SoundCloud18FirebaseTechLogger : NSObject
{
    // Error parsing type: , name: logEvent
    // Error parsing type: , name: privacySettingsStorage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)logEvent:(id)arg1;
- (id)init;

@end

