//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtCC2UI14UIImageFactory13PlayerButtons : NSObject
{
}

+ (id)makeGeoblocked;
+ (id)makeRetryPressed;
+ (id)makeRetry;
+ (id)makePlayPressed;
+ (id)makePlay;
+ (id)makePlayerPausedCenterPressed;
+ (id)makePlayerPausedEndRightPressed;
+ (id)makePlayerPausedEndLeftPressed;
+ (id)makePlayerPausedPressed;
+ (id)makePlayerCenterPressed;
+ (id)makePlayerEndRightPressed;
+ (id)makePlayerEndLeftPressed;
+ (id)makePlayerPressed;
+ (id)makePlayerPausedCenter;
+ (id)makePlayerPausedEndRight;
+ (id)makePlayerPausedEndLeft;
+ (id)makePlayerPaused;
+ (id)makePlayerCenter;
+ (id)makePlayerEndRight;
+ (id)makePlayerEndLeft;
+ (id)makePlayer;
- (id)init;

@end

