//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint;

@interface _TtC10SoundCloud22UserPlaylistHeaderView : UIView
{
    // Error parsing type: , name: artworkContainerView
    // Error parsing type: , name: engagementContainerView
    // Error parsing type: , name: engagementViewHeight
    // Error parsing type: , name: separatorHeight
    // Error parsing type: , name: engagementViewHeightConstant
    // Error parsing type: , name: maxArtworkHeight
    // Error parsing type: , name: artworkView
    // Error parsing type: , name: engagementView
    // Error parsing type: , name: engagementViewPresenter
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
@property(nonatomic, retain) NSLayoutConstraint *engagementViewHeight; // @synthesize engagementViewHeight;
@property(nonatomic, retain) UIView *engagementContainerView; // @synthesize engagementContainerView;
@property(nonatomic, retain) UIView *artworkContainerView; // @synthesize artworkContainerView;

@end

