//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIViewController;

@protocol _TtP8Features15UpsellLaunching_
- (void)launchFromSourceViewController:(UIViewController *)arg1 animated:(_Bool)arg2 context:(long long)arg3 completion:(void (^)(void))arg4;
@end

