//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol _TtP8Features13PlayQueueItem_;

@protocol _TtP8Playback19PlayerStateUpdating_
- (unsigned long long)updatedStateFor:(unsigned long long)arg1 item:(id <_TtP8Features13PlayQueueItem_>)arg2;
@end

