//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNumber, NSSet;
@protocol _TtP8Features24OfflineUserConfiguration_;

@protocol _TtP8Features24OfflineUserConfiguration_ <NSObject>
+ (id <_TtP8Features24OfflineUserConfiguration_>)default;
@property(readonly, nonatomic) _Bool collectionAvailableOffline;
@property(readonly, nonatomic) NSNumber *storageLimit;
@property(readonly, nonatomic) _Bool syncOnlyViaWiFi;
@property(readonly, copy, nonatomic) NSSet *offlinePlaylists;
@property(readonly, nonatomic) _Bool syncLikesOffline;
@end

