//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Urn;

@interface AboutUserViewControllerFactory : NSObject
{
    Urn *_urn;
}

@property(readonly, nonatomic) Urn *urn; // @synthesize urn=_urn;
- (void).cxx_destruct;
- (id)userInfoService;
- (id)aboutUserViewController;
- (id)initWithUrn:(id)arg1;

@end

