//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AlertConfigurationFactory : NSObject
{
}

- (id)removeRecentTracksFailed;
- (id)removeRecentlyPlayedContextsFailed;
- (id)removeListeningHistoryAlertConfigurationWithContinueBlock:(CDUnknownBlockType)arg1;
- (id)removeRecentlyPlayedAlertConfigurationWithContinueBlock:(CDUnknownBlockType)arg1;
- (id)alertConfigurationWithVocalError:(id)arg1;
- (id)followBlockedByMinimumAge:(id)arg1 forUser:(id)arg2;
- (id)followBlockedByUser:(id)arg1;
- (id)failedEngagementConfigurationWithTitle:(id)arg1 entity:(id)arg2;
- (id)offlineContentLogoutWarningConfigurationWithContinueBlock:(CDUnknownBlockType)arg1;
- (id)offlineExpiredConfiguration;
- (id)offlineThresholdConfiguration:(long long)arg1;
- (id)relatedTracksFetchingFailed;
- (id)foregroundTotalConfigurationDeviceLimitReached;
- (id)loginAlertTotalConfigurationDeviceLimitReached;
- (id)foregroundActiveConfigurationDeviceLimitReached;
- (id)loginAlertActiveConfigurationDeviceLimitReached;
- (id)authAlertConfiguration;
- (id)alertConfigurationForResetPasswordFailure;
- (id)alertConfigurationForResetPasswordSuccessfulWithContinueBlock:(CDUnknownBlockType)arg1;

@end

