//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AlertConfigurationFactory;

@interface AlertHandlerFactory : NSObject
{
    AlertConfigurationFactory *_configFactory;
}

@property(readonly, nonatomic) AlertConfigurationFactory *configFactory; // @synthesize configFactory=_configFactory;
- (void).cxx_destruct;
- (id)underAgeFollowHandler:(id)arg1 forUser:(id)arg2;
- (id)blockedFollowHandler:(id)arg1;
- (id)failedEngagementHandler:(id)arg1 entity:(id)arg2;
- (id)offlineExpiredHandler;
- (id)offlineThresholdHandler:(long long)arg1;
- (id)relatedTracksAlertHandler;
- (id)foregroundTotalDeviceLimitHandler;
- (id)foregroundActiveDeviceLimitHandler;
- (id)initWithAlertConfigurationFactory:(id)arg1;
- (id)init;

@end

