//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PlayQueueItemViewController.h"

@class AdSkipCalculator, AnalyticsUpsellEventTagger, AnalyticsVisualImpressionObserver, UpsellManager;

@interface AudioAdPlayerViewController : PlayQueueItemViewController
{
    AnalyticsVisualImpressionObserver *_analyticsVisualImpressionObserver;
    AnalyticsUpsellEventTagger *_analyticsUpsellTagger;
    UpsellManager *_upsellManager;
    AdSkipCalculator *_adSkipCalculator;
}

+ (id)instantiateControllerFromStoryboard;
@property(retain, nonatomic) AdSkipCalculator *adSkipCalculator; // @synthesize adSkipCalculator=_adSkipCalculator;
@property(retain, nonatomic) UpsellManager *upsellManager; // @synthesize upsellManager=_upsellManager;
@property(retain, nonatomic) AnalyticsUpsellEventTagger *analyticsUpsellTagger; // @synthesize analyticsUpsellTagger=_analyticsUpsellTagger;
@property(retain, nonatomic) AnalyticsVisualImpressionObserver *analyticsVisualImpressionObserver; // @synthesize analyticsVisualImpressionObserver=_analyticsVisualImpressionObserver;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)learnMoreActionTriggered:(id)arg1;
- (long long)screen;
- (void)presentViewForPlayState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (id)audioAdPlayerPresenter;
- (void)didTapInsideAdCompanion:(id)arg1;
- (void)didTapOutsideAdCompanion:(id)arg1;
- (void)updateWithItem;
- (void)willSkipToNext;
- (_Bool)shouldSkipToNextTrack;
- (void)initializeCurrentStateAnimated:(_Bool)arg1;
- (void)setupSkipCounterWithProgress:(double)arg1;
- (void)initializeCurrentProgress;
- (id)subscribePlayState;
- (id)subscribeProgress;
- (id)audioAd;
- (void)setPlayQueueItem:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)awakeFromNib;

@end

