//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BasicApiQueue, RequestCreator;

@interface EntityCollectionsCallFactory : NSObject
{
    BasicApiQueue *_apiQueue;
    RequestCreator *_requestCreator;
}

@property(readonly, nonatomic) RequestCreator *requestCreator; // @synthesize requestCreator=_requestCreator;
@property(readonly, nonatomic) BasicApiQueue *apiQueue; // @synthesize apiQueue=_apiQueue;
- (void).cxx_destruct;
- (id)apiCallForFetchingStations:(id)arg1;
- (id)apiCallForFetchingTracks:(id)arg1;
- (id)apiCallForFetchingUsers:(id)arg1;
- (id)apiCallForFetchingPlaylists:(id)arg1;
- (id)initWithRequestCreator:(id)arg1 apiQueue:(id)arg2;
- (id)init;

@end

