//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ImageDownloadQueue, PlaylistRepository, SyncNotifier;

@interface FetchPlaylistTracksService : NSObject
{
    PlaylistRepository *_playlistRepository;
    ImageDownloadQueue *_imageDownloadQueue;
    SyncNotifier *_syncNotifier;
}

@property(readonly, nonatomic) SyncNotifier *syncNotifier; // @synthesize syncNotifier=_syncNotifier;
@property(readonly, nonatomic) ImageDownloadQueue *imageDownloadQueue; // @synthesize imageDownloadQueue=_imageDownloadQueue;
@property(readonly, nonatomic) PlaylistRepository *playlistRepository; // @synthesize playlistRepository=_playlistRepository;
- (void).cxx_destruct;
- (id)artworkWithSuppressedErrorForPlaylistUrn:(id)arg1;
- (id)playlistTracksDataWithUrn:(id)arg1;
- (id)syncPlaylistTracksDataWithUrn:(id)arg1;
- (id)syncPlaylistWithUrn:(id)arg1;
- (id)fetchTracksForPlaylistUrn:(id)arg1;
- (id)initWithPlaylistRepository:(id)arg1 imageDownloadQueue:(id)arg2 syncNotifier:(id)arg3;
- (id)init;

@end

