//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC10SoundCloud24GoogleCastFeatureManager;

@interface GoogleCastView : UIView
{
    _TtC10SoundCloud24GoogleCastFeatureManager *_featureManager;
}

@property(retain, nonatomic) _TtC10SoundCloud24GoogleCastFeatureManager *featureManager; // @synthesize featureManager=_featureManager;
- (void).cxx_destruct;
- (void)setupGoogleCastView;
- (id)initWithCoder:(id)arg1 featureManager:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

