//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "Trigger-Protocol.h"

@class KeyboardNotificationFactory, NSString, RACDisposable, RACSubject;

@interface KeyboardVisibleTrigger : NSObject <Trigger>
{
    KeyboardNotificationFactory *_keyboardNotificationFactory;
    RACSubject *_keyboardVisibilitySubject;
    RACDisposable *_disposable;
}

@property(retain, nonatomic) RACDisposable *disposable; // @synthesize disposable=_disposable;
@property(readonly, nonatomic) RACSubject *keyboardVisibilitySubject; // @synthesize keyboardVisibilitySubject=_keyboardVisibilitySubject;
@property(readonly, nonatomic) KeyboardNotificationFactory *keyboardNotificationFactory; // @synthesize keyboardNotificationFactory=_keyboardNotificationFactory;
- (void).cxx_destruct;
- (id)subscribeKeyboardHide;
- (id)subscribeKeyboardShow;
- (id)triggerSignal;
- (void)stop;
- (void)start;
- (id)initWithKeyboardNotificationFactory:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

