//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "RefreshArtworkLayoutDelegate-Protocol.h"
#import "SectionDividerDecoratorDelegate-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UserProfileSectionFooterDelegate-Protocol.h"

@class AboutUserLauncher, AnalyticsInteractionEventTagger, CardCellActionHandler, ColumnLayout, LegacyPlayerLauncher, MarketingController, NSString, NewAndShinyDataSource, ReachabilityCollectionViewCoordinator, RefreshArtworkLayout, SectionDividerDecorator, SuperSpotlightCellPresenter, TrackActionHandler, TrackCellPresenter, UICollectionView, UserContentPlaylistStorageControllerFactory, UserContentTrackStorageControllerFactory, UserProfileActionHandler, UserProfileArtworkPresenter, UserProfileService, UserProfileStateCoordinator, UserProfileUser, UserProfileUserSpotlightStorageControllerFactory, UserProfileUserStorageControllerFactory, _TtC10SoundCloud26ProfileUpsellActionHandler;
@protocol Launcher;

@interface LegacyUserProfileViewController : BaseViewController <UICollectionViewDelegate, UserProfileSectionFooterDelegate, RefreshArtworkLayoutDelegate, SectionDividerDecoratorDelegate>
{
    UICollectionView *_collectionView;
    UserProfileArtworkPresenter *_userProfileArtworkPresenter;
    RefreshArtworkLayout *_refreshArtworkLayout;
    ColumnLayout *_spotlightLayout;
    ColumnLayout *_postedReleasesLayout;
    ColumnLayout *_postedTracksLayout;
    ColumnLayout *_likedTracksLayout;
    ColumnLayout *_postPlaylistsLayout;
    ColumnLayout *_repostPlaylistsLayout;
    ColumnLayout *_likePlaylistsLayout;
    UserProfileStateCoordinator *_userProfileStateCoordinator;
    TrackCellPresenter *_trackCellPresenter;
    TrackActionHandler *_trackActionHandler;
    CardCellActionHandler *_spotlightActionHandler;
    NewAndShinyDataSource *_dataSource;
    UserProfileService *_profileService;
    UserProfileActionHandler *_actionHandler;
    SectionDividerDecorator *_decorator;
    SuperSpotlightCellPresenter *_spotlightCellPresenter;
    UserProfileUserStorageControllerFactory *_userFactory;
    UserProfileUserSpotlightStorageControllerFactory *_userSpotlightFactory;
    UserContentPlaylistStorageControllerFactory *_userPlaylistFactory;
    UserContentTrackStorageControllerFactory *_userTrackFactory;
    AnalyticsInteractionEventTagger *_analyticsTagger;
    UserProfileUser *_user;
    id <Launcher> _launcher;
    ReachabilityCollectionViewCoordinator *_reachabilityCoordinator;
    LegacyPlayerLauncher *_playerLauncher;
    AboutUserLauncher *_aboutUserLauncher;
    _TtC10SoundCloud26ProfileUpsellActionHandler *_upsellActionHandler;
    MarketingController *_marketingController;
}

@property(nonatomic) __weak MarketingController *marketingController; // @synthesize marketingController=_marketingController;
@property(retain, nonatomic) _TtC10SoundCloud26ProfileUpsellActionHandler *upsellActionHandler; // @synthesize upsellActionHandler=_upsellActionHandler;
@property(retain, nonatomic) AboutUserLauncher *aboutUserLauncher; // @synthesize aboutUserLauncher=_aboutUserLauncher;
@property(retain, nonatomic) LegacyPlayerLauncher *playerLauncher; // @synthesize playerLauncher=_playerLauncher;
@property(retain, nonatomic) ReachabilityCollectionViewCoordinator *reachabilityCoordinator; // @synthesize reachabilityCoordinator=_reachabilityCoordinator;
@property(retain, nonatomic) id <Launcher> launcher; // @synthesize launcher=_launcher;
@property(retain, nonatomic) UserProfileUser *user; // @synthesize user=_user;
@property(readonly, nonatomic) AnalyticsInteractionEventTagger *analyticsTagger; // @synthesize analyticsTagger=_analyticsTagger;
@property(readonly, nonatomic) UserContentTrackStorageControllerFactory *userTrackFactory; // @synthesize userTrackFactory=_userTrackFactory;
@property(readonly, nonatomic) UserContentPlaylistStorageControllerFactory *userPlaylistFactory; // @synthesize userPlaylistFactory=_userPlaylistFactory;
@property(readonly, nonatomic) UserProfileUserSpotlightStorageControllerFactory *userSpotlightFactory; // @synthesize userSpotlightFactory=_userSpotlightFactory;
@property(readonly, nonatomic) UserProfileUserStorageControllerFactory *userFactory; // @synthesize userFactory=_userFactory;
@property(retain, nonatomic) SuperSpotlightCellPresenter *spotlightCellPresenter; // @synthesize spotlightCellPresenter=_spotlightCellPresenter;
@property(retain, nonatomic) SectionDividerDecorator *decorator; // @synthesize decorator=_decorator;
@property(retain, nonatomic) UserProfileActionHandler *actionHandler; // @synthesize actionHandler=_actionHandler;
@property(retain, nonatomic) UserProfileService *profileService; // @synthesize profileService=_profileService;
@property(retain, nonatomic) NewAndShinyDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) CardCellActionHandler *spotlightActionHandler; // @synthesize spotlightActionHandler=_spotlightActionHandler;
@property(retain, nonatomic) TrackActionHandler *trackActionHandler; // @synthesize trackActionHandler=_trackActionHandler;
@property(retain, nonatomic) TrackCellPresenter *trackCellPresenter; // @synthesize trackCellPresenter=_trackCellPresenter;
@property(retain, nonatomic) UserProfileStateCoordinator *userProfileStateCoordinator; // @synthesize userProfileStateCoordinator=_userProfileStateCoordinator;
@property(retain, nonatomic) ColumnLayout *likePlaylistsLayout; // @synthesize likePlaylistsLayout=_likePlaylistsLayout;
@property(retain, nonatomic) ColumnLayout *repostPlaylistsLayout; // @synthesize repostPlaylistsLayout=_repostPlaylistsLayout;
@property(retain, nonatomic) ColumnLayout *postPlaylistsLayout; // @synthesize postPlaylistsLayout=_postPlaylistsLayout;
@property(retain, nonatomic) ColumnLayout *likedTracksLayout; // @synthesize likedTracksLayout=_likedTracksLayout;
@property(retain, nonatomic) ColumnLayout *postedTracksLayout; // @synthesize postedTracksLayout=_postedTracksLayout;
@property(retain, nonatomic) ColumnLayout *postedReleasesLayout; // @synthesize postedReleasesLayout=_postedReleasesLayout;
@property(retain, nonatomic) ColumnLayout *spotlightLayout; // @synthesize spotlightLayout=_spotlightLayout;
@property(retain, nonatomic) RefreshArtworkLayout *refreshArtworkLayout; // @synthesize refreshArtworkLayout=_refreshArtworkLayout;
@property(retain, nonatomic) UserProfileArtworkPresenter *userProfileArtworkPresenter; // @synthesize userProfileArtworkPresenter=_userProfileArtworkPresenter;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)logEvent:(id)arg1;
- (void)logProfileVisitEvent;
- (_Bool)refreshArtworkLayout:(id)arg1 shouldDisplayUpsellInRect:(struct CGRect)arg2;
- (_Bool)shouldDisplayProfileUpsell;
- (double)sectionDividerDecorator:(id)arg1 heightForDividerAtSection:(long long)arg2;
- (id)playQueueDataSourceForItem:(id)arg1 inSection:(unsigned long long)arg2;
- (void)userProfileSectionFooterDidTapButtonForSection:(unsigned long long)arg1;
- (id)sectionDescriptionForSection:(unsigned long long)arg1;
- (id)playerTaggingContext;
- (id)supplementaryPresenterForSection:(unsigned long long)arg1;
- (id)userRepostPlaylistsDataSourceForSection:(unsigned long long)arg1;
- (id)userPostPlaylistsDataSourceForSection:(unsigned long long)arg1;
- (id)userPostedReleaseDataSourceForSection:(unsigned long long)arg1;
- (id)userLikePlaylistDataSourceForSection:(unsigned long long)arg1;
- (id)userLikedTrackDataSourceForSection:(unsigned long long)arg1;
- (id)userPostedTrackDataSourceForSection:(unsigned long long)arg1;
- (id)userSpotlightDataSourceForSection:(unsigned long long)arg1;
- (id)userProfileDataSource;
- (id)dataSources;
- (void)configurePresenter;
- (void)openPlaylistWithUrn:(id)arg1 reposterUrn:(id)arg2;
- (void)createActionHandler;
- (void)configureReachabilityCoordinator;
- (void)configureLayoutWithChildLayouts:(id)arg1;
- (void)showAboutUser;
- (id)rightNavigationBarButton;
- (id)childLayouts;
- (void)configureLayout;
- (void)createDataSource;
- (_Bool)shouldLaunchPlaylistForItem:(id)arg1 section:(unsigned long long)arg2;
- (void)privacyUpdated;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)sourceContext;
- (long long)screen;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

