//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class MobileApiTranscodingFormat, NSString;

@interface MobileApiTranscoding : MTLModel <MTLJSONSerializing>
{
    _Bool _snipped;
    long long _duration;
    NSString *_preset;
    NSString *_quality;
    NSString *_url;
    MobileApiTranscodingFormat *_format;
}

+ (id)formatJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) MobileApiTranscodingFormat *format; // @synthesize format=_format;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) _Bool snipped; // @synthesize snipped=_snipped;
@property(copy, nonatomic) NSString *quality; // @synthesize quality=_quality;
@property(copy, nonatomic) NSString *preset; // @synthesize preset=_preset;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (_Bool)validate:(id *)arg1;

@end

