//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSFetchRequestCreator : NSObject
{
}

- (id)prefetchKeysFromRequest:(id)arg1;
- (id)requestFromStorageRequest:(id)arg1 returnsObjectsAsFaults:(_Bool)arg2;
- (id)requestFromStorageRequest:(id)arg1;

@end

