//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP8Features24OfflineUserConfiguration_-Protocol.h"

@class NSNumber, NSSet, NSString;

@interface OfflineUserConfig : NSObject <_TtP8Features24OfflineUserConfiguration_>
{
    _Bool _syncLikesOffline;
    _Bool _syncOnlyViaWiFi;
    _Bool _collectionAvailableOffline;
    NSSet *_offlinePlaylists;
    NSNumber *_storageLimit;
}

+ (id)defaultWithPlaylists:(id)arg1;
+ (id)default;
@property(retain, nonatomic) NSNumber *storageLimit; // @synthesize storageLimit=_storageLimit;
@property(nonatomic) _Bool collectionAvailableOffline; // @synthesize collectionAvailableOffline=_collectionAvailableOffline;
@property(nonatomic) _Bool syncOnlyViaWiFi; // @synthesize syncOnlyViaWiFi=_syncOnlyViaWiFi;
@property(copy, nonatomic) NSSet *offlinePlaylists; // @synthesize offlinePlaylists=_offlinePlaylists;
@property(nonatomic) _Bool syncLikesOffline; // @synthesize syncLikesOffline=_syncLikesOffline;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSyncLikesOffline:(_Bool)arg1 syncOnlyViaWifi:(_Bool)arg2 storageLimit:(id)arg3 collectionAvailableOffline:(_Bool)arg4 offlinePlaylists:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

