//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TouchInsetButton.h"

@interface OldPlayerButton : TouchInsetButton
{
    _Bool _isImageRightAligned;
    unsigned long long _backgroundStyle;
}

@property(nonatomic) _Bool isImageRightAligned; // @synthesize isImageRightAligned=_isImageRightAligned;
@property(nonatomic) unsigned long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
- (void)setHidden:(_Bool)arg1;
- (struct CGSize)intrinsicContentSize;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (id)highlightedBackgroundImageForStyle:(unsigned long long)arg1;
- (id)backgroundImageForStyle:(unsigned long long)arg1;
- (void)initPlayerButton;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

