//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PlayableTagParser : NSObject
{
}

+ (id)sharedInstance;
- (_Bool)containsMachineTags:(id)arg1;
- (id)filteredTagList:(id)arg1 byRegexPattern:(id)arg2;
- (id)parsedTags:(id)arg1;
- (id)machineTag:(id)arg1;

@end

