//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PlayerLauncherFactory : NSObject
{
}

- (id)playerLauncherWithPlaylistUrn:(id)arg1 playlistTrack:(id)arg2 shouldShuffle:(_Bool)arg3 promotedState:(id)arg4 taggingContext:(id)arg5;

@end

