//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString, Urn;

@interface PlaylistMetaDataEntity : NSObject
{
    _Bool _isPrivate;
    _Bool _isRelease;
    Urn *_urn;
    long long _likeCount;
    NSString *_releaseSetType;
    NSDate *_releaseDate;
}

@property(readonly, nonatomic) NSDate *releaseDate; // @synthesize releaseDate=_releaseDate;
@property(readonly, nonatomic) NSString *releaseSetType; // @synthesize releaseSetType=_releaseSetType;
@property(readonly, nonatomic) long long likeCount; // @synthesize likeCount=_likeCount;
@property(readonly, nonatomic) _Bool isRelease; // @synthesize isRelease=_isRelease;
@property(readonly, nonatomic) _Bool isPrivate; // @synthesize isPrivate=_isPrivate;
@property(readonly, nonatomic) Urn *urn; // @synthesize urn=_urn;
- (void).cxx_destruct;
- (id)initWithPlaylist:(id)arg1;

@end

