//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP8Payments25AppReceiptRefreshObserver_-Protocol.h"
#import "_TtP8Payments25AppReceiptRequestObserver_-Protocol.h"

@class _TtC8Payments10AppReceipt, _TtC8Payments32AppReceiptRefreshRequestDelegate;
@protocol RACSubscriber;

@interface ReactiveAppReceipt : NSObject <_TtP8Payments25AppReceiptRequestObserver_, _TtP8Payments25AppReceiptRefreshObserver_>
{
    _TtC8Payments10AppReceipt *_appReceipt;
    id <RACSubscriber> _receiptSubscriber;
    id <RACSubscriber> _refreshSubscriber;
    _TtC8Payments32AppReceiptRefreshRequestDelegate *_receiptRefreshRequestDelegate;
}

@property(retain, nonatomic) _TtC8Payments32AppReceiptRefreshRequestDelegate *receiptRefreshRequestDelegate; // @synthesize receiptRefreshRequestDelegate=_receiptRefreshRequestDelegate;
@property(nonatomic) __weak id <RACSubscriber> refreshSubscriber; // @synthesize refreshSubscriber=_refreshSubscriber;
@property(nonatomic) __weak id <RACSubscriber> receiptSubscriber; // @synthesize receiptSubscriber=_receiptSubscriber;
@property(readonly, nonatomic) _TtC8Payments10AppReceipt *appReceipt; // @synthesize appReceipt=_appReceipt;
- (void).cxx_destruct;
- (void)refreshFailureWithRequest:(id)arg1 error:(id)arg2;
- (void)refreshSuccessWithRequest:(id)arg1;
- (void)receiptFailureWithError:(id)arg1;
- (void)receiptSuccessWithEncodedReceipt:(id)arg1;
- (id)receiptRequestSignal;
- (id)receiptRefreshSignal;
- (id)initWithAppReceipt:(id)arg1;
- (id)init;

@end

