//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ChildLayout.h"

@class UICollectionViewLayoutAttributes;
@protocol RefreshArtworkLayoutDelegate;

@interface RefreshArtworkLayout : ChildLayout
{
    _Bool _didCompleteInitialLoad;
    long long _artworkType;
    id <RefreshArtworkLayoutDelegate> _delegate;
    UICollectionViewLayoutAttributes *_artworkAttributes;
    UICollectionViewLayoutAttributes *_barAttributes;
    UICollectionViewLayoutAttributes *_emptyAttributes;
    UICollectionViewLayoutAttributes *_upsellAttributes;
}

@property(nonatomic) _Bool didCompleteInitialLoad; // @synthesize didCompleteInitialLoad=_didCompleteInitialLoad;
@property(retain, nonatomic) UICollectionViewLayoutAttributes *upsellAttributes; // @synthesize upsellAttributes=_upsellAttributes;
@property(retain, nonatomic) UICollectionViewLayoutAttributes *emptyAttributes; // @synthesize emptyAttributes=_emptyAttributes;
@property(retain, nonatomic) UICollectionViewLayoutAttributes *barAttributes; // @synthesize barAttributes=_barAttributes;
@property(retain, nonatomic) UICollectionViewLayoutAttributes *artworkAttributes; // @synthesize artworkAttributes=_artworkAttributes;
@property(nonatomic) __weak id <RefreshArtworkLayoutDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long artworkType; // @synthesize artworkType=_artworkType;
- (void).cxx_destruct;
- (_Bool)collectionViewIsEmpty;
- (_Bool)shouldShowEmptyView;
- (struct CGRect)calculateEmptyViewFrameWithOffset:(double)arg1;
- (struct CGRect)calculateUpsellViewFrameWithOffset:(double)arg1;
- (struct CGRect)calculateBarViewFrameWithOffset:(double)arg1;
- (double)artworkBottomForBounds:(struct CGRect)arg1;
- (struct CGRect)calculateArtworkFrameForBounds:(struct CGRect)arg1;
- (id)calculateEmptyViewAttributesWithOffset:(double)arg1;
- (id)calculateUpsellViewAttributesWithOffset:(double)arg1;
- (id)calculateBarViewAttributesWithOffset:(double)arg1;
- (id)calculateArtworkAttributes;
- (long long)numberOfItemsInSection;
- (id)filterUpsellAttributesFromAllAttributes:(id)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)bottomElementAttribute;
- (struct CGSize)collectionViewContentSize;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)allLayoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayoutWithOffset:(double)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (void)setState:(unsigned long long)arg1;

@end

