//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NewApiCoreDataAdapter-Protocol.h"

@class NSEntityDescription, NSManagedObjectContext, NSString, TrackAdapter, Urn;

@interface StationTrackAdapter : NSObject <NewApiCoreDataAdapter>
{
    NSManagedObjectContext *_context;
    Urn *_stationUrn;
    TrackAdapter *_trackAdapter;
    unsigned long long _index;
    NSEntityDescription *_entityDescription;
}

@property(readonly, nonatomic) NSEntityDescription *entityDescription; // @synthesize entityDescription=_entityDescription;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(readonly, nonatomic) TrackAdapter *trackAdapter; // @synthesize trackAdapter=_trackAdapter;
@property(readonly, nonatomic) Urn *stationUrn; // @synthesize stationUrn=_stationUrn;
@property(readonly, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)station;
- (id)createStationTrackWithTrack:(id)arg1 station:(id)arg2 queryUrn:(id)arg3;
- (id)adapt:(id)arg1;
- (id)initWithManagedObjectContext:(id)arg1 stationUrn:(id)arg2 trackAdapter:(id)arg3;
- (id)initWithManagedObjectContext:(id)arg1 stationUrn:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

