//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Decryptor.h"

@interface StreamDecryptor : Decryptor
{
}

- (id)decryptedDataForData:(id)arg1 shouldFinalize:(_Bool)arg2;
- (void)dealloc;
- (id)initWithKey:(id *)arg1;

@end

