//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface TaggingContext : NSObject
{
    long long _sourceScreen;
    NSString *_sourceScreenString;
    NSDictionary *_sourceAttributes;
}

+ (id)contextWithSourceScreen:(long long)arg1;
+ (id)contextWithSourceScreen:(long long)arg1 attributes:(id)arg2;
+ (id)contextWithSourceScreenString:(id)arg1;
+ (id)contextWithSourceScreenString:(id)arg1 attributes:(id)arg2;
@property(readonly, nonatomic) NSDictionary *sourceAttributes; // @synthesize sourceAttributes=_sourceAttributes;
@property(readonly, copy, nonatomic) NSString *sourceScreenString; // @synthesize sourceScreenString=_sourceScreenString;
@property(readonly, nonatomic) long long sourceScreen; // @synthesize sourceScreen=_sourceScreen;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)screenHash;
- (unsigned long long)hash;
- (_Bool)isEqualToTaggingContext:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSourceScreenString:(id)arg1 attributes:(id)arg2;
- (id)initWithSourceScreen:(long long)arg1 attributes:(id)arg2;

@end

