//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBar.h>

@class UIView, _TtC2UI11ViewsSorter;

@interface TitlelessTabBar : UITabBar
{
    UIView *_customView;
    unsigned long long _customViewIndex;
    _TtC2UI11ViewsSorter *_viewsSorter;
}

@property(retain, nonatomic) _TtC2UI11ViewsSorter *viewsSorter; // @synthesize viewsSorter=_viewsSorter;
@property(nonatomic) unsigned long long customViewIndex; // @synthesize customViewIndex=_customViewIndex;
@property(nonatomic) __weak UIView *customView; // @synthesize customView=_customView;
- (void).cxx_destruct;
- (id)sortedItemViews;
- (id)viewForItemWithIndex:(unsigned long long)arg1;
- (void)configureTabItems;
- (id)accessibilityIdentifier;
- (void)layoutSubviews;
- (void)setItems:(id)arg1 animated:(_Bool)arg2;
- (void)removeCustomView;
- (void)addCustomView:(id)arg1 toTabItem:(id)arg2;
- (void)initTitlelessTabBar;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

