//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCPlanManager;

@interface TrackAuthorizationHelper : NSObject
{
    SCPlanManager *_planManager;
}

@property(readonly, nonatomic) SCPlanManager *planManager; // @synthesize planManager=_planManager;
- (void).cxx_destruct;
- (_Bool)isHighTier:(id)arg1;
- (_Bool)isHighTierPreview:(id)arg1;
- (_Bool)shouldShowPreviewLabelAndGoMarkerForTrack:(id)arg1;
- (_Bool)shouldShowGoMarkerForTrack:(id)arg1;
- (id)initWithPlanManager:(id)arg1;

@end

