//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC7TV4Play24TV4WebViewViewController : UIViewController
{
    // Error parsing type: , name: url
    // Error parsing type: , name: backButton
    // Error parsing type: , name: forwardButton
    // Error parsing type: , name: webView.storage
    // Error parsing type: , name: activityIndicator.storage
    // Error parsing type: , name: toolbar.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)navigateForward;
- (void)navigateBack;
- (void)dismissController;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

