//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, NSURL, _TtC18bonnier_ios_player13BonnierPlayer;

@protocol _TtP18bonnier_ios_player21BonnierPlayerDelegate_ <NSObject>
- (void)didFailWith:(NSError *)arg1 bonnierPlayer:(_TtC18bonnier_ios_player13BonnierPlayer *)arg2;
- (void)didClose:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1 at:(double)arg2 with:(double)arg3;

@optional
- (void)didTapAdIn:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1 with:(NSURL *)arg2 ofType:(long long)arg3;
- (void)didSelectAudioIn:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1 language:(NSString *)arg2;
- (void)didSelectSubtitleIn:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1 language:(NSString *)arg2;
- (void)didSelectLanguageIn:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1 audio:(NSString *)arg2 subtitle:(NSString *)arg3;
- (void)didReachEndIn:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didPassItemIn:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1 with:(long long)arg2 at:(double)arg3;
- (void)didHideControls:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)willHideControls:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didShowControls:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)willShowControls:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didShare:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didStartPlayingContent:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didDisplayVideo:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didTapReplay:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
- (void)didToggleFullscreen:(_TtC18bonnier_ios_player13BonnierPlayer *)arg1;
@end

