//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KeychainItemWrapper, NSString;

@interface TSMobileAnalytics : NSObject
{
    _Bool _logPrintsActivated;
    _Bool _trackPanelistOnly;
    int _analyticsProvider;
    NSString *_cpid;
    NSString *_applicationName;
    NSString *_keychainAccessGroup;
    NSString *_mref;
    NSString *_mEuid;
    KeychainItemWrapper *_keychainItemWrapper;
}

+ (void)printErrorMessageToLog:(id)arg1;
+ (void)printInputValidationErrorWithMessage:(id)arg1;
+ (void)printErrorToLog:(id)arg1 withMessage:(id)arg2;
+ (void)printError:(id)arg1;
+ (void)printMessageToLog:(id)arg1;
+ (void)syncTokenWithPanelenApp;
+ (_Bool)isApplicationInstalled:(id)arg1;
+ (_Bool)isLegacyApplicationInstalled;
+ (_Bool)isInternetApplicationInstalled;
+ (_Bool)applicationInstalled;
+ (id)panelistToken;
+ (id)cookieDictionaryWithDomain:(id)arg1 Key:(id)arg2 value:(id)arg3;
+ (void)deleteCookiesForDomain:(id)arg1;
+ (void)setCookieWithValue:(id)arg1 forKey:(id)arg2 andDomain:(id)arg3;
+ (id)generateCategoryStringFromArray:(id)arg1;
+ (int)validateInputParametersWithCategory:(id)arg1 contentID:(id)arg2 contentName:(id)arg3;
+ (void)sendTagWithCategories:(id)arg1 contentName:(id)arg2 contentID:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)sendTagWithCategory:(id)arg1 contentName:(id)arg2 contentID:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)setTrackPanelistOnly:(_Bool)arg1;
+ (void)setLogPrintsActivated:(_Bool)arg1;
+ (id)sharedInstance;
+ (id)createInstanceWithCPID:(id)arg1 applicationName:(id)arg2 trackPanelist:(_Bool)arg3 keychainAccessGroup:(id)arg4;
@property(retain, nonatomic) KeychainItemWrapper *keychainItemWrapper; // @synthesize keychainItemWrapper=_keychainItemWrapper;
@property(retain, nonatomic) NSString *mEuid; // @synthesize mEuid=_mEuid;
@property(retain, nonatomic) NSString *mref; // @synthesize mref=_mref;
@property(nonatomic) int analyticsProvider; // @synthesize analyticsProvider=_analyticsProvider;
@property(nonatomic) _Bool trackPanelistOnly; // @synthesize trackPanelistOnly=_trackPanelistOnly;
@property(nonatomic) _Bool logPrintsActivated; // @synthesize logPrintsActivated=_logPrintsActivated;
@property(readonly, nonatomic) NSString *keychainAccessGroup; // @synthesize keychainAccessGroup=_keychainAccessGroup;
@property(retain, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(retain, nonatomic) NSString *cpid; // @synthesize cpid=_cpid;
- (void).cxx_destruct;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)setupKeychainWrapperWithIdentifier:(id)arg1 keychainAccessGroup:(id)arg2;
- (id)getKeychainUserId;
- (void)setCookiesFromURLResourceSpecifier:(id)arg1;
- (void)syncSourceApplicationWithFrameWorkFromURL:(id)arg1;
- (id)getURLWithCategoryArray:(id)arg1 contentName:(id)arg2 contentID:(id)arg3;
- (id)getURLWithCategory:(id)arg1 contentName:(id)arg2 contentID:(id)arg3;
- (id)formattedAccessGroupFromAccessGroup:(id)arg1;
- (id)getBundleSeedID;
- (void)setupKeychainItemWithAccessGroup:(id)arg1;
- (_Bool)syncWithSIFOPanelenApplication;
- (void)setDeviceType;
- (void)saveUserId;
- (id)initWithCPID:(id)arg1 appName:(id)arg2 trackPanelist:(_Bool)arg3 keychainAccessGroup:(id)arg4;

@end

