//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSDictionary, NSString, TV4Api4Program;

@interface TV4Api4VideoAsset : NSObject
{
    NSDictionary *_json;
    _Bool hideAds;
    _Bool _allowEmbed;
    _Bool _showLogo;
    _Bool _drmProtected;
    _Bool _live;
    _Bool _clip;
    _Bool _fullProgram;
    _Bool _liveCenterEnabled;
    NSArray *_keywords;
    NSString *_platform;
    NSString *_videoId;
    NSString *_videoAssetDescription;
    NSDate *_broadcastDateTime;
    NSString *_title;
    NSString *_image;
    long long _programTypeId;
    long long _duration;
    NSArray *_categories;
    NSArray *_productGroupNids;
    NSArray *_geoRegions;
    NSArray *_platforms;
    TV4Api4Program *_program;
    NSDate *_publishedDateTime;
    NSDate *_expireDateTime;
    NSArray *_annotags;
    NSArray *_tags;
    NSDictionary *_burt;
    NSDictionary *_videoplaza;
    long long _episodeId;
    NSString *_branding;
}

+ (id)videoAssetWithDictionary:(id)arg1;
@property(nonatomic) _Bool liveCenterEnabled; // @synthesize liveCenterEnabled=_liveCenterEnabled;
@property(retain, nonatomic) NSString *branding; // @synthesize branding=_branding;
@property(nonatomic, getter=isFullProgram) _Bool fullProgram; // @synthesize fullProgram=_fullProgram;
@property(nonatomic) long long episodeId; // @synthesize episodeId=_episodeId;
@property(retain, nonatomic) NSDictionary *videoplaza; // @synthesize videoplaza=_videoplaza;
@property(retain, nonatomic) NSDictionary *burt; // @synthesize burt=_burt;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(retain, nonatomic) NSArray *annotags; // @synthesize annotags=_annotags;
@property(retain, nonatomic) NSDate *expireDateTime; // @synthesize expireDateTime=_expireDateTime;
@property(retain, nonatomic) NSDate *publishedDateTime; // @synthesize publishedDateTime=_publishedDateTime;
@property(retain, nonatomic) TV4Api4Program *program; // @synthesize program=_program;
@property(nonatomic, getter=isClip) _Bool clip; // @synthesize clip=_clip;
@property(retain, nonatomic) NSArray *platforms; // @synthesize platforms=_platforms;
@property(retain, nonatomic) NSArray *geoRegions; // @synthesize geoRegions=_geoRegions;
@property(retain, nonatomic) NSArray *productGroupNids; // @synthesize productGroupNids=_productGroupNids;
@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(nonatomic) long long programTypeId; // @synthesize programTypeId=_programTypeId;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic, getter=isLive) _Bool live; // @synthesize live=_live;
@property(retain, nonatomic) NSDate *broadcastDateTime; // @synthesize broadcastDateTime=_broadcastDateTime;
@property(nonatomic, getter=isDrmProtected) _Bool drmProtected; // @synthesize drmProtected=_drmProtected;
@property(retain, nonatomic) NSString *videoAssetDescription; // @synthesize videoAssetDescription=_videoAssetDescription;
@property(retain, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
@property(retain, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
@property(nonatomic, getter=isShowLogo) _Bool showLogo; // @synthesize showLogo=_showLogo;
@property(nonatomic, getter=isAllowEmbed) _Bool allowEmbed; // @synthesize allowEmbed=_allowEmbed;
@property(nonatomic, getter=isHideAds) _Bool hideAds; // @synthesize hideAds;
- (void).cxx_destruct;
- (id)asJson;
- (id)initWithDictionary:(id)arg1;

@end

