//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURLSessionDataTask;

@interface TV4SearchEngine : NSObject
{
    CDUnknownBlockType _errorCallbackInSearchForString;
    CDUnknownBlockType _errorCallbackContinueSearch;
    long long _unfinishedSearches;
    NSURLSessionDataTask *_programsSearchTask;
    NSURLSessionDataTask *_episodesSearchTask;
    NSURLSessionDataTask *_clipsSearchTask;
}

@property(retain, nonatomic) NSURLSessionDataTask *clipsSearchTask; // @synthesize clipsSearchTask=_clipsSearchTask;
@property(retain, nonatomic) NSURLSessionDataTask *episodesSearchTask; // @synthesize episodesSearchTask=_episodesSearchTask;
@property(retain, nonatomic) NSURLSessionDataTask *programsSearchTask; // @synthesize programsSearchTask=_programsSearchTask;
@property(nonatomic) long long unfinishedSearches; // @synthesize unfinishedSearches=_unfinishedSearches;
@property(copy, nonatomic) CDUnknownBlockType errorCallbackContinueSearch; // @synthesize errorCallbackContinueSearch=_errorCallbackContinueSearch;
@property(copy, nonatomic) CDUnknownBlockType errorCallbackInSearchForString; // @synthesize errorCallbackInSearchForString=_errorCallbackInSearchForString;
- (void).cxx_destruct;
- (void)cancelPendingSearches;
- (id)perPage;
@property(readonly) _Bool isSearching;
- (id)paramsForResult:(id)arg1 section:(int)arg2;
- (void)continueSearchForResult:(id)arg1 section:(int)arg2 withCallbackBlock:(CDUnknownBlockType)arg3;
- (void)searchForString:(id)arg1 withCallbackBlock:(CDUnknownBlockType)arg2;

@end

