//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface _TtC4WiMP21AppIcon3DTouchService : NSObject
{
}

+ (id)sharedInstance;
- (CDUnknownBlockType).cxx_destruct;
- (_Bool)handleQuickAction:(id)arg1;
- (void)removeCustomShortcutItem;
- (_Bool)isItemAddedAsCustomShortcut:(id)arg1 itemType:(long long)arg2;
- (void)addCustomShortcutItem:(id)arg1 itemType:(long long)arg2 itemTitle:(id)arg3 itemSubtitle:(id)arg4;
- (void)resetDynamicShortcutItems;
- (void)createShortcutItems;
- (void)playQueueDidChanged:(id)arg1;
- (void)offlineModeDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end

