//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4WiMP10CutService : NSObject
{
    // Error parsing type: , name: provider
}

- (CDUnknownBlockType).cxx_destruct;
- (void)updateCut:(id)arg1 name:(id)arg2 startTime:(unsigned long long)arg3 endTime:(unsigned long long)arg4 fadeInDuration:(unsigned long long)arg5 fadeOutDuration:(unsigned long long)arg6 speed:(long long)arg7 completionHandler:(CDUnknownBlockType)arg8;
- (void)obtainCut:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

