//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4WiMP13SonosBaseBody.h"

@interface _TtCCC4WiMP11SonosGlobal23GroupCoordinatorChanged27GroupCoordinatorChangedBody : _TtC4WiMP13SonosBaseBody
{
    // Error parsing type: , name: groupId
    // Error parsing type: , name: groupStatus
    // Error parsing type: , name: groupName
    // Error parsing type: , name: websocketUrl
    // Error parsing type: , name: playerId
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

