//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel, UIView;

@interface _TtC4WiMP21MixCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: graphicsContainer
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: graphicRenderer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *subtitle; // @synthesize subtitle;
@property(nonatomic) __weak UILabel *title; // @synthesize title;
@property(nonatomic) __weak UIView *graphicsContainer; // @synthesize graphicsContainer;

@end

