//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4WiMP13SonosBaseBody.h"

@class _TtC4WiMP14SonosContainer, _TtC4WiMP27SonosUniversalMusicObjectId;

@interface _TtCCC4WiMP20SonosPlaybackSession19LoadProgrammedRadio23LoadProgrammedRadioBody : _TtC4WiMP13SonosBaseBody
{
    // Error parsing type: , name: stationId
    // Error parsing type: , name: playOnCompletion
    // Error parsing type: , name: stationMetadata
}

- (CDUnknownBlockType).cxx_destruct;
- (id)getParameterTypes;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)init;
@property(nonatomic, retain) _TtC4WiMP14SonosContainer *stationMetadata; // @synthesize stationMetadata;
@property(nonatomic, retain) _TtC4WiMP27SonosUniversalMusicObjectId *stationId; // @synthesize stationId;

@end

