//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4WiMP23ArtistTwitterFeedModule.h"

#import "TWTRTweetViewDelegate-Protocol.h"

@interface _TtC4WiMP23ArtistTwitterFeedModule (WiMP) <TWTRTweetViewDelegate>
- (_Bool)tweetView:(id)arg1 shouldDisplayDetailViewController:(id)arg2;
- (void)tweetView:(id)arg1 didTapURL:(id)arg2;
@end

