//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC4WiMP21DescriptionDataSource.h"

@interface _TtC4WiMP27ArtistDescriptionDataSource : _TtC4WiMP21DescriptionDataSource
{
    // Error parsing type: , name: kArtistBioSection
    // Error parsing type: , name: tappedUrlHandler
    // Error parsing type: , name: linkParser
}

- (CDUnknownBlockType).cxx_destruct;
- (void)linkLabelDidTapLink:(id)arg1;

@end

