//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC4WiMP17MediaQualityProxy : NSObject
{
    // Error parsing type: , name: itemType
    // Error parsing type: , name: soundQuality
    // Error parsing type: , name: videoQuality
    // Error parsing type: , name: codec
}

- (id)init;
- (long long)objCVideoQuality;
- (long long)objCCodec;
- (long long)objCAudioQuality;

@end

