//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCKCastChannel.h"

@class GCKDevice, NSArray, NSData, NSTimer;
@protocol GCKDeviceAuthChannelDelegate;

@interface GCKDeviceAuthChannel : GCKCastChannel
{
    GCKDevice *_device;
    struct __SecTrust *_peerTrust;
    NSArray *_anchorCertArray;
    NSData *_nonce;
    NSTimer *_timer;
    id <GCKDeviceAuthChannelDelegate> _delegate;
}

@property(nonatomic) __weak id <GCKDeviceAuthChannelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didDisconnect;
- (_Bool)verifyDeviceSignature:(id)arg1 deviceKey:(struct __SecKey *)arg2 deviceDigest:(id)arg3;
- (void)didReceiveBinaryMessage:(id)arg1;
- (void)notifyDidAuthenticate:(_Bool)arg1;
- (void)cancelTimer;
- (void)timerDidFire:(id)arg1;
- (void)sendChallengeWithPeerSecTrust:(struct __SecTrust *)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithDevice:(id)arg1;

@end

