//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle, NSLocale, NSString, NSURLSessionDataTask, NSURLSessionDownloadTask;

@interface Lokalise : NSObject
{
    _Bool _didSetup;
    NSString *_apiToken;
    NSString *_projectID;
    NSLocale *_localizationLocale;
    long long _localizationType;
    NSString *_lokaliseFolderPath;
    NSBundle *_localBundle;
    NSBundle *_localeBundle;
    NSBundle *_lokaliseBundle;
    NSBundle *_lokaliseLocaleBundle;
    NSString *_fallbackLocaleIdentifier;
    NSURLSessionDataTask *_checkVersionTask;
    NSURLSessionDownloadTask *_downloadTask;
    NSBundle *_liveEditBundle;
}

+ (id)sharedObject;
@property(retain, nonatomic) NSBundle *liveEditBundle; // @synthesize liveEditBundle=_liveEditBundle;
@property(retain, nonatomic) NSURLSessionDownloadTask *downloadTask; // @synthesize downloadTask=_downloadTask;
@property(retain, nonatomic) NSURLSessionDataTask *checkVersionTask; // @synthesize checkVersionTask=_checkVersionTask;
@property(retain, nonatomic) NSString *fallbackLocaleIdentifier; // @synthesize fallbackLocaleIdentifier=_fallbackLocaleIdentifier;
@property(retain, nonatomic) NSBundle *lokaliseLocaleBundle; // @synthesize lokaliseLocaleBundle=_lokaliseLocaleBundle;
@property(retain, nonatomic) NSBundle *lokaliseBundle; // @synthesize lokaliseBundle=_lokaliseBundle;
@property(retain, nonatomic) NSBundle *localeBundle; // @synthesize localeBundle=_localeBundle;
@property(retain, nonatomic) NSBundle *localBundle; // @synthesize localBundle=_localBundle;
@property(retain, nonatomic) NSString *lokaliseFolderPath; // @synthesize lokaliseFolderPath=_lokaliseFolderPath;
@property(nonatomic) _Bool didSetup; // @synthesize didSetup=_didSetup;
@property(nonatomic) long long localizationType; // @synthesize localizationType=_localizationType;
@property(readonly, nonatomic) NSLocale *localizationLocale; // @synthesize localizationLocale=_localizationLocale;
@property(retain, nonatomic) NSString *projectID; // @synthesize projectID=_projectID;
@property(retain, nonatomic) NSString *apiToken; // @synthesize apiToken=_apiToken;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long lokaliseBundleVersion;
- (void)setLocalizationLocale:(id)arg1 makeDefault:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)informAboutLocalizationUpdate;
- (void)loadLokaliseBundleAtPath:(id)arg1;
- (void)loadLokaliseBundleForLocale:(id)arg1;
- (void)loadLocalBundleForLocale:(id)arg1;
- (void)reloadBundles;
- (id)duplicateFile:(id)arg1 path:(id)arg2;
- (_Bool)unzipFileAtPath:(id)arg1 toDestinationPath:(id)arg2;
- (void)downloadLokaliseBundle:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteLokaliseData:(_Bool)arg1;
- (_Bool)isMainBundleSwizzled;
- (id)lokaliseBundleName;
- (id)deviceUUID;
- (void)deleteLokaliseData;
- (void)dispatchOnMainThread:(CDUnknownBlockType)arg1;
- (void)deswizzleMainBundle;
- (void)swizzleMainBundle;
- (id)availableLocales;
- (void)checkForUpdatesWithCompletion:(CDUnknownBlockType)arg1;
- (id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3;
- (void)setAPIToken:(id)arg1 projectID:(id)arg2;
- (id)init;

@end

