//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (GCKBAdditions)
- (id)gckb_stringWithTrailingComponentsRemoved:(id)arg1;
- (id)gckb_SHA1Hash;
- (id)gckb_base64DecodedData;
- (_Bool)gckb_matchesGlob:(id)arg1;
- (_Bool)gckb_containsRegex:(id)arg1;
- (_Bool)gckb_matchesPattern:(id)arg1;
@end

