//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString, SDLFile;

@interface SDLLifecycleConfiguration : NSObject <NSCopying>
{
    _Bool _tcpDebugMode;
    unsigned short _tcpDebugPort;
    NSString *_tcpDebugIPAddress;
    NSString *_appName;
    NSString *_appId;
    NSString *_resumeHash;
    NSString *_appType;
    NSArray *_additionalAppTypes;
    NSString *_language;
    NSArray *_languagesSupported;
    SDLFile *_appIcon;
    NSString *_shortAppName;
    NSArray *_ttsName;
    NSArray *_voiceRecognitionCommandNames;
}

+ (id)debugConfigurationWithAppName:(id)arg1 appId:(id)arg2 ipAddress:(id)arg3 port:(unsigned short)arg4;
+ (id)defaultConfigurationWithAppName:(id)arg1 appId:(id)arg2;
@property(copy, nonatomic) NSArray *voiceRecognitionCommandNames; // @synthesize voiceRecognitionCommandNames=_voiceRecognitionCommandNames;
@property(copy, nonatomic) NSArray *ttsName; // @synthesize ttsName=_ttsName;
@property(copy, nonatomic) NSString *shortAppName; // @synthesize shortAppName=_shortAppName;
@property(retain, nonatomic) SDLFile *appIcon; // @synthesize appIcon=_appIcon;
@property(retain, nonatomic) NSArray *languagesSupported; // @synthesize languagesSupported=_languagesSupported;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(copy, nonatomic) NSArray *additionalAppTypes; // @synthesize additionalAppTypes=_additionalAppTypes;
@property(retain, nonatomic) NSString *appType; // @synthesize appType=_appType;
@property(copy, nonatomic) NSString *resumeHash; // @synthesize resumeHash=_resumeHash;
@property(readonly, copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(nonatomic) unsigned short tcpDebugPort; // @synthesize tcpDebugPort=_tcpDebugPort;
@property(copy, nonatomic) NSString *tcpDebugIPAddress; // @synthesize tcpDebugIPAddress=_tcpDebugIPAddress;
@property(nonatomic) _Bool tcpDebugMode; // @synthesize tcpDebugMode=_tcpDebugMode;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) _Bool isMedia;
- (id)initDefaultConfigurationWithAppName:(id)arg1 appId:(id)arg2;

@end

