//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableSet, NSString, SwrveRESTClient;

@interface SwrveAssetsManager : NSObject
{
    NSMutableSet *assetsOnDiskSet;
    NSMutableSet *assetsCurrentlyDownloading;
    SwrveRESTClient *restClient;
    NSString *cdnImages;
    NSString *cdnFonts;
    NSString *cacheFolder;
}

+ (id)assetQItemWith:(id)arg1 andDigest:(id)arg2 andIsImage:(_Bool)arg3;
@property(retain, nonatomic) NSString *cacheFolder; // @synthesize cacheFolder;
@property(retain, nonatomic) NSString *cdnFonts; // @synthesize cdnFonts;
@property(retain, nonatomic) NSString *cdnImages; // @synthesize cdnImages;
@property(retain, nonatomic) SwrveRESTClient *restClient; // @synthesize restClient;
- (void).cxx_destruct;
- (id)assetsOnDisk;
- (_Bool)verifySHA:(id)arg1 against:(id)arg2;
- (id)filterExistingFiles:(id)arg1;
- (void)downloadAsset:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)downloadAssets:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)initWithRestClient:(id)arg1 andCacheFolder:(id)arg2;

@end

