//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIButton, UILabel, UIScrollView, UITextView, WMPLoginService, _TtC4WiMP20PlaceHolderTextField;
@protocol WMPLoginServiceDelegate;

@interface WMPNativeSignupModule : UIViewController <UITextFieldDelegate, UITextViewDelegate>
{
    id <WMPLoginServiceDelegate> _delegate;
    UIScrollView *_scrollView;
    _TtC4WiMP20PlaceHolderTextField *_emailTextField;
    _TtC4WiMP20PlaceHolderTextField *_reEmailTextField;
    _TtC4WiMP20PlaceHolderTextField *_passwordTextField;
    UITextView *_termsTextView;
    UILabel *_orLabel;
    UIButton *_signupWithFacebookButton;
    UIButton *_signupWithEmailButton;
    UIActivityIndicatorView *_activityIndicatorView;
    WMPLoginService *_loginService;
}

+ (id)getInstance;
@property(retain, nonatomic) WMPLoginService *loginService; // @synthesize loginService=_loginService;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIButton *signupWithEmailButton; // @synthesize signupWithEmailButton=_signupWithEmailButton;
@property(retain, nonatomic) UIButton *signupWithFacebookButton; // @synthesize signupWithFacebookButton=_signupWithFacebookButton;
@property(retain, nonatomic) UILabel *orLabel; // @synthesize orLabel=_orLabel;
@property(retain, nonatomic) UITextView *termsTextView; // @synthesize termsTextView=_termsTextView;
@property(retain, nonatomic) _TtC4WiMP20PlaceHolderTextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) _TtC4WiMP20PlaceHolderTextField *reEmailTextField; // @synthesize reEmailTextField=_reEmailTextField;
@property(retain, nonatomic) _TtC4WiMP20PlaceHolderTextField *emailTextField; // @synthesize emailTextField=_emailTextField;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <WMPLoginServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setupLocalizableStrings;
- (void)setupViews;
- (void)textFieldDidChange:(id)arg1;
- (void)addTextFieldEventObservers;
- (_Bool)hasAnyErrorsInTextFields;
- (void)errorReEmailClicked:(id)arg1;
- (void)errorEmailClicked:(id)arg1;
- (void)errorPasswordClicked:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3;
- (void)resetSignupButtons;
- (void)addActivityViewToButton:(id)arg1;
- (void)signUpWithEmailAction:(id)arg1;
- (void)signUpWithFacebookAction:(id)arg1;
- (void)didPressCancelButton:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)showNetworkErrorIfPossible:(id)arg1;
- (void)loginWithParsedResult:(id)arg1;
- (void)setupTermsTextView;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

