//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol WMPPlaybackDelegate <NSObject>
- (void)didPressRepeatButton;
- (void)didPressShuffleButton;
- (void)didPressVideoQualitiesButton;
- (void)seekToTime:(double)arg1;
- (void)didPressNextButton;
- (void)didPressBackButton;
- (void)didPressPlayButton;
@end

