//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "WMPModule-Protocol.h"

@class NSDictionary, NSNumber, NSString, UIView, WMPProgressAnimator;
@protocol WMPModuleDelegate;

@interface WMPSearchSuggestion : NSObject <NSCoding, WMPModule>
{
    long long _type;
    NSString *_title;
    NSString *_subTitle;
    NSString *_versionText;
    id _itemId;
    NSNumber *_albumId;
    NSNumber *_isExplicit;
    NSString *_imageResourceId;
    NSString *_imagePath;
}

+ (id)typeStringFromEnum:(long long)arg1;
@property(retain, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
@property(retain, nonatomic) NSString *imageResourceId; // @synthesize imageResourceId=_imageResourceId;
@property(retain, nonatomic) NSNumber *isExplicit; // @synthesize isExplicit=_isExplicit;
@property(retain, nonatomic) NSNumber *albumId; // @synthesize albumId=_albumId;
@property(retain, nonatomic) id itemId; // @synthesize itemId=_itemId;
@property(retain, nonatomic) NSString *versionText; // @synthesize versionText=_versionText;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqualToSuggestion:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)typeAsString;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithType:(long long)arg1 title:(id)arg2 subTitle:(id)arg3 itemId:(id)arg4 albumId:(id)arg5 imageResourceId:(id)arg6;
- (id)init;
- (void)loadThumbnailInView:(id)arg1;

// Remaining properties
@property(retain, nonatomic) WMPProgressAnimator *animator;
@property(nonatomic) _Bool canCollapse;
@property(nonatomic) _Bool contentLoadFinished;
@property(readonly, copy) NSString *debugDescription;
@property(copy, nonatomic) NSDictionary *eventMetadata;
@property(nonatomic) _Bool hasDetails;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *header;
@property(nonatomic) double heightConstraint;
@property(nonatomic) double heightUnits;
@property(nonatomic) double horizontalUnits;
@property(nonatomic) _Bool isFullScreen;
@property(nonatomic) __weak id <WMPModuleDelegate> moduleDelegate;
@property(retain, nonatomic) NSString *moduleTag;
@property(retain, nonatomic) UIView *noConnectionView;
@property(nonatomic) _Bool scrollEnabled;
@property(nonatomic) _Bool sortingEnabled;
@property(readonly) Class superclass;

@end

