//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WMPBaseServiceProvider.h"

@interface WMPTrackServiceProvider : WMPBaseServiceProvider
{
}

- (void)loadRecommendedTracksForTrackUuid:(id)arg1 sortAndRangeParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadTrackExtendedInfoForUuid:(id)arg1 sortAndRangeParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeTrackFromFavorites:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addTrackToFavorites:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadTracksByCategoryIdentifier:(id)arg1 sortAndRangeParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadFavoriteTracksByUserId:(id)arg1 sortAndRangeParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadTopTracksByArtistId:(id)arg1 sortAndRangeParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadTrackByTrackUuid:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadTrackRadioByTrackId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)loadTrackRadioByArtistId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

