//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Napster14ViewController.h"

@class NSString, RHLinearGradientView, UIButton, UILabel, UIView, _TtC7Napster19RHDeferredImageView;

@interface _TtC7Napster26AlarmRingingViewController : _TtC7Napster14ViewController
{
    // Error parsing type: , name: gradientView
    // Error parsing type: , name: timeLabel
    // Error parsing type: , name: trackLabel
    // Error parsing type: , name: artistLabel
    // Error parsing type: , name: resumeButton
    // Error parsing type: , name: snoozeView
    // Error parsing type: , name: snoozeButton
    // Error parsing type: , name: snoozeLabel
    // Error parsing type: , name: dismissButton
    // Error parsing type: , name: dismissLabel
    // Error parsing type: , name: trackView
    // Error parsing type: , name: artwork
    // Error parsing type: , name: snoozedInfoLabel
    // Error parsing type: , name: dependencies
    // Error parsing type: , name: alarm
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 metricsSource:(id)arg3;
@property(nonatomic, readonly) NSString *metricsScreenName;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) __weak UILabel *snoozedInfoLabel; // @synthesize snoozedInfoLabel;
@property(nonatomic) __weak _TtC7Napster19RHDeferredImageView *artwork; // @synthesize artwork;
@property(nonatomic) __weak UIView *trackView; // @synthesize trackView;
@property(nonatomic) __weak UILabel *dismissLabel; // @synthesize dismissLabel;
@property(nonatomic) __weak UIButton *dismissButton; // @synthesize dismissButton;
@property(nonatomic) __weak UILabel *snoozeLabel; // @synthesize snoozeLabel;
@property(nonatomic) __weak UIButton *snoozeButton; // @synthesize snoozeButton;
@property(nonatomic) __weak UIView *snoozeView; // @synthesize snoozeView;
@property(nonatomic) __weak UIButton *resumeButton; // @synthesize resumeButton;
@property(nonatomic) __weak UILabel *artistLabel; // @synthesize artistLabel;
@property(nonatomic) __weak UILabel *trackLabel; // @synthesize trackLabel;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel;
@property(nonatomic) __weak RHLinearGradientView *gradientView; // @synthesize gradientView;

@end

