//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Napster14ViewController.h"

@class NSDictionary, NSString, UICollectionView;

@interface _TtC7Napster19BooksViewController : _TtC7Napster14ViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: dependencies
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: genre
    // Error parsing type: , name: onlyDownloaded
    // Error parsing type: , name: noBookmarksViewController
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: numberOfCellsPerRow
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 metricsSource:(id)arg3;
@property(nonatomic, readonly) NSDictionary *metricsProperties;
@property(nonatomic, readonly) NSString *metricsScreenEvent;
@property(nonatomic, readonly) NSString *metricsScreenName;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) UICollectionView *collectionView; // @synthesize collectionView;

@end

