//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Napster14ViewController.h"

@class UIButton, UICollectionView, UILabel;

@interface _TtC7Napster27HeaderSectionViewController : _TtC7Napster14ViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: headerLabel
    // Error parsing type: , name: seeAllButton
    // Error parsing type: , name: dependencies
    // Error parsing type: , name: genre
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: numberOfCellsPerRow
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 metricsSource:(id)arg3;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) double heightWithoutCollectionView;
@property(nonatomic) __weak UIButton *seeAllButton; // @synthesize seeAllButton;
@property(nonatomic) __weak UILabel *headerLabel; // @synthesize headerLabel;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

