//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Napster14ViewController.h"

@class UIButton, UICollectionView, UILabel, UISearchBar;

@interface _TtC7Napster27AddTagsSearchViewController : _TtC7Napster14ViewController
{
    // Error parsing type: , name: closeAction
    // Error parsing type: , name: closeSubject
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: dependencies
    // Error parsing type: , name: addTagsComponent
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: templateCell
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: searchBar
    // Error parsing type: , name: doneButton
    // Error parsing type: , name: noContentLabel
    // Error parsing type: , name: collectionView
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 metricsSource:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UILabel *noContentLabel; // @synthesize noContentLabel;
@property(nonatomic) __weak UIButton *doneButton; // @synthesize doneButton;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar;

@end

