//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Napster13AppboyService.h"

#import "ABKInAppMessageControllerDelegate-Protocol.h"

@interface _TtC7Napster13AppboyService (Napster) <ABKInAppMessageControllerDelegate>
- (long long)beforeInAppMessageDisplayed:(id)arg1;
@end

