//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC7Napster17ActivityIndicator : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _lock
    // Error parsing type: , name: _variable
    // Error parsing type: , name: _loading
}

@end

