//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UITableView, _TtC7Napster20SettingsSectionEntry;

@protocol _TtP7Napster28SettingsSectionEntryDelegate_
- (long long)indexOfSettingsSection:(_TtC7Napster20SettingsSectionEntry *)arg1;
- (UITableView *)tableViewForSettingsSection:(_TtC7Napster20SettingsSectionEntry *)arg1;
@end

