//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CarIntegrationDataTranslator, ZDSDeferred;

@interface CatalogSearcher : NSObject
{
    CarIntegrationDataTranslator *_dataTranslator;
    ZDSDeferred *_deferredResults;
}

@property(retain) ZDSDeferred *deferredResults; // @synthesize deferredResults=_deferredResults;
@property(retain) CarIntegrationDataTranslator *dataTranslator; // @synthesize dataTranslator=_dataTranslator;
- (void).cxx_destruct;
- (void)searchFor:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

