//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RAPIEntertainmentAppLinkDelegate-Protocol.h"

@class NSMutableArray, NSString, RAPIAlbumsController, RAPIEntertainmentAppLink, RAPIPlayableTwoLineController, RAPIPlayerScreenController, RAPIPlaylistsController, RAPIRadioStationsForGenreController, RAPIStandardMenuController, RAPIStandardOneLineController;
@protocol CarIntegrationDelegate;

@interface RAPIMainController : NSObject <RAPIEntertainmentAppLinkDelegate>
{
    _Bool _isConnected;
    _Bool _id5Mode;
    unsigned long long _rapiPlayerScreenIndex;
    unsigned long long _rapiNowPlayingScreenIndex;
    unsigned long long _rapiStandardMenuScreenIndex;
    unsigned long long _rapiSearchScreenIndex;
    unsigned long long _rapiPlayableTwoLineScreenIndex;
    unsigned long long _rapiAlbumsControllerScreenIndex;
    unsigned long long _rapiPlaylistsScreenIndex;
    unsigned long long _rapiStandardOneLineScreenIndex;
    unsigned long long _rapiRadioScreenIndex;
    unsigned long long _rapiRadioStationsForGenreScreenIndex;
    id <CarIntegrationDelegate> _carIntegrationDelegate;
    long long _carBrand;
    NSString *_carLanguage;
    NSMutableArray *_screenTable;
    RAPIEntertainmentAppLink *_rapiEntertainmentAppLink;
    RAPIPlayerScreenController *_playerScreenController;
    RAPIStandardMenuController *_standardMenuController;
    RAPIPlayableTwoLineController *_playableTwoLineController;
    RAPIPlaylistsController *_playlistsController;
    RAPIStandardOneLineController *_standardOneLineController;
    RAPIAlbumsController *_albumsController;
    RAPIRadioStationsForGenreController *_radioStationsForGenreController;
}

@property(retain, nonatomic) RAPIRadioStationsForGenreController *radioStationsForGenreController; // @synthesize radioStationsForGenreController=_radioStationsForGenreController;
@property(retain, nonatomic) RAPIAlbumsController *albumsController; // @synthesize albumsController=_albumsController;
@property(retain, nonatomic) RAPIStandardOneLineController *standardOneLineController; // @synthesize standardOneLineController=_standardOneLineController;
@property(retain, nonatomic) RAPIPlaylistsController *playlistsController; // @synthesize playlistsController=_playlistsController;
@property(retain, nonatomic) RAPIPlayableTwoLineController *playableTwoLineController; // @synthesize playableTwoLineController=_playableTwoLineController;
@property(retain, nonatomic) RAPIStandardMenuController *standardMenuController; // @synthesize standardMenuController=_standardMenuController;
@property(retain, nonatomic) RAPIPlayerScreenController *playerScreenController; // @synthesize playerScreenController=_playerScreenController;
@property(nonatomic) _Bool id5Mode; // @synthesize id5Mode=_id5Mode;
@property(retain) RAPIEntertainmentAppLink *rapiEntertainmentAppLink; // @synthesize rapiEntertainmentAppLink=_rapiEntertainmentAppLink;
@property(retain) NSMutableArray *screenTable; // @synthesize screenTable=_screenTable;
@property(retain, nonatomic) NSString *carLanguage; // @synthesize carLanguage=_carLanguage;
@property(nonatomic) _Bool isConnected; // @synthesize isConnected=_isConnected;
@property(nonatomic) long long carBrand; // @synthesize carBrand=_carBrand;
@property __weak id <CarIntegrationDelegate> carIntegrationDelegate; // @synthesize carIntegrationDelegate=_carIntegrationDelegate;
@property unsigned long long rapiRadioStationsForGenreScreenIndex; // @synthesize rapiRadioStationsForGenreScreenIndex=_rapiRadioStationsForGenreScreenIndex;
@property unsigned long long rapiRadioScreenIndex; // @synthesize rapiRadioScreenIndex=_rapiRadioScreenIndex;
@property unsigned long long rapiStandardOneLineScreenIndex; // @synthesize rapiStandardOneLineScreenIndex=_rapiStandardOneLineScreenIndex;
@property unsigned long long rapiPlaylistsScreenIndex; // @synthesize rapiPlaylistsScreenIndex=_rapiPlaylistsScreenIndex;
@property unsigned long long rapiAlbumsControllerScreenIndex; // @synthesize rapiAlbumsControllerScreenIndex=_rapiAlbumsControllerScreenIndex;
@property unsigned long long rapiPlayableTwoLineScreenIndex; // @synthesize rapiPlayableTwoLineScreenIndex=_rapiPlayableTwoLineScreenIndex;
@property unsigned long long rapiSearchScreenIndex; // @synthesize rapiSearchScreenIndex=_rapiSearchScreenIndex;
@property unsigned long long rapiStandardMenuScreenIndex; // @synthesize rapiStandardMenuScreenIndex=_rapiStandardMenuScreenIndex;
@property unsigned long long rapiNowPlayingScreenIndex; // @synthesize rapiNowPlayingScreenIndex=_rapiNowPlayingScreenIndex;
@property unsigned long long rapiPlayerScreenIndex; // @synthesize rapiPlayerScreenIndex=_rapiPlayerScreenIndex;
- (void).cxx_destruct;
- (void)displayMessage:(id)arg1;
- (void)refreshToolbarButtons;
- (void)prepareAlbumsControllerForArtist:(id)arg1 mode:(unsigned long long)arg2;
- (void)prepareStandardOneLineControllerForMode:(unsigned long long)arg1;
- (void)preparePlaylistsControllerForMode:(unsigned long long)arg1;
- (void)preparePlayableTwoLineControllerForMode:(unsigned long long)arg1;
- (void)prepareStandardMenuControllerForMode:(unsigned long long)arg1;
- (void)prepareRadioStationsControllerForGenre:(id)arg1;
@property(readonly, nonatomic) _Bool isHMI4;
- (void)onCarLanguageChanged:(id)arg1;
- (id)getDefaultLabel:(int)arg1;
@property(readonly, nonatomic) _Bool isPlayingRadio;
- (_Bool)canSkipPrev;
- (_Bool)canSkipNext;
- (void)onBeginSeekForward;
- (void)onEndSeek;
- (void)onBeginSeekBackward;
- (void)onSkipPrev;
- (void)onSkipNext;
- (void)onPausePlayback;
- (void)onStartPlayback;
- (long long)getTotalTrackTime;
- (long long)getCurrentTrackTime;
- (float)getCurrentTrackProgress;
- (void)onDisconnectedFromCar;
- (void)onConnectedToCar:(id)arg1;
- (void)invalidateAllScreens;
- (unsigned long long)addScreen:(id)arg1;
- (id)initWithCarIntegrationDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

