//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PSTCollectionViewCell.h"

@class RHAlbumMO, UIImageView, UILabel, ZDSPromise;

@interface RHAlbumCollectionViewCell : PSTCollectionViewCell
{
    struct CGSize imageSize;
    int _contentStyle;
    RHAlbumMO *_album;
    UILabel *_albumLabel;
    UILabel *_albumTypeLabel;
    UILabel *_artistLabel;
    UILabel *_ordinalLabel;
    UIImageView *_albumImageView;
    ZDSPromise *_imagePromise;
    double _ordinalToAlbumSpacing;
    double _albumToAlbumTypeSpacing;
    double _rightMargin;
}

@property(nonatomic) double rightMargin; // @synthesize rightMargin=_rightMargin;
@property(nonatomic) double albumToAlbumTypeSpacing; // @synthesize albumToAlbumTypeSpacing=_albumToAlbumTypeSpacing;
@property(nonatomic) double ordinalToAlbumSpacing; // @synthesize ordinalToAlbumSpacing=_ordinalToAlbumSpacing;
@property(retain, nonatomic) ZDSPromise *imagePromise; // @synthesize imagePromise=_imagePromise;
@property(nonatomic) __weak UIImageView *albumImageView; // @synthesize albumImageView=_albumImageView;
@property(nonatomic) __weak UILabel *ordinalLabel; // @synthesize ordinalLabel=_ordinalLabel;
@property(nonatomic) __weak UILabel *artistLabel; // @synthesize artistLabel=_artistLabel;
@property(nonatomic) __weak UILabel *albumTypeLabel; // @synthesize albumTypeLabel=_albumTypeLabel;
@property(nonatomic) __weak UILabel *albumLabel; // @synthesize albumLabel=_albumLabel;
@property(nonatomic) int contentStyle; // @synthesize contentStyle=_contentStyle;
@property(retain, nonatomic) RHAlbumMO *album; // @synthesize album=_album;
- (void).cxx_destruct;
- (id)imageProvider;
- (id)reachabilityService;
- (void)handleNetworkStatusChangedNotification:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)loadImage;
- (void)configureCellWithAlbumHighlight:(id)arg1;
- (void)configureCellWithAlbum:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

@end

