//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZDSDataMapFilter.h"

@interface RHDataMapFilter : ZDSDataMapFilter
{
}

+ (id)preparedFilter;
- (id)stripHTMLFromString:(id)arg1;
- (id)abbreviationFromString:(id)arg1;
- (id)dateFromString:(id)arg1;
- (id)dateFromDictionary:(id)arg1;

@end

