//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RHViewController.h"

#import "NSFetchedResultsControllerDelegate-Protocol.h"
#import "RHFilterChooserViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSFetchedResultsController, NSString, RHDataController, RHEditorialTableCell, RHGenreMO, RHLoadingOverlay, RHNoDataOverlay, UIButton, UILabel, UITableView, UIView, ZDSPromise;

@interface RHEditorialsViewController : RHViewController <NSFetchedResultsControllerDelegate, RHFilterChooserViewControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    _Bool _showsFilter;
    RHGenreMO *_genre;
    unsigned long long _selectedFilter;
    RHDataController *_dataController;
    NSFetchedResultsController *_fetchedResultsController;
    ZDSPromise *_loadingPromise;
    UILabel *_titleLabel;
    UIButton *_filterButton;
    UIView *_filterBackground;
    UIView *_contentView;
    UITableView *_tableView;
    UIView *_topContainer;
    RHEditorialTableCell *_offscreenCell;
    RHLoadingOverlay *_loadingOverlay;
    RHNoDataOverlay *_noDataOverlay;
    NSArray *_fetchedObjects;
}

@property(nonatomic) _Bool showsFilter; // @synthesize showsFilter=_showsFilter;
@property(retain, nonatomic) NSArray *fetchedObjects; // @synthesize fetchedObjects=_fetchedObjects;
@property(nonatomic) __weak RHNoDataOverlay *noDataOverlay; // @synthesize noDataOverlay=_noDataOverlay;
@property(nonatomic) __weak RHLoadingOverlay *loadingOverlay; // @synthesize loadingOverlay=_loadingOverlay;
@property(retain, nonatomic) RHEditorialTableCell *offscreenCell; // @synthesize offscreenCell=_offscreenCell;
@property(nonatomic) __weak UIView *topContainer; // @synthesize topContainer=_topContainer;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *filterBackground; // @synthesize filterBackground=_filterBackground;
@property(nonatomic) __weak UIButton *filterButton; // @synthesize filterButton=_filterButton;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) ZDSPromise *loadingPromise; // @synthesize loadingPromise=_loadingPromise;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
@property(retain, nonatomic) RHDataController *dataController; // @synthesize dataController=_dataController;
@property(nonatomic) unsigned long long selectedFilter; // @synthesize selectedFilter=_selectedFilter;
@property(retain, nonatomic) RHGenreMO *genre; // @synthesize genre=_genre;
- (void).cxx_destruct;
- (id)metricsScreenEvent;
- (id)metricsScreenName;
- (id)reachabilityService;
- (id)dependencies;
- (id)targetActionWithSelector:(SEL)arg1 param:(id)arg2;
- (id)noDataMessage;
- (void)showEditorial:(id)arg1;
- (void)showChooserForFilters:(id)arg1;
- (void)configureFilterButton;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (void)refreshData;
- (id)sortEditorialsByCategory:(id)arg1;
- (void)configureFetchedResultsController;
- (void)indicateAvailableData:(_Bool)arg1 loading:(_Bool)arg2;
- (void)updateInterfaceForAvailableData;
- (void)filterChooser:(id)arg1 didSelectFilter:(id)arg2;
- (void)playViewTappedForEditorial:(id)arg1;
- (void)filterButtonTapped:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)networkStatusDidChange:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (double)tableView:(id)arg1 heightForCellAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollToTop;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewUnloading;
- (void)viewDidLoad;
- (id)initWithDataController:(id)arg1 genre:(id)arg2 showsFilter:(_Bool)arg3;
- (id)initWithDataController:(id)arg1 genre:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

