//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class MeqEarPrint, NSString;

@interface RHEvenEarprintModel : NSObject <NSCoding>
{
    MeqEarPrint *_earprint;
    NSString *_id;
}

+ (id)newEarprintModel:(id)arg1;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
@property(retain, nonatomic) MeqEarPrint *earprint; // @synthesize earprint=_earprint;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

