//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSAttributedString, UILabel;

@interface RHHorizontalBannerView : UIView
{
    _Bool _reset;
    NSAttributedString *_text;
    NSAttributedString *_highlightedText;
    CDUnknownBlockType _tapAction;
    long long _textAlignment;
    double _scrollSpeed;
    UILabel *_firstLabel;
    UILabel *_secondLabel;
    struct UIEdgeInsets _touchInsets;
}

@property(nonatomic) _Bool reset; // @synthesize reset=_reset;
@property(retain, nonatomic) UILabel *secondLabel; // @synthesize secondLabel=_secondLabel;
@property(retain, nonatomic) UILabel *firstLabel; // @synthesize firstLabel=_firstLabel;
@property(nonatomic) double scrollSpeed; // @synthesize scrollSpeed=_scrollSpeed;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(copy, nonatomic) CDUnknownBlockType tapAction; // @synthesize tapAction=_tapAction;
@property(nonatomic) struct UIEdgeInsets touchInsets; // @synthesize touchInsets=_touchInsets;
@property(copy, nonatomic) NSAttributedString *highlightedText; // @synthesize highlightedText=_highlightedText;
@property(copy, nonatomic) NSAttributedString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)rectValidForTouches:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)updateTextWithHighlight:(_Bool)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)animateFromCurrentPosition:(double)arg1;
- (void)layoutSubviews;
- (void)stopScrolling;
- (_Bool)shouldNowScroll:(double *)arg1;
- (struct CGRect)positionForIndex:(long long)arg1 andWidth:(double)arg2;
- (void)setAccessibilityIdentifier:(id)arg1;
- (void)configureDefaultValues;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

