//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RHModePermissionsController.h"

@interface RHKidsModePermissionsController : RHModePermissionsController
{
}

- (_Bool)shouldShowFullScreenPlayerForPreviousState:(long long)arg1 presentState:(long long)arg2 viewMode:(long long)arg3;
- (_Bool)shouldShowOmnibarUpsell;
- (_Bool)shouldRevealFlyoutMenu;
- (_Bool)shouldHandleDeepLink:(id)arg1;
- (_Bool)ignorePushNotifications;
- (_Bool)isKidsModeEnabled;
- (id)menuItemsIPhone;

@end

