//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RHObserver.h"

#import "NSFetchedResultsControllerDelegate-Protocol.h"

@class NSArray, NSFetchedResultsController, NSString, ZDSDeferred;

@interface RHModelObserver : RHObserver <NSFetchedResultsControllerDelegate>
{
    ZDSDeferred *_refresh;
    CDUnknownBlockType _modelChanged;
    NSFetchedResultsController *_frc;
    NSArray *_oldSections;
    NSArray *_oldModels;
    CDUnknownBlockType _modelSelector;
}

+ (id)empty;
@property(copy, nonatomic) CDUnknownBlockType modelSelector; // @synthesize modelSelector=_modelSelector;
@property(retain, nonatomic) NSArray *oldModels; // @synthesize oldModels=_oldModels;
@property(retain, nonatomic) NSArray *oldSections; // @synthesize oldSections=_oldSections;
@property(retain, nonatomic) NSFetchedResultsController *frc; // @synthesize frc=_frc;
@property(copy, nonatomic) CDUnknownBlockType modelChanged; // @synthesize modelChanged=_modelChanged;
@property(retain, nonatomic) ZDSDeferred *refresh; // @synthesize refresh=_refresh;
- (void).cxx_destruct;
- (id)map:(CDUnknownBlockType)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)dispatchNotification;
- (void)controllerWillChangeContent:(id)arg1;
- (void)dealloc;
- (id)initWithFrc:(id)arg1 refreshDeferred:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

