//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIBarButtonItem.h>

@class UIButton, UIImage, ZDSPromise;

@interface RHNowPlayingBarButtonItem : UIBarButtonItem
{
    ZDSPromise *_imagePromise;
    UIImage *_currentArtwork;
    UIButton *_button;
}

@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UIImage *currentArtwork; // @synthesize currentArtwork=_currentArtwork;
@property(retain, nonatomic) ZDSPromise *imagePromise; // @synthesize imagePromise=_imagePromise;
- (void).cxx_destruct;
- (id)imageProvider;
- (id)appDelegate;
- (void)dealloc;
- (void)imageForTrack:(id)arg1;
- (void)trackChanged:(id)arg1;
- (id)init;

@end

