//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class RHFindFriendsViewModel, UILabel;

@interface RHNoRhapsodyFriendsView : UIView
{
    RHFindFriendsViewModel *_viewModel;
    UILabel *_noResultsLabel;
}

+ (id)newWithViewModel:(id)arg1;
@property(nonatomic) __weak UILabel *noResultsLabel; // @synthesize noResultsLabel=_noResultsLabel;
@property(retain, nonatomic) RHFindFriendsViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)configureKVO;
- (void)awakeFromNib;

@end

