//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface RHPartnerReferal : NSObject
{
    NSDate *_referalDate;
    NSString *_referedPartner;
    NSString *_campaign;
}

@property(copy, nonatomic) NSString *campaign; // @synthesize campaign=_campaign;
@property(copy, nonatomic) NSString *referedPartner; // @synthesize referedPartner=_referedPartner;
@property(copy, nonatomic) NSDate *referalDate; // @synthesize referalDate=_referalDate;
- (void).cxx_destruct;
- (id)initWithReferalDate:(id)arg1 referedPartner:(id)arg2 campaign:(id)arg3;

@end

