//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_RHProfileArtistMO.h"

@interface RHProfileArtistMO : _RHProfileArtistMO
{
}

+ (id)processChartsWithPlayCounts:(id)arg1 tag:(id)arg2 artists:(id)arg3 type:(unsigned long long)arg4 range:(unsigned long long)arg5 context:(id)arg6;

@end

