//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Deezer23StackableViewController.h"

@class UIActivityIndicatorView, UIButton, UITextField;

@interface _TtC6Deezer37MSISDNEmailDissociationViewController : _TtC6Deezer23StackableViewController
{
    // Error parsing type: , name: signInSpinner
    // Error parsing type: , name: signIn
    // Error parsing type: , name: email
    // Error parsing type: , name: password
    // Error parsing type: , name: passwordConfirmation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)login:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UITextField *passwordConfirmation; // @synthesize passwordConfirmation;
@property(nonatomic) __weak UITextField *password; // @synthesize password;
@property(nonatomic) __weak UITextField *email; // @synthesize email;
@property(nonatomic) __weak UIButton *signIn; // @synthesize signIn;
@property(nonatomic) __weak UIActivityIndicatorView *signInSpinner; // @synthesize signInSpinner;

@end

