//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Deezer30BBA56C1C64FAD9624C572F7D023653 : NSObject
{
}

+ (void)c57d38b15347c1bb508f4e4dff55a0:(id)arg1;
+ (_Bool)e98723db6cda01f713a13e031d1ebe:(id)arg1 error:(id *)arg2;
- (id)init;

@end

