//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class DeezerInterstitialTrack, UIButton, UILabel, _TtC6Deezer19DZRAudioAdCoverView, _TtC6Deezer21DZRCircleProgressView;

@interface _TtC6Deezer24DZRAudioAdViewController : UIViewController
{
    // Error parsing type: , name: progressView
    // Error parsing type: , name: whyAdsButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: elapsedTimeLabel
    // Error parsing type: , name: playButton
    // Error parsing type: , name: pageTitleLabel
    // Error parsing type: , name: explanationCaptionLabel
    // Error parsing type: , name: coverView
    // Error parsing type: , name: touchGesture
    // Error parsing type: , name: shouldDismiss
    // Error parsing type: , name: coverScaleEffect
    // Error parsing type: , name: track
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (void)handleTap;
- (void)whyAdsPressed:(id)arg1;
- (void)pausePressed:(id)arg1;
- (void)updateControlButton;
- (void)trackDidProgressWithNotification:(id)arg1;
- (void)trackDidFinishWithNotification:(id)arg1;
- (void)observe;
- (void)dismiss;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic, retain) DeezerInterstitialTrack *track; // @synthesize track;
@property(nonatomic) __weak _TtC6Deezer19DZRAudioAdCoverView *coverView; // @synthesize coverView;
@property(nonatomic) __weak UILabel *explanationCaptionLabel; // @synthesize explanationCaptionLabel;
@property(nonatomic) __weak UILabel *pageTitleLabel; // @synthesize pageTitleLabel;
@property(nonatomic) __weak UIButton *playButton; // @synthesize playButton;
@property(nonatomic) __weak UILabel *elapsedTimeLabel; // @synthesize elapsedTimeLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIButton *whyAdsButton; // @synthesize whyAdsButton;
@property(nonatomic) __weak _TtC6Deezer21DZRCircleProgressView *progressView; // @synthesize progressView;

@end

