//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPageViewController.h>

@interface _TtC6Deezer18WhatsNewController : UIPageViewController
{
    // Error parsing type: , name: config
    // Error parsing type: , name: pages
    // Error parsing type: , name: currentIndex
    // Error parsing type: , name: targetIndex
    // Error parsing type: , name: controlBar.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)goNext;
- (void)done;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithTransitionStyle:(long long)arg1 navigationOrientation:(long long)arg2 options:(id)arg3;
- (id)initWithFile:(id)arg1 error:(id *)arg2;
- (id)initWithData:(id)arg1 error:(id *)arg2;

@end

