//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DZRAudioMixing-Protocol.h"

@class AVAudioTime, AudioOutputChannel, NSString;
@protocol OS_dispatch_queue;

@interface DZRAudioMixingController : NSObject <DZRAudioMixing>
{
    float _level;
    float _holdLevel;
    float _idleLevel;
    unsigned long long _stage;
    double _attackDuration;
    double _releaseDuration;
    NSString *_label;
    AudioOutputChannel *_audioChannel;
    unsigned long long _pendingStage;
    double _sampleRate;
    AVAudioTime *_updateStartAudioTime;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)invertedEnvelopeWithAudioChannel:(id)arg1;
+ (id)envelopeWithAudioChannel:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) AVAudioTime *updateStartAudioTime; // @synthesize updateStartAudioTime=_updateStartAudioTime;
@property(nonatomic) float idleLevel; // @synthesize idleLevel=_idleLevel;
@property(nonatomic) float holdLevel; // @synthesize holdLevel=_holdLevel;
@property(nonatomic) float level; // @synthesize level=_level;
@property(nonatomic) double sampleRate; // @synthesize sampleRate=_sampleRate;
@property(nonatomic) unsigned long long pendingStage; // @synthesize pendingStage=_pendingStage;
@property(nonatomic) __weak AudioOutputChannel *audioChannel; // @synthesize audioChannel=_audioChannel;
@property(retain) NSString *label; // @synthesize label=_label;
@property(nonatomic) double attackDuration; // @synthesize attackDuration=_attackDuration;
- (void).cxx_destruct;
- (void)updateAudioMixingVolume;
- (_Bool)isUpdating;
- (void)stopUpdating;
- (void)startUpdating;
- (unsigned long long)updateStage;
- (unsigned long long)applyEnvelopeToBufferList:(struct AudioBufferList *)arg1 numberOfFrames:(unsigned int)arg2;
- (unsigned long long)startRelease;
- (unsigned long long)startAttack;
@property(nonatomic) double releaseDuration; // @synthesize releaseDuration=_releaseDuration;
- (void)skipAttack;
- (void)reset;
@property(nonatomic) unsigned long long stage; // @synthesize stage=_stage;
- (id)initWithAudioChannel:(id)arg1;

@end

