//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DZRBannerAdView, NSError;

@protocol DZRBannerAdViewDelegate <NSObject>
- (void)bannerAdView:(DZRBannerAdView *)arg1 didFailToLoadWithError:(NSError *)arg2;
- (void)bannerAdViewDidLoad:(DZRBannerAdView *)arg1;
@end

