//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class DZRContextMenuViewController, DeezerPlaylist, NSLayoutConstraint, PlayerControllerListeningContext, UIActivityViewController, UILabel, UINavigationController, UIView, _TtC6Deezer16IllustrationView;
@protocol DZRContextMenuDelegate, DZRQueueableCollection;

@interface DZRContextMenuViewContainer : UIViewController
{
    _Bool _showAddToPlaylist;
    _Bool _creatingPlaylist;
    id <DZRContextMenuDelegate> _delegate;
    long long _contextMenuType;
    id _contextMenuContent;
    id <DZRQueueableCollection> _contextMenuTrackContainer;
    DeezerPlaylist *_parentPlaylist;
    _TtC6Deezer16IllustrationView *_illustrationView;
    UINavigationController *_contextMenuNavigationController;
    UIActivityViewController *_activityViewController;
    PlayerControllerListeningContext *_listeningContext;
    UIView *_contextMenuView;
    UIView *_contextView;
    UILabel *_contextTitleLabel;
    UILabel *_contextSubtitle1Label;
    UILabel *_contextSubtitle2Label;
    UIView *_actionsView;
    NSLayoutConstraint *_actionsViewHeightConstraint;
    NSLayoutConstraint *_actionsViewTopConstraint;
    NSLayoutConstraint *_contextMenuViewHeightConstraint;
    NSLayoutConstraint *_contextMenuTopConstraint;
    NSLayoutConstraint *_contextMenuBottomConstraint;
    NSLayoutConstraint *_titleLabelBottomAlignmentConstraint;
    NSLayoutConstraint *_titleLabelCenterAlignmentConstraint;
    DZRContextMenuViewController *_contextMenuViewController;
}

+ (void)presentContextMenuForItem:(id)arg1 withType:(long long)arg2;
@property(nonatomic) _Bool creatingPlaylist; // @synthesize creatingPlaylist=_creatingPlaylist;
@property(retain, nonatomic) DZRContextMenuViewController *contextMenuViewController; // @synthesize contextMenuViewController=_contextMenuViewController;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelCenterAlignmentConstraint; // @synthesize titleLabelCenterAlignmentConstraint=_titleLabelCenterAlignmentConstraint;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelBottomAlignmentConstraint; // @synthesize titleLabelBottomAlignmentConstraint=_titleLabelBottomAlignmentConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contextMenuBottomConstraint; // @synthesize contextMenuBottomConstraint=_contextMenuBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contextMenuTopConstraint; // @synthesize contextMenuTopConstraint=_contextMenuTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *contextMenuViewHeightConstraint; // @synthesize contextMenuViewHeightConstraint=_contextMenuViewHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *actionsViewTopConstraint; // @synthesize actionsViewTopConstraint=_actionsViewTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *actionsViewHeightConstraint; // @synthesize actionsViewHeightConstraint=_actionsViewHeightConstraint;
@property(retain, nonatomic) UIView *actionsView; // @synthesize actionsView=_actionsView;
@property(retain, nonatomic) UILabel *contextSubtitle2Label; // @synthesize contextSubtitle2Label=_contextSubtitle2Label;
@property(retain, nonatomic) UILabel *contextSubtitle1Label; // @synthesize contextSubtitle1Label=_contextSubtitle1Label;
@property(retain, nonatomic) UILabel *contextTitleLabel; // @synthesize contextTitleLabel=_contextTitleLabel;
@property(retain, nonatomic) UIView *contextView; // @synthesize contextView=_contextView;
@property(retain, nonatomic) UIView *contextMenuView; // @synthesize contextMenuView=_contextMenuView;
@property(retain, nonatomic) PlayerControllerListeningContext *listeningContext; // @synthesize listeningContext=_listeningContext;
@property(retain, nonatomic) UIActivityViewController *activityViewController; // @synthesize activityViewController=_activityViewController;
@property(retain, nonatomic) UINavigationController *contextMenuNavigationController; // @synthesize contextMenuNavigationController=_contextMenuNavigationController;
@property(retain, nonatomic) _TtC6Deezer16IllustrationView *illustrationView; // @synthesize illustrationView=_illustrationView;
@property(retain, nonatomic) DeezerPlaylist *parentPlaylist; // @synthesize parentPlaylist=_parentPlaylist;
@property(retain, nonatomic) id <DZRQueueableCollection> contextMenuTrackContainer; // @synthesize contextMenuTrackContainer=_contextMenuTrackContainer;
@property(retain, nonatomic) id contextMenuContent; // @synthesize contextMenuContent=_contextMenuContent;
@property(nonatomic) long long contextMenuType; // @synthesize contextMenuType=_contextMenuType;
@property(nonatomic) __weak id <DZRContextMenuDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)keyboardWillShow:(id)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)closeContextMenuAnimated:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)closeContextMenuWithCompletion:(CDUnknownBlockType)arg1;
- (void)closeContextMenu:(id)arg1;
- (void)updateActionsTopWhenCreatingPlaylist:(_Bool)arg1;
- (void)updateActionsViewHeight:(double)arg1 animated:(_Bool)arg2;
- (void)presentAddToPlaylistContext;
- (void)presentContextMenu;
- (void)applicationWillResignActive:(id)arg1;
- (void)configureMenuWithSampledCollection:(id)arg1;
- (void)configureMenuWithLiveRadio:(id)arg1;
- (void)configureMenuWithMix:(id)arg1;
- (void)configureMenuWithWebApplication:(id)arg1;
- (void)configureMenuWithArtist:(id)arg1;
- (void)configureMenuWithSmartTracklist:(id)arg1;
- (void)configureMenuWithPlaylist:(id)arg1;
- (void)configureMenuWithTalkEpisode:(id)arg1;
- (void)configureMenuWithTalkShow:(id)arg1;
- (void)configureMenuWithAudiobook:(id)arg1;
- (void)configureMenuWithAlbum:(id)arg1;
- (void)configureMenuWithTrack:(id)arg1;
- (void)_configureMenuTitleForMaxNumberOfLines:(unsigned long long)arg1 andCenter:(_Bool)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (double)maxActionAreaHeightForScreen;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

