//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DZRSmartCachedPlayablesRepository-Protocol.h"

@class DZRFisherYatesShuffler, NSCache, NSString, YapDatabase, YapDatabaseConnection;

@interface DZRDownloadableIndexer : NSObject <DZRSmartCachedPlayablesRepository>
{
    NSString *_ownerID;
    NSString *_directoryPath;
    NSString *_currentIndexPath;
    YapDatabase *_yapDatabase;
    YapDatabaseConnection *_yapConnection;
    NSCache *_objectsCache;
    DZRFisherYatesShuffler *_shuffler;
}

@property(retain, nonatomic) DZRFisherYatesShuffler *shuffler; // @synthesize shuffler=_shuffler;
@property(retain, nonatomic) NSCache *objectsCache; // @synthesize objectsCache=_objectsCache;
@property(retain, nonatomic) YapDatabaseConnection *yapConnection; // @synthesize yapConnection=_yapConnection;
@property(retain, nonatomic) YapDatabase *yapDatabase; // @synthesize yapDatabase=_yapDatabase;
@property(retain, nonatomic) NSString *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(retain, nonatomic) NSString *directoryPath; // @synthesize directoryPath=_directoryPath;
@property(retain, nonatomic) NSString *ownerID; // @synthesize ownerID=_ownerID;
- (void).cxx_destruct;
- (void)clearSmartCachedPlayables;
- (id)bestQualityDownloadableForPlayable:(id)arg1 inStorage:(id)arg2;
- (_Bool)hasSmartCachedPlayable:(id)arg1;
- (void)enumerateDownloadableUrlForPlayable:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)allSmartCachedPlayables;
- (void)removeSmartCachedPlayableForKey:(id)arg1;
- (void)addSmartCachedPlayable:(id)arg1 forKey:(id)arg2;
- (_Bool)synchronizedObjectContainsPlayable:(id)arg1 transaction:(id)arg2;
- (id)getRandomSelectionOfDownloadedTracks:(unsigned long long)arg1;
- (id)indexedPlayableIDsAmongPlayables:(id)arg1 forCollectionWithID:(id)arg2;
- (void)removeRelationForDownloadable:(id)arg1 withCollectionID:(id)arg2;
- (void)addRelationForDownloadable:(id)arg1 withCollectionID:(id)arg2;
- (void)fixRelationForDownloadableOfPlayable:(id)arg1 forCollectionWithID:(id)arg2;
- (_Bool)hasDownloadable:(id)arg1 forCollectionWithID:(id)arg2;
- (long long)numberOfDownloadablesForCollectionWithID:(id)arg1;
- (_Bool)canProvideRelationsToDownloadablesForCollectionWithID:(id)arg1;
- (void)removeAllDownloadablesForPlayable:(id)arg1;
- (void)removeDownloadable:(id)arg1;
- (id)indexedDownloadableForPlayable:(id)arg1;
- (id)playablesWithIndexedDownloadablesAmong:(id)arg1;
- (void)addDownloadable:(id)arg1;
- (void)readAndWriteToIndex:(CDUnknownBlockType)arg1;
- (void)readFromIndex:(CDUnknownBlockType)arg1;
- (void)dropIndex;
- (void)closeIndex;
- (void)_openIndex;
- (void)dealloc;
- (id)initWithOwnerID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

