//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;
@protocol DZRDynamicPageActionDelegate;

@protocol DZRDynamicPageAction <NSObject>
- (void)performAction;
- (id <DZRDynamicPageActionDelegate>)delegate;
- (void)setDelegate:(id <DZRDynamicPageActionDelegate>)arg1;
- (NSDictionary *)options;
- (NSString *)name;
- (NSString *)kind;
@end

