//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DZRDynamicPageMastheadContentView.h"

@class DZFlatButton, UILabel, UIView, _TtC6Deezer16IllustrationView;
@protocol DZRDynamicPageItem, DZRDynamicPageSection;

@interface DZRDynamicPageMastheadArtistContentView : DZRDynamicPageMastheadContentView
{
    _TtC6Deezer16IllustrationView *_medallionView;
    UIView *_labelsContainer;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    DZFlatButton *_navigationButton;
    id <DZRDynamicPageSection> _section;
    id <DZRDynamicPageItem> _item;
}

@property(retain, nonatomic) id <DZRDynamicPageItem> item; // @synthesize item=_item;
@property(retain, nonatomic) id <DZRDynamicPageSection> section; // @synthesize section=_section;
@property(retain, nonatomic) DZFlatButton *navigationButton; // @synthesize navigationButton=_navigationButton;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *labelsContainer; // @synthesize labelsContainer=_labelsContainer;
@property(retain, nonatomic) _TtC6Deezer16IllustrationView *medallionView; // @synthesize medallionView=_medallionView;
- (void).cxx_destruct;
- (void)navigationButtonTapped;
- (void)layoutSubviews;
- (id)nonEmptyLabels;
- (id)allLabels;
- (void)populateWithSection:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

