//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DeezerBrowsable-Protocol.h"

@class DZRPeekAndPopViewController, NSString;

@protocol DZRItemPeekable <DeezerBrowsable>
- (long long)illustratonDisplayMode;
- (NSString *)detailLabelString;
- (void)goToRelatedViewController;
- (DZRPeekAndPopViewController *)peekViewControllerWithFrame:(struct CGRect)arg1;
@end

