//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DZRLyricsDataManager, NSString;

@protocol DZRLyricsDataManagerDelegate <NSObject>
- (void)lyricsDataManager:(DZRLyricsDataManager *)arg1 didChangeLyricState:(long long)arg2 forLyricsWithDeezerID:(NSString *)arg3;
@end

