//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DZRDataProvider;

@interface DZROfferAccessService : NSObject
{
    DZRDataProvider *_dataProvider;
}

@property(retain, nonatomic) DZRDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;
- (id)getAccessStrategyForOfferId:(id)arg1 fromOrigin:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithDataProvider:(id)arg1;
- (id)init;

@end

