//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (DZRDataProviderAdditions)
+ (id)dzrDataProviderErrorCurrentUserIsNil;
+ (id)dzrDataProviderErrorParsing;
+ (id)dzrDataProviderErrorOfflineMode;
+ (id)dzrDataProviderErrorCacheInvalidatedForKey:(id)arg1 error:(id)arg2;
+ (id)dzrDataProviderErrorCacheExpiredForKey:(id)arg1 lastModified:(id)arg2 freshness:(double)arg3;
+ (id)dzrDataProviderErrorCacheMissForKey:(id)arg1;
- (_Bool)dzrIsDataProviderErrorCurrentUserIsNil;
- (_Bool)dzrIsDataProviderErrorParsing;
- (_Bool)dzrIsDZRDataProviderOfflineModeError;
- (_Bool)dzrIsDZRDataProviderCacheInvalidatedError;
- (_Bool)dzrIsDZRDataProviderCacheExpiredError;
- (_Bool)dzrIsDZRDataProviderCacheMissError;
- (_Bool)dzrIsDZRDataProviderError;
@end

