//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCComponent.h"

@class NSString, RCAPIRequest;

@interface RCComponentDisclaimerRequest : RCComponent
{
    _Bool _isDisclaimer;
    RCAPIRequest *_apiRequest;
    NSString *_disclaimerId;
    NSString *_disclaimerTitle;
    NSString *_disclaimerText_id;
    NSString *_disclaimerCheckboxTextId;
}

@property(nonatomic) _Bool isDisclaimer; // @synthesize isDisclaimer=_isDisclaimer;
@property(retain, nonatomic) NSString *disclaimerCheckboxTextId; // @synthesize disclaimerCheckboxTextId=_disclaimerCheckboxTextId;
@property(retain, nonatomic) NSString *disclaimerText_id; // @synthesize disclaimerText_id=_disclaimerText_id;
@property(retain, nonatomic) NSString *disclaimerTitle; // @synthesize disclaimerTitle=_disclaimerTitle;
@property(retain, nonatomic) NSString *disclaimerId; // @synthesize disclaimerId=_disclaimerId;
@property(retain, nonatomic) RCAPIRequest *apiRequest; // @synthesize apiRequest=_apiRequest;
- (void).cxx_destruct;
- (id)initWithAPIRequest:(id)arg1 diclaimerId:(id)arg2 disclaimerTitle:(id)arg3 disclaimerCheckboxTitle:(id)arg4 andDisclaimerText:(id)arg5;

@end

