//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SASMediationAdapter.h"

#import "AdinCubeBannerDelegate-Protocol.h"
#import "AdinCubeInterstitialDelegate-Protocol.h"
#import "AdinCubeRewardedDelegate-Protocol.h"

@class AdinCubeBannerView, AdinCubeInterstitial, AdinCubeRewarded, NSNumber, NSString, SASAdView, SASReward, UIView, UIViewController;

@interface SASAdInCubeAdapter : SASMediationAdapter <AdinCubeBannerDelegate, AdinCubeInterstitialDelegate, AdinCubeRewardedDelegate>
{
    _Bool _isDisplayingInterstitial;
    SASAdView *_adView;
    UIViewController *_rootViewController;
    NSString *_applicationID;
    long long _adUnitType;
    UIView *_adInCubeAdView;
    AdinCubeBannerView *_bannerView;
    AdinCubeInterstitial *_interstitial;
    NSString *_rewardCurrency;
    NSNumber *_rewardAmount;
    SASReward *_sasReward;
    AdinCubeRewarded *_rewardedVideoAd;
}

@property(retain, nonatomic) AdinCubeRewarded *rewardedVideoAd; // @synthesize rewardedVideoAd=_rewardedVideoAd;
@property(retain, nonatomic) SASReward *sasReward; // @synthesize sasReward=_sasReward;
@property(retain, nonatomic) NSNumber *rewardAmount; // @synthesize rewardAmount=_rewardAmount;
@property(retain, nonatomic) NSString *rewardCurrency; // @synthesize rewardCurrency=_rewardCurrency;
@property(nonatomic) _Bool isDisplayingInterstitial; // @synthesize isDisplayingInterstitial=_isDisplayingInterstitial;
@property(retain, nonatomic) AdinCubeInterstitial *interstitial; // @synthesize interstitial=_interstitial;
@property(retain, nonatomic) AdinCubeBannerView *bannerView; // @synthesize bannerView=_bannerView;
@property(retain, nonatomic) UIView *adInCubeAdView; // @synthesize adInCubeAdView=_adInCubeAdView;
@property(nonatomic) long long adUnitType; // @synthesize adUnitType=_adUnitType;
@property(retain, nonatomic) NSString *applicationID; // @synthesize applicationID=_applicationID;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak SASAdView *adView; // @synthesize adView=_adView;
- (void).cxx_destruct;
- (int)bannerAdSize;
- (void)didHideRewarded;
- (void)didCompleteRewarded;
- (void)didClickOnRewarded;
- (void)didFailToShowRewarded:(id)arg1;
- (void)didShowRewarded;
- (void)didFailToFetchRewarded:(id)arg1;
- (void)didFetchRewarded;
- (void)didHideInterstitial;
- (void)didClickOnInterstitial;
- (void)didFailToShowInterstitial:(id)arg1;
- (void)didShowInterstitial;
- (void)didCacheInterstitial;
- (void)didClickOnBanner:(id)arg1;
- (void)didFailToShowBanner:(id)arg1 withError:(id)arg2;
- (void)didShowBanner:(id)arg1;
- (void)didFailToLoadBanner:(id)arg1 withError:(id)arg2;
- (void)didLoadBanner:(id)arg1;
- (void)handleFailureWithError:(id)arg1 forView:(id)arg2;
- (id)mediationAdView;
- (_Bool)isRewardedVideoAdReady;
- (void)showRewardedVideoAdFromViewController:(id)arg1;
- (void)cancelAd;
- (void)requestRewardedVideoAd;
- (void)requestInterstitialAd;
- (void)requestBannerAdWithSize:(int)arg1;
- (void)requestAd;
- (id)initMediationAdViewWithAdView:(id)arg1 adParameters:(id)arg2 interfaceParameters:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

