//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, SASPreviewPlacement, SASStrippedView, UIButton;
@protocol SASLivePreviewControlsViewDelegate;

@interface SASLivePreviewControlsView : UIView
{
    _Bool _expanded;
    _Bool _locked;
    _Bool _interstitialStyle;
    SASPreviewPlacement *_placement;
    id <SASLivePreviewControlsViewDelegate> _delegate;
    UIButton *_btnPreview;
    CAShapeLayer *_btnPreviewBorder;
    SASStrippedView *_grayedView;
    UIButton *_btnArrow;
    UIView *_actionView;
    UIButton *_btnRefresh;
    UIButton *_btnStop;
    double _headerHeight;
    double _expandHeight;
}

@property(nonatomic) double expandHeight; // @synthesize expandHeight=_expandHeight;
@property(nonatomic) double headerHeight; // @synthesize headerHeight=_headerHeight;
@property(nonatomic) _Bool interstitialStyle; // @synthesize interstitialStyle=_interstitialStyle;
@property(nonatomic) _Bool locked; // @synthesize locked=_locked;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
@property(retain, nonatomic) UIButton *btnStop; // @synthesize btnStop=_btnStop;
@property(retain, nonatomic) UIButton *btnRefresh; // @synthesize btnRefresh=_btnRefresh;
@property(retain, nonatomic) UIView *actionView; // @synthesize actionView=_actionView;
@property(retain, nonatomic) UIButton *btnArrow; // @synthesize btnArrow=_btnArrow;
@property(retain, nonatomic) SASStrippedView *grayedView; // @synthesize grayedView=_grayedView;
@property(retain, nonatomic) CAShapeLayer *btnPreviewBorder; // @synthesize btnPreviewBorder=_btnPreviewBorder;
@property(retain, nonatomic) UIButton *btnPreview; // @synthesize btnPreview=_btnPreview;
@property(nonatomic) __weak id <SASLivePreviewControlsViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak SASPreviewPlacement *placement; // @synthesize placement=_placement;
- (void).cxx_destruct;
- (void)updateFrameForSuperview:(id)arg1;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(id)arg1;
- (void)removeGrayedView;
- (void)addGrayedView;
- (void)unlock;
- (void)lock;
- (void)softLockContols;
- (void)lockControls:(_Bool)arg1;
- (void)deactivate;
- (void)expand:(_Bool)arg1;
- (void)stopButtonTapped:(id)arg1;
- (void)refreshButtonTapped:(id)arg1;
- (void)expandButtonTapped:(id)arg1;
- (void)viewSwippedDown:(id)arg1;
- (void)addStopButton;
- (void)addRefreshButton;
- (void)removeActionView;
- (void)addActionView;
- (void)addCloseButton;
- (void)configurePreviewButtonForLockedState:(_Bool)arg1;
- (void)addPreviewButton;
- (void)drawTopRightCornerMaskToView:(id)arg1;
- (void)initializeInterface;
- (_Bool)isLocked;
- (_Bool)isExpanded;
- (double)totalHeight;
- (id)initWithPlacement:(id)arg1 interstitialStyle:(_Bool)arg2;
- (void)removeFromSuperview;
- (void)dealloc;

@end

