//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GlobalLogEvent.h"

@class NSDictionary, NSString;

@interface UTMLogEvent : GlobalLogEvent
{
    NSString *_utm_source;
    NSString *_utm_campaign;
    NSString *_utm_medium;
    NSString *_utm_term;
    NSString *_utm_content;
    NSString *_timeStamp;
    NSDictionary *_content;
}

+ (id)logUTMEventWithSource:(id)arg1 UTMCampaign:(id)arg2 UTMMedium:(id)arg3 UTMTerm:(id)arg4 UTMContent:(id)arg5;
+ (int)logPhase;
+ (id)persistedPropertiesNames;
+ (id)filePrefix;
@property(retain, nonatomic) NSDictionary *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *timeStamp; // @synthesize timeStamp=_timeStamp;
@property(retain, nonatomic) NSString *utm_content; // @synthesize utm_content=_utm_content;
@property(retain, nonatomic) NSString *utm_term; // @synthesize utm_term=_utm_term;
@property(retain, nonatomic) NSString *utm_medium; // @synthesize utm_medium=_utm_medium;
@property(retain, nonatomic) NSString *utm_campaign; // @synthesize utm_campaign=_utm_campaign;
@property(retain, nonatomic) NSString *utm_source; // @synthesize utm_source=_utm_source;
- (void).cxx_destruct;
- (id)channelName;
- (_Bool)isVirtualEvent;
- (id)logContent;

@end

