//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPModule.h"

#import "GCDAsyncSocketDelegate-Protocol.h"

@class GCDAsyncSocket, NSMutableArray, NSString, XMPPIDTracker;

@interface XMPPFileTransfer : XMPPModule <GCDAsyncSocketDelegate>
{
    unsigned char _streamMethods;
    XMPPIDTracker *_idTracker;
    GCDAsyncSocket *_asyncSocket;
    NSMutableArray *_streamhosts;
    _Bool _disableDirectTransfers;
    _Bool _disableSOCKS5;
    _Bool _disableIBB;
    NSString *_sid;
}

@property(nonatomic) _Bool disableIBB; // @synthesize disableIBB=_disableIBB;
@property(nonatomic) _Bool disableSOCKS5; // @synthesize disableSOCKS5=_disableSOCKS5;
@property(nonatomic) _Bool disableDirectTransfers; // @synthesize disableDirectTransfers=_disableDirectTransfers;
@property(copy, nonatomic) NSString *sid; // @synthesize sid=_sid;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

