//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class ARIAndroidGeneralComplexTextDetails, ARIAndroidTextDetails, ARIPhotosAndroidAutobackupSettingsTextDetails_DeviceFolderBackupTextDetails, NSMutableArray;

@interface ARIPhotosAndroidAutobackupSettingsTextDetails : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) ARIAndroidTextDetails *autoBackupAccountLabel; // @dynamic autoBackupAccountLabel;
@property(retain, nonatomic) ARIAndroidTextDetails *autoBackupSubText; // @dynamic autoBackupSubText;
@property(retain, nonatomic) ARIAndroidTextDetails *autoBackupSwitchLabel; // @dynamic autoBackupSwitchLabel;
@property(retain, nonatomic) ARIAndroidTextDetails *autoBackupTitleText; // @dynamic autoBackupTitleText;
@property(retain, nonatomic) ARIAndroidTextDetails *backupAndSyncHelpText; // @dynamic backupAndSyncHelpText;
@property(retain, nonatomic) ARIAndroidGeneralComplexTextDetails *backupDeviceFoldersSummaryText; // @dynamic backupDeviceFoldersSummaryText;
@property(retain, nonatomic) ARIAndroidTextDetails *backupDeviceFoldersTitleText; // @dynamic backupDeviceFoldersTitleText;
@property(retain, nonatomic) ARIAndroidTextDetails *buyStorageButtonText; // @dynamic buyStorageButtonText;
@property(retain, nonatomic) ARIPhotosAndroidAutobackupSettingsTextDetails_DeviceFolderBackupTextDetails *deviceFolderBackupText; // @dynamic deviceFolderBackupText;
@property(nonatomic) _Bool hasAutoBackupAccountLabel; // @dynamic hasAutoBackupAccountLabel;
@property(nonatomic) _Bool hasAutoBackupSubText; // @dynamic hasAutoBackupSubText;
@property(nonatomic) _Bool hasAutoBackupSwitchLabel; // @dynamic hasAutoBackupSwitchLabel;
@property(nonatomic) _Bool hasAutoBackupTitleText; // @dynamic hasAutoBackupTitleText;
@property(nonatomic) _Bool hasBackupAndSyncHelpText; // @dynamic hasBackupAndSyncHelpText;
@property(nonatomic) _Bool hasBackupDeviceFoldersSummaryText; // @dynamic hasBackupDeviceFoldersSummaryText;
@property(nonatomic) _Bool hasBackupDeviceFoldersTitleText; // @dynamic hasBackupDeviceFoldersTitleText;
@property(nonatomic) _Bool hasBuyStorageButtonText; // @dynamic hasBuyStorageButtonText;
@property(nonatomic) _Bool hasDeviceFolderBackupText; // @dynamic hasDeviceFolderBackupText;
@property(nonatomic) _Bool hasStoragePromotionText; // @dynamic hasStoragePromotionText;
@property(nonatomic) _Bool hasUploadCellularPhotosSwitchText; // @dynamic hasUploadCellularPhotosSwitchText;
@property(nonatomic) _Bool hasUploadCellularTitleText; // @dynamic hasUploadCellularTitleText;
@property(nonatomic) _Bool hasUploadCellularVideosSwitchText; // @dynamic hasUploadCellularVideosSwitchText;
@property(nonatomic) _Bool hasUploadQualityText; // @dynamic hasUploadQualityText;
@property(nonatomic) _Bool hasUploadQualityTitleText; // @dynamic hasUploadQualityTitleText;
@property(nonatomic) _Bool hasUploadRoamingSwitchText; // @dynamic hasUploadRoamingSwitchText;
@property(nonatomic) _Bool hasUploadTimeTitleText; // @dynamic hasUploadTimeTitleText;
@property(retain, nonatomic) ARIAndroidGeneralComplexTextDetails *storagePromotionText; // @dynamic storagePromotionText;
@property(retain, nonatomic) ARIAndroidTextDetails *uploadCellularPhotosSwitchText; // @dynamic uploadCellularPhotosSwitchText;
@property(retain, nonatomic) ARIAndroidTextDetails *uploadCellularTitleText; // @dynamic uploadCellularTitleText;
@property(retain, nonatomic) ARIAndroidTextDetails *uploadCellularVideosSwitchText; // @dynamic uploadCellularVideosSwitchText;
@property(retain, nonatomic) NSMutableArray *uploadQualityDetailArray; // @dynamic uploadQualityDetailArray;
@property(readonly, nonatomic) unsigned long long uploadQualityDetailArray_Count; // @dynamic uploadQualityDetailArray_Count;
@property(retain, nonatomic) ARIAndroidGeneralComplexTextDetails *uploadQualityText; // @dynamic uploadQualityText;
@property(retain, nonatomic) ARIAndroidTextDetails *uploadQualityTitleText; // @dynamic uploadQualityTitleText;
@property(retain, nonatomic) ARIAndroidTextDetails *uploadRoamingSwitchText; // @dynamic uploadRoamingSwitchText;
@property(retain, nonatomic) ARIAndroidTextDetails *uploadTimeTitleText; // @dynamic uploadTimeTitleText;

@end

