//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GPMCloudQueueCastChannelDelegate-Protocol.h"
#import "GPMCloudQueuePlaybackProtocol-Protocol.h"

@class GPMCloudQueueCastChannel, NSString;
@protocol GPMCloudQueueSessionChangeDelegate;

@interface CloudQueueMessageStream : NSObject <GPMCloudQueueCastChannelDelegate, GPMCloudQueuePlaybackProtocol>
{
    GPMCloudQueueCastChannel *_castChannel;
    id <GPMCloudQueueSessionChangeDelegate> _cloudQueueSessionChangeDelegate;
}

@property(nonatomic) __weak id <GPMCloudQueueSessionChangeDelegate> cloudQueueSessionChangeDelegate; // @synthesize cloudQueueSessionChangeDelegate=_cloudQueueSessionChangeDelegate;
@property(readonly, nonatomic) GPMCloudQueueCastChannel *castChannel; // @synthesize castChannel=_castChannel;
- (void).cxx_destruct;
- (void)castChannel:(id)arg1 didReceiveTextMessage:(id)arg2 withNamespace:(id)arg3;
- (void)castChannelDidDisconnect:(id)arg1;
- (void)castChannelDidConnect:(id)arg1;
- (void)joinSession;
- (void)sendMessage:(id)arg1;
- (void)reset;
- (void)skipWoodstockTrack;
- (void)sendRefreshCloudQueueCommand:(id)arg1;
- (void)dealloc;
- (void)setupObservers;
- (id)initWithCastChannel:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

