//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVAssetResourceLoaderDelegate-Protocol.h"

@class AVURLAsset, NSString;
@protocol AVAssetResourceLoaderDelegate;

@interface DashToHLSResourceLoader : NSObject <AVAssetResourceLoaderDelegate>
{
    id <AVAssetResourceLoaderDelegate> _avDelegate;
    AVURLAsset *_originalAsset;
}

@property(readonly) __weak AVURLAsset *originalAsset; // @synthesize originalAsset=_originalAsset;
@property(readonly) id <AVAssetResourceLoaderDelegate> avDelegate; // @synthesize avDelegate=_avDelegate;
- (void).cxx_destruct;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForRenewalOfRequestedResource:(id)arg2;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (id)initWithDelegate:(id)arg1 asset:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

