//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DogfoodUtils : NSObject
{
}

+ (int)secItemAdd:(id)arg1 result:(id *)arg2;
+ (int)secItemCopyMatching:(id)arg1 result:(id *)arg2;
+ (id)computeAppIdentifierPrefix;
+ (id)applicationIdentifierPrefix;
+ (_Bool)isFirstLaunchAfterChangingApplicationIdentifier;

@end

