//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GGLInstanceIDAuthKeychain, GGLInstanceIDBackupExcludedPlist, NSString;

@interface GGLInstanceIDCheckinStore : NSObject
{
    GGLInstanceIDBackupExcludedPlist *_plist;
    GGLInstanceIDAuthKeychain *_keychain;
}

@property(retain, nonatomic) GGLInstanceIDAuthKeychain *keychain; // @synthesize keychain=_keychain;
@property(retain, nonatomic) GGLInstanceIDBackupExcludedPlist *plist; // @synthesize plist=_plist;
- (void).cxx_destruct;
- (_Bool)migrateCheckinItemIfNeeded;
- (void)moveCheckinAuthPreferencesToKeychain;
- (id)cachedCheckinPreferences;
- (_Bool)removeCheckinPreferencesWithError:(id *)arg1;
- (_Bool)saveCheckinPreferences:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) NSString *bundleIdentifierForKeychainAccount;
- (_Bool)hasCheckinPlist;
- (id)initWithCheckinPlist:(id)arg1 keychain:(id)arg2;
- (id)initWithCheckinPlistFileName:(id)arg1;

@end

