//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GPDBDatabaseDelegateManager, NSMutableArray, NSMutableSet, NSPredicate, NSString;

@interface GPDBDatabaseConnectionPool : NSObject
{
    GPDBDatabaseDelegateManager *_delegateManager;
    _Bool _newConnectionsAllowed;
    NSMutableSet *_activeConnections;
    unsigned long long _largestRecordedActiveConnectionCount;
    NSMutableSet *_idleConnections;
    NSMutableArray *_scalarExtensionFunctions;
    NSMutableArray *_collateExtensionFunctions;
    NSPredicate *_idleConnectionPredicate;
    NSString *_path;
}

@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)restrictIdleConnections;
- (id)connectionAddingReferenceWithHandler:(CDUnknownBlockType)arg1 error:(id *)arg2;
- (void)cleanupLeakedConnection:(id)arg1;
- (_Bool)updateIdleStateOfConnection:(id)arg1;
- (void)closeIdleConnections;
- (void)forceClose;
- (void)close;
- (_Bool)openWithError:(id *)arg1;
- (_Bool)defineCollationFunction:(CDUnknownFunctionPointerType)arg1 name:(id)arg2 userData:(id)arg3 error:(id *)arg4;
- (_Bool)defineScalarFunction:(CDUnknownFunctionPointerType)arg1 name:(id)arg2 argCount:(long long)arg3 deterministic:(_Bool)arg4 userData:(id)arg5 error:(id *)arg6;
- (void)dealloc;
- (id)initWithPath:(id)arg1 delegateManager:(id)arg2;
- (id)init;

@end

