//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AEModule.h"

@class AEArray, AEManagedValue, AERenderer, NSArray;

@interface GPMAudioPlayerSplicerModule : AEModule
{
    AEArray *_subModuleEntryArray;
    CDStruct_2e79dc9b *_currentEntry;
    unsigned int _silenceFramesMostRecentCallToProcess;
    AEManagedValue *_subrendererValue;
}

@property(retain, nonatomic) AEManagedValue *subrendererValue; // @synthesize subrendererValue=_subrendererValue;
- (void).cxx_destruct;
- (void)rendererDidChangeNumberOfChannels;
- (void)rendererDidChangeSampleRate;
- (CDStruct_2e79dc9b *)newEntryForModule:(id)arg1 availableSamplesFunction:(CDUnknownFunctionPointerType)arg2;
@property(readonly, nonatomic) NSArray *modules;
- (void)clearModules;
- (void)advanceToNextModule;
- (void)setNextModule:(id)arg1 availableSamplesFunction:(CDUnknownFunctionPointerType)arg2;
- (void)setCurrentModule:(id)arg1 availableSamplesFunction:(CDUnknownFunctionPointerType)arg2;
@property(retain, nonatomic) AERenderer *subrenderer;
- (id)initWithRenderer:(id)arg1;

@end

