//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPMCircularCardViewModel.h"

@interface GPMArtistViewModel : GPMCircularCardViewModel
{
}

+ (id)menuAccessibilityLabelForArtist:(id)arg1;
+ (id)accessibilityLabelForArtist:(id)arg1;
- (id)initWithArtist:(id)arg1;

@end

