//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IMAAdsManager;
@protocol IMAAdPlaybackInfo;

@interface GPMIMAAdsManagerWrapper : NSObject
{
    IMAAdsManager *_adsManager;
    id <IMAAdPlaybackInfo> _adPlaybackInfo;
}

@property(readonly, nonatomic) id <IMAAdPlaybackInfo> adPlaybackInfo; // @synthesize adPlaybackInfo=_adPlaybackInfo;
- (void).cxx_destruct;
- (void)unloadAdsManager;
- (void)skip;
- (void)resume;
- (void)pause;
- (void)start;
- (void)setAdsRenderingSettings:(id)arg1;
- (void)adPlaybackInfowithHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithIMAAdsManager:(id)arg1 delegate:(id)arg2;

@end

