//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class GPMButton;
@protocol GPMQuizArtistsLoadMoreDelegate;

@interface GPMQuizArtistsLoadMoreView : UICollectionReusableView
{
    GPMButton *_loadMoreButton;
    id <GPMQuizArtistsLoadMoreDelegate> _delegate;
}

@property(nonatomic) __weak id <GPMQuizArtistsLoadMoreDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)loadMoreTapped;
- (void)layoutSubviews;
- (void)setupLoadMoreButton;
- (id)initWithFrame:(struct CGRect)arg1;

@end

