//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MusicCollectionViewController.h"

#import "GPMBannerAdDisplay-Protocol.h"
#import "OfflineMusicManagerDelegate-Protocol.h"
#import "TrackListDetailHeaderDelegate-Protocol.h"

@class GPMRadioStationAnnotation, ItemList, NSMutableDictionary, NSString, RadioStation, TrackListDetailHeader;
@protocol GPMRadioStationAnnotationLoaderDelegate;

@interface GPMRadioStationCollectionViewController : MusicCollectionViewController <OfflineMusicManagerDelegate, TrackListDetailHeaderDelegate, GPMBannerAdDisplay>
{
    RadioStation *_radioStation;
    ItemList *_annotationItemList;
    NSMutableDictionary *_sectionTitles;
    GPMRadioStationAnnotation *_radioStationAnnotation;
    id <GPMRadioStationAnnotationLoaderDelegate> _delegate;
    TrackListDetailHeader *_detailHeader;
}

@property(readonly, nonatomic) TrackListDetailHeader *detailHeader; // @synthesize detailHeader=_detailHeader;
@property(nonatomic) __weak id <GPMRadioStationAnnotationLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateHeaderPlayingIndicator;
- (void)updatePlayingIndicator;
- (void)configureDetailHeader;
- (_Bool)isPinningUIEnabled;
- (id)defaultDescriptionForRadio:(id)arg1;
- (id)defaultRadioSubtitle;
- (void)showDefaultData;
- (id)arrayOfRelatedStations:(id)arg1;
- (id)arrayOfRelatedArtists:(id)arg1;
- (void)updateDownloadingUI;
- (void)updateDetailHeaderButtonsWithIsInMyLibrary:(_Bool)arg1;
- (id)radioTitleFromAnnotation:(id)arg1;
- (id)navigationPrimaryScrollView;
- (_Bool)shouldDisplayEmptyScreen;
- (void)buttonClickedWithType:(unsigned long long)arg1 sender:(id)arg2;
- (void)displayContextMenu:(id)arg1;
- (void)toggleDownloadTrackList:(id)arg1;
- (void)profileImageClicked;
- (void)readMoreClicked;
- (void)pauseClicked;
- (void)playClicked;
- (void)progressDidUpdate:(double)arg1;
- (void)pinnedStateDidChange:(_Bool)arg1;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (void)card:(id)arg1 clickedAtIndexPath:(id)arg2;
- (id)pageContainerItem;
- (double)heightForItemAtIndexPath:(id)arg1 withWidth:(double)arg2;
- (unsigned long long)numberOfColumnsInSection:(unsigned long long)arg1;
- (id)titleForSection:(unsigned long long)arg1;
- (void)updateDetailHeaderWithAnnotation:(id)arg1;
- (void)loadRadioStationAnnotationForSeed:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)loadItemsWithLoadingHandler:(CDUnknownBlockType)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (id)cardDataSourceForItem:(id)arg1 atIndexPath:(id)arg2;
- (id)reusableIdentifierForItem:(id)arg1 atIndexPath:(id)arg2;
- (void)registerCollectionIdentifiers;
- (id)musicItemProvider;
- (void)collectionView:(id)arg1 willDisplaySupplementaryView:(id)arg2 forElementKind:(id)arg3 atIndexPath:(id)arg4;
- (void)dealloc;
- (id)initWithRadioStation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

