//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTLRObject.h"

@class GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersModuleNowCardDescriptor, GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersSquarePlayableCardDescriptor, GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersTallPlayableCardDescriptor, GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersWidePlayableCardDescriptor;

@interface GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersGridCollectionSupportedRenderers : GTLRObject
{
}


// Remaining properties
@property(retain, nonatomic) GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersModuleNowCardDescriptor *moduleNowCard; // @dynamic moduleNowCard;
@property(retain, nonatomic) GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersSquarePlayableCardDescriptor *squarePlayableCard; // @dynamic squarePlayableCard;
@property(retain, nonatomic) GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersTallPlayableCardDescriptor *tallPlayableCard; // @dynamic tallPlayableCard;
@property(retain, nonatomic) GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersWidePlayableCardDescriptor *widePlayableCard; // @dynamic widePlayableCard;
@end

