//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTLRObject.h"

@class NSNumber;

@interface GTLRSJ_PodcastseriesuserpreferencesResource : GTLRObject
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *autoDownload; // @dynamic autoDownload;
@property(retain, nonatomic) NSNumber *notifyOnNewEpisode; // @dynamic notifyOnNewEpisode;
@property(retain, nonatomic) NSNumber *subscribed; // @dynamic subscribed;
@end

