//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTLRObject.h"

@class NSArray, NSNumber, NSString;

@interface GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1RenderersFullBleedModuleList : GTLRObject
{
}

+ (id)arrayPropertyToClassMap;

// Remaining properties
@property(retain, nonatomic) NSNumber *initialModuleIndex; // @dynamic initialModuleIndex;
@property(retain, nonatomic) NSArray *modules; // @dynamic modules;
@property(copy, nonatomic) NSString *recentsModuleToken; // @dynamic recentsModuleToken;

@end

