//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTLRObject.h"

@class GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1VisualsColor, NSNumber;

@interface GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1VisualsPaletteEntry : GTLRObject
{
}

+ (id)propertyToJSONKeyMap;

// Remaining properties
@property(retain, nonatomic) GTLRMusicPA_GoogleInternalPlayMusicInnerjamV1VisualsColor *color; // @dynamic color;
@property(retain, nonatomic) NSNumber *identifier; // @dynamic identifier;

@end

