//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPMTabbedViewController.h"

#import "GPMBannerAdDisplay-Protocol.h"

@class NSString;

@interface MyLibraryViewController : GPMTabbedViewController <GPMBannerAdDisplay>
{
    _Bool _viewAppeared;
}

- (_Bool)shouldShowBannerAdForCurrentView;
- (long long)initialTabIndexForTabbedCollectionViewController:(id)arg1;
- (void)tabbedCollectionViewController:(id)arg1 didShowViewController:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

