//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString, RadioConstraints;

@interface RadioContinuationResponse : NSObject
{
    NSDate *_currentTimestamp;
    NSArray *_skipHistory;
    RadioConstraints *_radioConstraints;
    NSString *_sessionToken;
}

@property(copy, nonatomic) NSString *sessionToken; // @synthesize sessionToken=_sessionToken;
@property(readonly, nonatomic) RadioConstraints *radioConstraints; // @synthesize radioConstraints=_radioConstraints;
@property(copy, nonatomic) NSArray *skipHistory; // @synthesize skipHistory=_skipHistory;
@property(readonly, nonatomic) NSDate *currentTimestamp; // @synthesize currentTimestamp=_currentTimestamp;
- (void).cxx_destruct;
- (id)initWithMQSContinuationResponse:(id)arg1;

@end

