//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTMFetcherAuthorizationProtocol-Protocol.h"

@class NSArray, NSDate, NSMutableURLRequest, NSObject, NSString, SSOIdentity;
@protocol OS_dispatch_queue;

@protocol SSOAuthorization <GTMFetcherAuthorizationProtocol>
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *refreshAccessTokenCallbackQueue;
@property(readonly, nonatomic) NSArray *scopes;
@property(readonly, nonatomic, getter=isLibraryAuth) _Bool libraryAuth;
@property(readonly, nonatomic) SSOIdentity *identity;
@property(readonly, nonatomic) NSDate *tokenExpirationDate;
@property(readonly, nonatomic) NSString *accessToken;
@property _Bool shouldAuthorizeAllRequests;
@property(readonly) _Bool canAuthorize;
- (void)refreshAccessTokenWithCompletionHandler:(void (^)(NSError *))arg1;
- (void)authorizeRequest:(NSMutableURLRequest *)arg1 completionHandler:(void (^)(NSError *))arg2;

@optional
@property(readonly, nonatomic) unsigned long long delegationType;
@property(readonly, copy, nonatomic) NSString *delegateeUserID;
@end

