//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MusicItem.h"

#import "GPMShareableItem-Protocol.h"
#import "QueueableContainer-Protocol.h"

@class Album, Artist, Genre, NSNumber, NSString;

@interface Track : MusicItem <GPMShareableItem, QueueableContainer>
{
    _Bool _audioAd;
    _Bool _trackArtistDerived;
    _Bool _albumArtistDerived;
    NSString *_title;
    NSString *_lockerID;
    NSString *_NID;
    NSString *_albumArtistString;
    NSString *_albumArtURLString;
    NSString *_composer;
    NSNumber *_trackNumber;
    NSNumber *_discNumber;
    NSNumber *_recentTimestamp;
    NSNumber *_creationTimestamp;
    NSNumber *_lastModified;
    double _duration;
    NSNumber *_rating;
    NSNumber *_lastRatingChangeTimestamp;
    long long _year;
    long long _estimatedSize;
    long long _trackType;
    long long _contentType;
    NSString *_youTubeVideoID;
    NSString *_youTubeVideoArtURLString;
    NSString *_wEntryID;
    NSString *_streamAuthID;
    Album *_album;
    Artist *_artist;
    Genre *_genre;
    NSString *_canonicalID;
    long long _playCount;
}

@property(nonatomic) long long playCount; // @synthesize playCount=_playCount;
@property(copy, nonatomic) NSString *canonicalID; // @synthesize canonicalID=_canonicalID;
@property(retain, nonatomic) Genre *genre; // @synthesize genre=_genre;
@property(retain, nonatomic) Artist *artist; // @synthesize artist=_artist;
@property(retain, nonatomic) Album *album; // @synthesize album=_album;
@property(nonatomic, getter=isAlbumArtistDerived) _Bool albumArtistDerived; // @synthesize albumArtistDerived=_albumArtistDerived;
@property(nonatomic, getter=isTrackArtistDerived) _Bool trackArtistDerived; // @synthesize trackArtistDerived=_trackArtistDerived;
@property(nonatomic, getter=isAudioAd) _Bool audioAd; // @synthesize audioAd=_audioAd;
@property(copy, nonatomic) NSString *streamAuthID; // @synthesize streamAuthID=_streamAuthID;
@property(copy, nonatomic) NSString *wEntryID; // @synthesize wEntryID=_wEntryID;
@property(copy, nonatomic) NSString *youTubeVideoArtURLString; // @synthesize youTubeVideoArtURLString=_youTubeVideoArtURLString;
@property(copy, nonatomic) NSString *youTubeVideoID; // @synthesize youTubeVideoID=_youTubeVideoID;
@property(nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(nonatomic) long long trackType; // @synthesize trackType=_trackType;
@property(nonatomic) long long estimatedSize; // @synthesize estimatedSize=_estimatedSize;
@property(nonatomic) long long year; // @synthesize year=_year;
@property(retain, nonatomic) NSNumber *lastRatingChangeTimestamp; // @synthesize lastRatingChangeTimestamp=_lastRatingChangeTimestamp;
@property(retain, nonatomic) NSNumber *rating; // @synthesize rating=_rating;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSNumber *lastModified; // @synthesize lastModified=_lastModified;
@property(retain, nonatomic) NSNumber *creationTimestamp; // @synthesize creationTimestamp=_creationTimestamp;
@property(retain, nonatomic) NSNumber *recentTimestamp; // @synthesize recentTimestamp=_recentTimestamp;
@property(retain, nonatomic) NSNumber *discNumber; // @synthesize discNumber=_discNumber;
@property(retain, nonatomic) NSNumber *trackNumber; // @synthesize trackNumber=_trackNumber;
@property(copy, nonatomic) NSString *composer; // @synthesize composer=_composer;
@property(copy, nonatomic) NSString *albumArtURLString; // @synthesize albumArtURLString=_albumArtURLString;
@property(copy, nonatomic) NSString *albumArtistString; // @synthesize albumArtistString=_albumArtistString;
@property(copy, nonatomic) NSString *NID; // @synthesize NID=_NID;
@property(copy, nonatomic) NSString *lockerID; // @synthesize lockerID=_lockerID;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)queueableContainerInfo;
- (id)supportedContextMenuKeysForAvailabilityState:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)hasContextMenu;
- (_Bool)isEquivalentToMusicItem:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)musicQueueSyncTrack;
- (id)sjTrack;
- (id)generateLockerArtistKey;
- (id)generateLockerAlbumKey;
@property(readonly, nonatomic) NSString *displayName;
@property(readonly) NSString *cacheID;
- (_Bool)isWoodstockTrack;
- (_Bool)isSubscriptionTrack;
- (_Bool)isEphemeralTrack;
- (_Bool)hasLockerIDOrNID;
- (_Bool)isLockerTrack;
- (void)populateFromMQSTrack:(id)arg1;
- (void)populateFromSJTrack:(id)arg1;
- (id)initWithMQSTrack:(id)arg1;
- (id)initWithSJTrack:(id)arg1;
- (id)sharingSubject;
- (void)sharingURLWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)isShareableWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)tagDictionary;
- (id)playLogContainer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

