//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Anghami17HelpListViewModel.h"

@interface _TtC7Anghami21HelpSectionsViewModel : _TtC7Anghami17HelpListViewModel
{
    // Error parsing type: , name: categoryId
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithCategoryId:(id)arg1;

@end

