//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7Anghami22ANGGiftsViewController.h"

@class ANGAsyncImageView, NSLayoutConstraint, UIButton, UILabel, UIStackView, UIView;

@interface _TtC7Anghami31ANGGiftsShowOfferViewController : _TtC7Anghami22ANGGiftsViewController
{
    // Error parsing type: , name: stackView
    // Error parsing type: , name: iconImageView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: mainButton
    // Error parsing type: , name: secondaryButton
    // Error parsing type: , name: seeMoreButton
    // Error parsing type: , name: tncButton
    // Error parsing type: , name: seeMoreButtonRow
    // Error parsing type: , name: tncButtonRow
    // Error parsing type: , name: secondaryButtonRow
    // Error parsing type: , name: iconHeightC
    // Error parsing type: , name: titleLabelTopC
    // Error parsing type: , name: titleLabelBotC
    // Error parsing type: , name: subtitleLabelTopC
    // Error parsing type: , name: subtitleLabelBotC
    // Error parsing type: , name: mainButtonTopC
    // Error parsing type: , name: mainButtonBotC
    // Error parsing type: , name: mainButtonHeightC
    // Error parsing type: , name: secondaryButtonBotC
    // Error parsing type: , name: secondaryButtonHeightC
    // Error parsing type: , name: seeMoreButtonBotC
    // Error parsing type: , name: seeMoreButtonTopC
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)tncButtonAction:(id)arg1;
- (void)seeMoreButtonAction:(id)arg1;
- (void)secondaryButtonAction:(id)arg1;
- (void)mainButtonAction:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak NSLayoutConstraint *seeMoreButtonTopC; // @synthesize seeMoreButtonTopC;
@property(nonatomic) __weak NSLayoutConstraint *seeMoreButtonBotC; // @synthesize seeMoreButtonBotC;
@property(nonatomic) __weak NSLayoutConstraint *secondaryButtonHeightC; // @synthesize secondaryButtonHeightC;
@property(nonatomic) __weak NSLayoutConstraint *secondaryButtonBotC; // @synthesize secondaryButtonBotC;
@property(nonatomic) __weak NSLayoutConstraint *mainButtonHeightC; // @synthesize mainButtonHeightC;
@property(nonatomic) __weak NSLayoutConstraint *mainButtonBotC; // @synthesize mainButtonBotC;
@property(nonatomic) __weak NSLayoutConstraint *mainButtonTopC; // @synthesize mainButtonTopC;
@property(nonatomic) __weak NSLayoutConstraint *subtitleLabelBotC; // @synthesize subtitleLabelBotC;
@property(nonatomic) __weak NSLayoutConstraint *subtitleLabelTopC; // @synthesize subtitleLabelTopC;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelBotC; // @synthesize titleLabelBotC;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelTopC; // @synthesize titleLabelTopC;
@property(nonatomic) __weak NSLayoutConstraint *iconHeightC; // @synthesize iconHeightC;
@property(nonatomic) __weak UIView *secondaryButtonRow; // @synthesize secondaryButtonRow;
@property(nonatomic) __weak UIView *tncButtonRow; // @synthesize tncButtonRow;
@property(nonatomic) __weak UIView *seeMoreButtonRow; // @synthesize seeMoreButtonRow;
@property(nonatomic) __weak UIButton *tncButton; // @synthesize tncButton;
@property(nonatomic) __weak UIButton *seeMoreButton; // @synthesize seeMoreButton;
@property(nonatomic) __weak UIButton *secondaryButton; // @synthesize secondaryButton;
@property(nonatomic) __weak UIButton *mainButton; // @synthesize mainButton;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak ANGAsyncImageView *iconImageView; // @synthesize iconImageView;
@property(nonatomic) __weak UIStackView *stackView; // @synthesize stackView;

@end

