//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class ANGLink, ANGLinkCardView, UIView;

@interface ANGLinkCardTableViewCell : UITableViewCell
{
    ANGLink *_link;
    UIView *_containerView;
    ANGLinkCardView *_cardView;
}

@property(retain, nonatomic) ANGLinkCardView *cardView; // @synthesize cardView=_cardView;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) ANGLink *link; // @synthesize link=_link;
- (void).cxx_destruct;
- (void)addLinkCardView;
- (void)awakeFromNib;

@end

