//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ANGAsyncImageView, ANGLink, UIImageView, UILabel;

@interface ANGLinkHeaderSwiperViewItem : UIView
{
    ANGLink *_link;
    ANGAsyncImageView *_linkImageView;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UILabel *_superTitleLabel;
    UIImageView *_arrowImageView;
}

@property(nonatomic) __weak UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) __weak UILabel *superTitleLabel; // @synthesize superTitleLabel=_superTitleLabel;
@property(nonatomic) __weak UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak ANGAsyncImageView *linkImageView; // @synthesize linkImageView=_linkImageView;
@property(retain, nonatomic) ANGLink *link; // @synthesize link=_link;
- (void).cxx_destruct;
- (void)addShadowToLabel:(id)arg1;
- (void)updateView;
- (void)initWithLink:(id)arg1;

@end

