//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ANGSectionedContentSongsListViewController.h"

#import "ANGOptionsSelectorDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSMutableSet, NSString, UILabel, UIProgressView;

@interface ANGSectionedContentDownloadsViewController : ANGSectionedContentSongsListViewController <ANGOptionsSelectorDelegate>
{
    _Bool _onOtherDevicesShown;
    long long _onOtherDevicesCount;
    _Bool _sortedAlphabetically;
    NSString *_lastSearchText;
    UILabel *_downloadingLabel;
    NSArray *_songs;
    NSArray *_artists;
    NSArray *_tempArtists;
    NSMutableSet *_allSongsInQueue;
    float _progress;
    UIProgressView *_progressView;
    _Bool _isShowingTitleSelector;
    _Bool _showDownloadedPlaylists;
    NSArray *_downloadedSongsList;
    NSArray *_downloadingSongsList;
    NSMutableArray *_onOtherDevices;
    NSArray *_filteredArtists;
    unsigned long long _selectedTab;
    NSDictionary *_numSongsAndAlbumsForArtist;
    NSArray *_downloadedPlaylists;
    NSMutableArray *_filteredPlaylists;
}

@property(retain, nonatomic) NSMutableArray *filteredPlaylists; // @synthesize filteredPlaylists=_filteredPlaylists;
@property(retain, nonatomic) NSArray *downloadedPlaylists; // @synthesize downloadedPlaylists=_downloadedPlaylists;
@property(nonatomic) _Bool showDownloadedPlaylists; // @synthesize showDownloadedPlaylists=_showDownloadedPlaylists;
@property(retain, nonatomic) NSDictionary *numSongsAndAlbumsForArtist; // @synthesize numSongsAndAlbumsForArtist=_numSongsAndAlbumsForArtist;
@property(nonatomic) unsigned long long selectedTab; // @synthesize selectedTab=_selectedTab;
@property(retain, nonatomic) NSArray *filteredArtists; // @synthesize filteredArtists=_filteredArtists;
@property(retain, nonatomic) NSArray *artists; // @synthesize artists=_artists;
@property(retain, nonatomic) NSMutableArray *onOtherDevices; // @synthesize onOtherDevices=_onOtherDevices;
@property(retain, nonatomic) NSArray *downloadingSongsList; // @synthesize downloadingSongsList=_downloadingSongsList;
@property(retain, nonatomic) NSArray *downloadedSongsList; // @synthesize downloadedSongsList=_downloadedSongsList;
- (void).cxx_destruct;
- (long long)headerPlaySource;
- (long long)headerShuffleSource;
- (long long)enginePlaySource;
- (_Bool)isStoreCell:(long long)arg1;
- (id)previewObjectForIndexPath:(id)arg1 collectionView:(id)arg2 section:(id)arg3 confirmActionRef:(CDUnknownBlockType *)arg4;
- (_Bool)navigationMinimizes;
- (_Bool)availableInOfflineMode;
- (_Bool)supportsEmptyView;
- (_Bool)isShowingSongs;
- (_Bool)sortedAlphabetically;
- (id)customTitle;
- (void)clearSongs;
- (id)clearMessage;
- (id)searchPlaceholder;
- (id)songsEmptyViewImageName;
- (id)songsEmptyViewSubtitle;
- (id)songsEmptyViewTitle;
- (id)addSongsEmptyView;
- (id)addSongsView;
- (void)subscribeAction:(id)arg1;
- (id)addSubscribeView;
- (void)didTapHeaderMainButton;
- (id)headerMainButtonTitle;
- (void)addSongsAction;
- (void)showDownloading;
- (void)onOtherDevicesAction;
- (void)enableAutoDownloadsAction;
- (void)publicToggleAction:(id)arg1;
- (void)optionSelected:(id)arg1 valueChanged:(unsigned long long)arg2 andRowString:(id)arg3;
- (void)optionSelected:(id)arg1 valueChanged:(unsigned long long)arg2;
- (id)optionsForSection:(unsigned long long)arg1;
- (id)optionsSelectorImageNameForSection:(unsigned long long)arg1;
- (id)optionsSelectorTitleForSection:(unsigned long long)arg1;
- (unsigned long long)optionsSelectorNumberOfRowsForSection:(unsigned long long)arg1;
- (unsigned long long)optionsSelectorNumberOfSections;
- (id)arrayOfTitleSelectorRows;
- (void)optButtonPressed;
- (void)filterPressed;
- (id)songs;
- (_Bool)shouldShowSearchField;
- (double)searchFieldSpace;
- (void)performSearchWithText:(id)arg1;
- (void)songDownloadProgressChanged:(id)arg1;
- (void)connectionStateDidChange:(id)arg1;
- (void)songAdded;
- (void)songAdded:(id)arg1;
- (id)downloadNotification;
- (void)unregisterForNotifications;
- (void)registerForNotifications;
- (void)reloadTitle;
- (void)setNumberOfSongs:(long long)arg1 isVideo:(_Bool)arg2;
- (_Bool)shouldShowEmptySongsView;
- (_Bool)hasDownloads;
- (id)defaultHeaderButtons;
- (id)headerBarImageViewLabels;
- (id)downloadingTitle;
- (_Bool)headerBackgroundGradientViewVisible;
- (_Bool)canChangeOrder;
- (_Bool)hasButtonsView;
- (double)initialHeaderViewHeight;
- (void)reloadHeader;
- (void)updateContentSection;
- (void)loadServerData;
- (void)reloadBackingData;
- (void)resetDownloadingParams;
- (void)constructPlayQueueForSection:(id)arg1 atIndex:(unsigned long long)arg2 isVideoPlayQueue:(_Bool)arg3 showPlayerForVideo:(_Bool)arg4;
- (void)deleteSong:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)hasStoreCell;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

