//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDate;

@interface ANGSearchAutoCompleteCacheItem : NSObject
{
    NSDate *_resultDate;
    NSData *_result;
}

@property(retain, nonatomic) NSData *result; // @synthesize result=_result;
@property(retain, nonatomic) NSDate *resultDate; // @synthesize resultDate=_resultDate;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isExpired;
- (id)initWithData:(id)arg1;

@end

