//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AnghamiNewTableViewController.h"

#import "ISHPullUpSizingDelegate-Protocol.h"
#import "ISHPullUpStateDelegate-Protocol.h"

@class ANGStoryChapter, ISHPullUpHandleView, ISHPullUpViewController, UINavigationController, UITapGestureRecognizer;

@interface ANGStoryChapterViewsContextSheet : AnghamiNewTableViewController <ISHPullUpSizingDelegate, ISHPullUpStateDelegate>
{
    UITapGestureRecognizer *_tapToDismiss;
    ISHPullUpViewController *_pullUpController;
    UINavigationController *_navigationController;
    CDUnknownBlockType _dismissCompletionBlock;
    ISHPullUpHandleView *_handleView;
    ANGStoryChapter *_chapter;
}

+ (void)presentContextSheetForItem:(id)arg1;
@property(retain, nonatomic) ANGStoryChapter *chapter; // @synthesize chapter=_chapter;
@property(retain, nonatomic) ISHPullUpHandleView *handleView; // @synthesize handleView=_handleView;
@property(copy, nonatomic) CDUnknownBlockType dismissCompletionBlock; // @synthesize dismissCompletionBlock=_dismissCompletionBlock;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak ISHPullUpViewController *pullUpController; // @synthesize pullUpController=_pullUpController;
- (void).cxx_destruct;
- (void)pullUpViewController:(id)arg1 didChangeToState:(unsigned long long)arg2;
- (void)pullUpViewController:(id)arg1 updateEdgeInsets:(struct UIEdgeInsets)arg2 forBottomViewController:(id)arg3;
- (_Bool)shouldShowHandleView;
- (double)minimumHeightForBottomController;
- (void)dismissOnDragging;
- (double)pullUpViewController:(id)arg1 targetHeightForBottomViewController:(id)arg2 fromCurrentHeight:(double)arg3;
- (double)totalHeightForBottomView;
- (double)rowHeight;
- (double)pullUpViewController:(id)arg1 minimumHeightForBottomViewController:(id)arg2;
- (double)pullUpViewController:(id)arg1 maximumHeightForBottomViewController:(id)arg2 maximumAvailableHeight:(double)arg3;
- (void)handleTapBehind:(id)arg1;
- (void)removeTapToDismiss;
- (void)addTapToDismiss;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (_Bool)shouldAutorotate;
- (void)dismiss:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)dealloc;
- (_Bool)showConnectivityBar;
- (void)refreshActions:(_Bool)arg1;
- (void)refreshActions;
- (void)viewWillAppear:(_Bool)arg1;
- (id)tableViewBackgroundColor;
- (void)setupHandleView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (_Bool)availableInOfflineMode;
- (id)initWithChapter:(id)arg1;

@end

