//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class ANGAsyncImageView, ANGUserVideoComment, NSLayoutConstraint, NSObject, UILabel;
@protocol ANGUserVideoCommentTableViewCellDelegate;

@interface ANGUserVideoCommentTableViewCell : UITableViewCell
{
    ANGUserVideoComment *_comment;
    NSObject<ANGUserVideoCommentTableViewCellDelegate> *_delegate;
    UILabel *_usernameLabel;
    UILabel *_messageLabel;
    UILabel *_timeLabel;
    ANGAsyncImageView *_userImageView;
    NSLayoutConstraint *_userImageViewWidth;
    NSLayoutConstraint *_imageViewTopConstraint;
    NSLayoutConstraint *_spaceBetweenNameAndTextConstraint;
}

+ (double)messageLabelFreeSpace;
+ (double)heightForCellWithComment:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *spaceBetweenNameAndTextConstraint; // @synthesize spaceBetweenNameAndTextConstraint=_spaceBetweenNameAndTextConstraint;
@property(retain, nonatomic) NSLayoutConstraint *imageViewTopConstraint; // @synthesize imageViewTopConstraint=_imageViewTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *userImageViewWidth; // @synthesize userImageViewWidth=_userImageViewWidth;
@property(retain, nonatomic) ANGAsyncImageView *userImageView; // @synthesize userImageView=_userImageView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property __weak NSObject<ANGUserVideoCommentTableViewCellDelegate> *delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ANGUserVideoComment *comment; // @synthesize comment=_comment;
- (void).cxx_destruct;
- (void)longPressAction:(id)arg1;
- (void)addLongPressgesture;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

