//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ANGVideoView;

@protocol ANGVideoViewDelegate <NSObject>
- (void)videoViewDidLoseVideo:(ANGVideoView *)arg1;
- (void)videoViewDidAcquireVideo:(ANGVideoView *)arg1 isReady:(_Bool)arg2;
@end

