//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ANGAlertView;
@protocol AppiraterDelegate;

@interface Appirater : NSObject
{
    ANGAlertView *_ratingAlert;
    ANGAlertView *_questionAlert;
    NSObject<AppiraterDelegate> *_delegate;
}

+ (void)registerAppRated;
+ (void)rateApp;
+ (void)incrementSignificantEventCounterBy:(long long)arg1 canPromptForRating:(_Bool)arg2;
+ (void)userDidSignificantEvent:(_Bool)arg1;
+ (void)appEnteredForeground:(_Bool)arg1;
+ (void)appWillResignActive;
+ (void)appLaunched:(_Bool)arg1;
+ (void)appLaunched;
+ (void)showRatingAlert;
+ (id)sharedInstance;
+ (void)setDelegate:(id)arg1;
+ (void)setTimeBeforeReminding:(double)arg1;
+ (void)setSignificantEventsUntilPrompt:(long long)arg1;
+ (void)setUsesUntilPrompt:(long long)arg1;
+ (void)setDaysUntilPrompt:(double)arg1;
+ (void)setAppId:(id)arg1;
@property(nonatomic) __weak NSObject<AppiraterDelegate> *delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ANGAlertView *questionAlert; // @synthesize questionAlert=_questionAlert;
@property(retain, nonatomic) ANGAlertView *ratingAlert; // @synthesize ratingAlert=_ratingAlert;
- (void).cxx_destruct;
- (void)hideRatingAlert;
- (void)incrementSignificantEventsBy:(long long)arg1 andRate:(_Bool)arg2;
- (void)incrementAndRate:(_Bool)arg1;
- (void)incrementSignificantEventCountBy:(long long)arg1;
- (void)incrementUseCount;
- (_Bool)ratingConditionsHaveBeenMet;
- (void)setRateLater;
- (void)setRefusedToRate;
- (void)showRateAnghamiIOS9;
- (void)showRatingAlert;
- (_Bool)connectedToNetwork;

@end

