//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "LoaderDelegate-Protocol.h"

@class NSString;

@interface ArtistFollowManager : NSObject <LoaderDelegate>
{
    _Bool following;
    _Bool radioEnabled;
    _Bool hidden;
    NSString *_artistID;
    NSString *_extras;
}

+ (id)singleton;
@property(retain, nonatomic) NSString *extras; // @synthesize extras=_extras;
@property(retain, nonatomic) NSString *artistID; // @synthesize artistID=_artistID;
- (void).cxx_destruct;
- (_Bool)isHidden;
@property(readonly, nonatomic) _Bool radioEnabled;
@property(readonly, nonatomic) _Bool isFollowing;
- (void)updateFollow:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadArtistWithId:(id)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

