//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDecimalNumber, NSMutableArray, NSMutableDictionary, NSString;

@interface BranchEvent : NSObject
{
    NSMutableDictionary *_customData;
    NSMutableArray *_contentItems;
    NSString *_transactionID;
    NSString *_currency;
    NSDecimalNumber *_revenue;
    NSDecimalNumber *_shipping;
    NSDecimalNumber *_tax;
    NSString *_coupon;
    NSString *_affiliation;
    NSString *_eventDescription;
    NSString *_searchQuery;
    NSString *_eventName;
}

+ (id)standardEvents;
+ (id)customEventWithName:(id)arg1 contentItem:(id)arg2;
+ (id)customEventWithName:(id)arg1;
+ (id)standardEvent:(id)arg1 withContentItem:(id)arg2;
+ (id)standardEvent:(id)arg1;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
@property(retain, nonatomic) NSString *searchQuery; // @synthesize searchQuery=_searchQuery;
@property(retain, nonatomic) NSString *eventDescription; // @synthesize eventDescription=_eventDescription;
@property(retain, nonatomic) NSString *affiliation; // @synthesize affiliation=_affiliation;
@property(retain, nonatomic) NSString *coupon; // @synthesize coupon=_coupon;
@property(retain, nonatomic) NSDecimalNumber *tax; // @synthesize tax=_tax;
@property(retain, nonatomic) NSDecimalNumber *shipping; // @synthesize shipping=_shipping;
@property(retain, nonatomic) NSDecimalNumber *revenue; // @synthesize revenue=_revenue;
@property(retain, nonatomic) NSString *currency; // @synthesize currency=_currency;
@property(retain, nonatomic) NSString *transactionID; // @synthesize transactionID=_transactionID;
- (void).cxx_destruct;
- (id)description;
- (void)logEvent;
- (id)dictionary;
@property(copy, nonatomic) NSMutableArray *contentItems;
@property(copy, nonatomic) NSMutableDictionary *customData;
- (id)initWithName:(id)arg1;

@end

