//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CBZSplashView.h"

#import "CAAnimationDelegate-Protocol.h"

@class CAGradientLayer, CALayer, NSString, UIColor;

@interface CBZVectorSplashView : CBZSplashView <CAAnimationDelegate>
{
    CDUnknownBlockType _animationCompletionHandler;
    CAGradientLayer *_iconLayer;
    UIColor *_backgroundViewColor;
    CALayer *_backgroundLayer;
}

@property(retain, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(retain, nonatomic) UIColor *backgroundViewColor; // @synthesize backgroundViewColor=_backgroundViewColor;
@property(retain, nonatomic) CAGradientLayer *iconLayer; // @synthesize iconLayer=_iconLayer;
@property(copy, nonatomic) CDUnknownBlockType animationCompletionHandler; // @synthesize animationCompletionHandler=_animationCompletionHandler;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)startAnimationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)_createShapeLayerWithBezierPath:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)initWithBezierPath:(id)arg1 backgroundColor:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

