//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface FBSDKProfileExpressionApplicationStateManager : NSObject
{
    _Bool _wasLaunchedFromFacebook;
    NSDictionary *_currentMetadata;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool wasLaunchedFromFacebook; // @synthesize wasLaunchedFromFacebook=_wasLaunchedFromFacebook;
@property(retain, nonatomic) NSDictionary *currentMetadata; // @synthesize currentMetadata=_currentMetadata;
- (void).cxx_destruct;
- (void)resetState;
- (void)dealloc;
- (void)applicationDidEnterBackground:(id)arg1;
- (id)_init;

@end

