//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNotificationCenter.h>

@interface NSNotificationCenter (MainThread)
+ (void)removeObserverOnMainThread:(id)arg1 name:(id)arg2 object:(id)arg3;
+ (void)removeObserverOnMainThread:(id)arg1;
+ (void)addObserverOnMainThreadAsync:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;
+ (void)addObserverOnMainThread:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;
+ (void)postNotificationToMainThreadWithName:(id)arg1;
+ (void)postNotificationToMainThreadWithName:(id)arg1 object:(id)arg2;
+ (void)postNotificationToMainThreadWithName:(id)arg1 userInfo:(id)arg2;
+ (void)postNotificationToMainThreadWithName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
+ (void)postNotificationInternal:(id)arg1;
@end

