//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RLMArrayLinkViewHandoverMetadata : NSObject
{
    NSString *_parentClassName;
    NSString *_key;
}

@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *parentClassName; // @synthesize parentClassName=_parentClassName;
- (void).cxx_destruct;

@end

