//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

#import "UITextViewDelegate-Protocol.h"

@class NSArray, NSAttributedString, NSDictionary, NSLayoutManager, NSMutableArray, NSRegularExpression, NSString, NSTextContainer, NSTextStorage, UIColor, UITextView;

@interface STTweetLabel : UILabel <UITextViewDelegate>
{
    _Bool _isTouchesMoved;
    struct _NSRange _selectableRange;
    long long _firstCharIndex;
    struct CGPoint _firstTouchLocation;
    _Bool _leftToRight;
    _Bool _textSelectable;
    NSArray *_validProtocols;
    UIColor *_selectionColor;
    CDUnknownBlockType _detectionBlock;
    NSRegularExpression *_urlRegex;
    NSTextStorage *_textStorage;
    NSLayoutManager *_layoutManager;
    NSTextContainer *_textContainer;
    NSString *_cleanText;
    NSAttributedString *_cleanAttributedText;
    NSMutableArray *_rangesOfHotWords;
    NSDictionary *_attributesText;
    NSDictionary *_attributesHandle;
    NSDictionary *_attributesHashtag;
    NSDictionary *_attributesLink;
    UITextView *_textView;
}

@property(retain) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSDictionary *attributesLink; // @synthesize attributesLink=_attributesLink;
@property(retain, nonatomic) NSDictionary *attributesHashtag; // @synthesize attributesHashtag=_attributesHashtag;
@property(retain, nonatomic) NSDictionary *attributesHandle; // @synthesize attributesHandle=_attributesHandle;
@property(retain, nonatomic) NSDictionary *attributesText; // @synthesize attributesText=_attributesText;
@property(retain) NSMutableArray *rangesOfHotWords; // @synthesize rangesOfHotWords=_rangesOfHotWords;
@property(copy, nonatomic) NSAttributedString *cleanAttributedText; // @synthesize cleanAttributedText=_cleanAttributedText;
@property(retain, nonatomic) NSString *cleanText; // @synthesize cleanText=_cleanText;
@property(retain) NSTextContainer *textContainer; // @synthesize textContainer=_textContainer;
@property(retain) NSLayoutManager *layoutManager; // @synthesize layoutManager=_layoutManager;
@property(retain) NSTextStorage *textStorage; // @synthesize textStorage=_textStorage;
@property(retain, nonatomic) NSRegularExpression *urlRegex; // @synthesize urlRegex=_urlRegex;
@property(copy, nonatomic) CDUnknownBlockType detectionBlock; // @synthesize detectionBlock=_detectionBlock;
@property(retain, nonatomic) UIColor *selectionColor; // @synthesize selectionColor=_selectionColor;
@property(nonatomic) _Bool textSelectable; // @synthesize textSelectable=_textSelectable;
@property(nonatomic) _Bool leftToRight; // @synthesize leftToRight=_leftToRight;
@property(retain, nonatomic) NSArray *validProtocols; // @synthesize validProtocols=_validProtocols;
- (void).cxx_destruct;
- (void)setText:(id)arg1 withHotWordsRanges:(id)arg2;
- (id)getTouchedHotword:(id)arg1;
- (long long)charIndexAtLocation:(struct CGPoint)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)isLeftToRight;
- (id)attributesForHotWord:(long long)arg1;
- (id)attributes;
- (id)text;
- (void)setAttributedText:(id)arg1;
- (void)setTextAlignment:(long long)arg1;
- (void)setAttributes:(id)arg1 hotWord:(long long)arg2;
- (void)setAttributes:(id)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)hotWordsList;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)suggestedFrameSizeToFitEntireStringConstrainedToWidth:(double)arg1;
- (void)updateText;
- (void)determineLinks;
- (void)determineHotWords;
- (void)setupLabel;
- (void)copy:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)setupURLRegularExpression;
- (void)setupTextView;
- (id)defaultFontToUse;
- (void)setupColorsSignals;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

