//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface UIScrollView (GSKStretchyHeaderView)
- (void)gsk_layoutStretchyHeaderView:(id)arg1 contentOffset:(struct CGPoint)arg2 previousContentOffset:(struct CGPoint)arg3;
- (void)gsk_arrangeStretchyHeaderView:(id)arg1;
- (void)gsk_fixZPositionsForStretchyHeaderView:(id)arg1;
@end

