//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (Anghami)
- (void)setDarkenGradientLayerWithAlpha1:(double)arg1 alpha2:(double)arg2;
- (void)setGradientLayerWithColor:(id)arg1;
- (void)setGradientLayerWithColors:(id)arg1 layerName:(id)arg2;
@end

